// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// WaInstanceIdInstanceAddGroupParticipantApiTokenInstancePost implements POST /waInstance{idInstance}/addGroupParticipant/{apiTokenInstance} operation.
//
// Документация [AddGroupParticipant](https://green-api.
// com/v3/docs/api/groups/AddGroupParticipant/).
//
// POST /waInstance{idInstance}/addGroupParticipant/{apiTokenInstance}
func (UnimplementedHandler) WaInstanceIdInstanceAddGroupParticipantApiTokenInstancePost(ctx context.Context, req OptWaInstanceIdInstanceAddGroupParticipantApiTokenInstancePostReq, params WaInstanceIdInstanceAddGroupParticipantApiTokenInstancePostParams) (r WaInstanceIdInstanceAddGroupParticipantApiTokenInstancePostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// WaInstanceIdInstanceCheckAccountApiTokenInstancePost implements POST /waInstance{idInstance}/checkAccount/{apiTokenInstance} operation.
//
// Документация [CheckAccount](https://green-api.com/v3/docs/api/service/CheckAccount/).
//
// POST /waInstance{idInstance}/checkAccount/{apiTokenInstance}
func (UnimplementedHandler) WaInstanceIdInstanceCheckAccountApiTokenInstancePost(ctx context.Context, req OptWaInstanceIdInstanceCheckAccountApiTokenInstancePostReq, params WaInstanceIdInstanceCheckAccountApiTokenInstancePostParams) (r WaInstanceIdInstanceCheckAccountApiTokenInstancePostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// WaInstanceIdInstanceClearMessagesQueueApiTokenInstanceGet implements GET /waInstance{idInstance}/clearMessagesQueue/{apiTokenInstance} operation.
//
// Документация [ClearMessagesQueue](https://green-api.
// com/v3/docs/api/queues/ClearMessagesQueue/).
//
// GET /waInstance{idInstance}/clearMessagesQueue/{apiTokenInstance}
func (UnimplementedHandler) WaInstanceIdInstanceClearMessagesQueueApiTokenInstanceGet(ctx context.Context, params WaInstanceIdInstanceClearMessagesQueueApiTokenInstanceGetParams) (r *WaInstanceIdInstanceClearMessagesQueueApiTokenInstanceGetOKHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// WaInstanceIdInstanceClearWebhooksQueueApiTokenInstanceDelete implements DELETE /waInstance{idInstance}/clearWebhooksQueue/{apiTokenInstance} operation.
//
// Документация [ClearWebhooksQueue](https://green-api.
// com/v3/docs/api/queues/ClearWebhooksQueue/).
//
// DELETE /waInstance{idInstance}/clearWebhooksQueue/{apiTokenInstance}
func (UnimplementedHandler) WaInstanceIdInstanceClearWebhooksQueueApiTokenInstanceDelete(ctx context.Context, params WaInstanceIdInstanceClearWebhooksQueueApiTokenInstanceDeleteParams) (r *WaInstanceIdInstanceClearWebhooksQueueApiTokenInstanceDeleteOKHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// WaInstanceIdInstanceCreateGroupApiTokenInstancePost implements POST /waInstance{idInstance}/createGroup/{apiTokenInstance} operation.
//
// Документация [CreateGroup](https://green-api.com/v3/docs/api/groups/CreateGroup/).
//
// POST /waInstance{idInstance}/createGroup/{apiTokenInstance}
func (UnimplementedHandler) WaInstanceIdInstanceCreateGroupApiTokenInstancePost(ctx context.Context, req OptWaInstanceIdInstanceCreateGroupApiTokenInstancePostReq, params WaInstanceIdInstanceCreateGroupApiTokenInstancePostParams) (r WaInstanceIdInstanceCreateGroupApiTokenInstancePostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// WaInstanceIdInstanceDeleteMessageApiTokenInstancePost implements POST /waInstance{idInstance}/deleteMessage/{apiTokenInstance} operation.
//
// Документация [DeleteMessage](https://green-api.com/v3/docs/api/service/DeleteMessage).
//
// POST /waInstance{idInstance}/deleteMessage/{apiTokenInstance}
func (UnimplementedHandler) WaInstanceIdInstanceDeleteMessageApiTokenInstancePost(ctx context.Context, req *WaInstanceIdInstanceDeleteMessageApiTokenInstancePostReq, params WaInstanceIdInstanceDeleteMessageApiTokenInstancePostParams) (r WaInstanceIdInstanceDeleteMessageApiTokenInstancePostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// WaInstanceIdInstanceDeleteNotificationApiTokenInstanceReceiptIdDelete implements DELETE /waInstance{idInstance}/deleteNotification/{apiTokenInstance}/{receiptId} operation.
//
// Документация [DeleteNotification](https://green-api.
// com/v3/docs/api/receiving/technology-http-api/DeleteNotification/).
//
// DELETE /waInstance{idInstance}/deleteNotification/{apiTokenInstance}/{receiptId}
func (UnimplementedHandler) WaInstanceIdInstanceDeleteNotificationApiTokenInstanceReceiptIdDelete(ctx context.Context, params WaInstanceIdInstanceDeleteNotificationApiTokenInstanceReceiptIdDeleteParams) (r *WaInstanceIdInstanceDeleteNotificationApiTokenInstanceReceiptIdDeleteOK, _ error) {
	return r, ht.ErrNotImplemented
}

// WaInstanceIdInstanceDownloadFileApiTokenInstancePost implements POST /waInstance{idInstance}/downloadFile/{apiTokenInstance} operation.
//
// Документация [DownloadFile](https://green-api.
// com/v3/docs/api/receiving/files/DownloadFile/).
//
// POST /waInstance{idInstance}/downloadFile/{apiTokenInstance}
func (UnimplementedHandler) WaInstanceIdInstanceDownloadFileApiTokenInstancePost(ctx context.Context, req OptWaInstanceIdInstanceDownloadFileApiTokenInstancePostReq, params WaInstanceIdInstanceDownloadFileApiTokenInstancePostParams) (r WaInstanceIdInstanceDownloadFileApiTokenInstancePostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// WaInstanceIdInstanceEditMessageApiTokenInstancePost implements POST /waInstance{idInstance}/editMessage/{apiTokenInstance} operation.
//
// Документация [EditMessage](https://green-api.com/v3/docs/api/service/EditMessage).
//
// POST /waInstance{idInstance}/editMessage/{apiTokenInstance}
func (UnimplementedHandler) WaInstanceIdInstanceEditMessageApiTokenInstancePost(ctx context.Context, req OptWaInstanceIdInstanceEditMessageApiTokenInstancePostReq, params WaInstanceIdInstanceEditMessageApiTokenInstancePostParams) (r WaInstanceIdInstanceEditMessageApiTokenInstancePostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// WaInstanceIdInstanceGetAccountSettingsApiTokenInstanceGet implements GET /waInstance{idInstance}/getAccountSettings/{apiTokenInstance} operation.
//
// Документация [GetAccountSettings](https://green-api.
// com/v3/docs/api/account/GetAccountSettings/).
//
// GET /waInstance{idInstance}/getAccountSettings/{apiTokenInstance}
func (UnimplementedHandler) WaInstanceIdInstanceGetAccountSettingsApiTokenInstanceGet(ctx context.Context, req *WaInstanceIdInstanceGetAccountSettingsApiTokenInstanceGetReq, params WaInstanceIdInstanceGetAccountSettingsApiTokenInstanceGetParams) (r *WaInstanceIdInstanceGetAccountSettingsApiTokenInstanceGetOKHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// WaInstanceIdInstanceGetAvatarApiTokenInstancePost implements POST /waInstance{idInstance}/getAvatar/{apiTokenInstance} operation.
//
// Документация [GetAvatar](https://green-api.com/v3/docs/api/service/GetAvatar).
//
// POST /waInstance{idInstance}/getAvatar/{apiTokenInstance}
func (UnimplementedHandler) WaInstanceIdInstanceGetAvatarApiTokenInstancePost(ctx context.Context, req OptWaInstanceIdInstanceGetAvatarApiTokenInstancePostReq, params WaInstanceIdInstanceGetAvatarApiTokenInstancePostParams) (r WaInstanceIdInstanceGetAvatarApiTokenInstancePostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// WaInstanceIdInstanceGetChatHistoryApiTokenInstancePost implements POST /waInstance{idInstance}/getChatHistory/{apiTokenInstance} operation.
//
// Документация [GetChatHistory](https://green-api.
// com/v3/docs/api/journals/GetChatHistory/).
//
// POST /waInstance{idInstance}/getChatHistory/{apiTokenInstance}
func (UnimplementedHandler) WaInstanceIdInstanceGetChatHistoryApiTokenInstancePost(ctx context.Context, req OptWaInstanceIdInstanceGetChatHistoryApiTokenInstancePostReq, params WaInstanceIdInstanceGetChatHistoryApiTokenInstancePostParams) (r WaInstanceIdInstanceGetChatHistoryApiTokenInstancePostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// WaInstanceIdInstanceGetChatsApiTokenInstanceGet implements GET /waInstance{idInstance}/GetChats/{apiTokenInstance} operation.
//
// Документация [GetChats](https://green-api.com/v3/docs/api/service/GetChats/).
//
// GET /waInstance{idInstance}/GetChats/{apiTokenInstance}
func (UnimplementedHandler) WaInstanceIdInstanceGetChatsApiTokenInstanceGet(ctx context.Context, params WaInstanceIdInstanceGetChatsApiTokenInstanceGetParams) (r *WaInstanceIdInstanceGetChatsApiTokenInstanceGetOKHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// WaInstanceIdInstanceGetContactInfoApiTokenInstancePost implements POST /waInstance{idInstance}/GetContactInfo/{apiTokenInstance} operation.
//
// Документация [GetContactInfo](https://green-api.
// com/v3/docs/api/service/GetContactInfo/).
//
// POST /waInstance{idInstance}/GetContactInfo/{apiTokenInstance}
func (UnimplementedHandler) WaInstanceIdInstanceGetContactInfoApiTokenInstancePost(ctx context.Context, req OptWaInstanceIdInstanceGetContactInfoApiTokenInstancePostReq, params WaInstanceIdInstanceGetContactInfoApiTokenInstancePostParams) (r WaInstanceIdInstanceGetContactInfoApiTokenInstancePostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// WaInstanceIdInstanceGetContactsApiTokenInstanceGet implements GET /waInstance{idInstance}/getContacts/{apiTokenInstance} operation.
//
// Документация [GetContacts](https://green-api.com/v3/docs/api/service/GetContacts/).
//
// GET /waInstance{idInstance}/getContacts/{apiTokenInstance}
func (UnimplementedHandler) WaInstanceIdInstanceGetContactsApiTokenInstanceGet(ctx context.Context, params WaInstanceIdInstanceGetContactsApiTokenInstanceGetParams) (r *WaInstanceIdInstanceGetContactsApiTokenInstanceGetOKHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// WaInstanceIdInstanceGetGroupDataApiTokenInstancePost implements POST /waInstance{idInstance}/getGroupData/{apiTokenInstance} operation.
//
// Документация [GetGroupData](https://green-api.com/v3/docs/api/groups/GetGroupData/).
//
// POST /waInstance{idInstance}/getGroupData/{apiTokenInstance}
func (UnimplementedHandler) WaInstanceIdInstanceGetGroupDataApiTokenInstancePost(ctx context.Context, req OptWaInstanceIdInstanceGetGroupDataApiTokenInstancePostReq, params WaInstanceIdInstanceGetGroupDataApiTokenInstancePostParams) (r WaInstanceIdInstanceGetGroupDataApiTokenInstancePostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// WaInstanceIdInstanceGetMessageApiTokenInstancePost implements POST /waInstance{idInstance}/getMessage/{apiTokenInstance} operation.
//
// Документация [GetMessage](https://green-api.com/v3/docs/api/journals/GetMessage/).
//
// POST /waInstance{idInstance}/getMessage/{apiTokenInstance}
func (UnimplementedHandler) WaInstanceIdInstanceGetMessageApiTokenInstancePost(ctx context.Context, req OptWaInstanceIdInstanceGetMessageApiTokenInstancePostReq, params WaInstanceIdInstanceGetMessageApiTokenInstancePostParams) (r WaInstanceIdInstanceGetMessageApiTokenInstancePostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// WaInstanceIdInstanceGetMessagesCountApiTokenInstanceGet implements GET /waInstance{idInstance}/getMessagesCount/{apiTokenInstance} operation.
//
// Документация [GetMessagesCount](https://green-api.
// com/v3/docs/api/queues/GetMessagesCount).
//
// GET /waInstance{idInstance}/getMessagesCount/{apiTokenInstance}
func (UnimplementedHandler) WaInstanceIdInstanceGetMessagesCountApiTokenInstanceGet(ctx context.Context, params WaInstanceIdInstanceGetMessagesCountApiTokenInstanceGetParams) (r *WaInstanceIdInstanceGetMessagesCountApiTokenInstanceGetOKHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// WaInstanceIdInstanceGetSettingsApiTokenInstanceGet implements GET /waInstance{idInstance}/getSettings/{apiTokenInstance} operation.
//
// Документация [GetSettings](https://green-api.com/v3/docs/api/account/GetSettings/).
//
// GET /waInstance{idInstance}/getSettings/{apiTokenInstance}
func (UnimplementedHandler) WaInstanceIdInstanceGetSettingsApiTokenInstanceGet(ctx context.Context, params WaInstanceIdInstanceGetSettingsApiTokenInstanceGetParams) (r *WaInstanceIdInstanceGetSettingsApiTokenInstanceGetOKHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// WaInstanceIdInstanceGetStateInstanceApiTokenInstanceGet implements GET /waInstance{idInstance}/getStateInstance/{apiTokenInstance} operation.
//
// Документация [GetStateInstance](https://green-api.
// com/v3/docs/api/account/GetStateInstance/).
//
// GET /waInstance{idInstance}/getStateInstance/{apiTokenInstance}
func (UnimplementedHandler) WaInstanceIdInstanceGetStateInstanceApiTokenInstanceGet(ctx context.Context, params WaInstanceIdInstanceGetStateInstanceApiTokenInstanceGetParams) (r *WaInstanceIdInstanceGetStateInstanceApiTokenInstanceGetOKHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// WaInstanceIdInstanceGetWebhooksCountApiTokenInstanceGet implements GET /waInstance{idInstance}/getWebhooksCount/{apiTokenInstance} operation.
//
// Документация [GetWebhooksCount](https://green-api.
// com/v3/docs/api/queues/GetWebhooksCount/).
//
// GET /waInstance{idInstance}/getWebhooksCount/{apiTokenInstance}
func (UnimplementedHandler) WaInstanceIdInstanceGetWebhooksCountApiTokenInstanceGet(ctx context.Context, params WaInstanceIdInstanceGetWebhooksCountApiTokenInstanceGetParams) (r *WaInstanceIdInstanceGetWebhooksCountApiTokenInstanceGetOKHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// WaInstanceIdInstanceLastIncomingMessagesApiTokenInstanceGet implements GET /waInstance{idInstance}/lastIncomingMessages/{apiTokenInstance} operation.
//
// Документация [LastIncomingMessages](https://green-api.
// com/v3/docs/api/journals/LastIncomingMessages/).
//
// GET /waInstance{idInstance}/lastIncomingMessages/{apiTokenInstance}
func (UnimplementedHandler) WaInstanceIdInstanceLastIncomingMessagesApiTokenInstanceGet(ctx context.Context, params WaInstanceIdInstanceLastIncomingMessagesApiTokenInstanceGetParams) (r *WaInstanceIdInstanceLastIncomingMessagesApiTokenInstanceGetOKHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// WaInstanceIdInstanceLastOutgoingMessagesApiTokenInstanceGet implements GET /waInstance{idInstance}/lastOutgoingMessages/{apiTokenInstance} operation.
//
// Документация [LastOutgoingMessages](https://green-api.
// com/v3/docs/api/journals/LastOutgoingMessages/).
//
// GET /waInstance{idInstance}/lastOutgoingMessages/{apiTokenInstance}
func (UnimplementedHandler) WaInstanceIdInstanceLastOutgoingMessagesApiTokenInstanceGet(ctx context.Context, params WaInstanceIdInstanceLastOutgoingMessagesApiTokenInstanceGetParams) (r *WaInstanceIdInstanceLastOutgoingMessagesApiTokenInstanceGetOKHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// WaInstanceIdInstanceLeaveGroupApiTokenInstancePost implements POST /waInstance{idInstance}/leaveGroup/{apiTokenInstance} operation.
//
// Документация [LeaveGroup](https://green-api.com/v3/docs/api/groups/LeaveGroup/).
//
// POST /waInstance{idInstance}/leaveGroup/{apiTokenInstance}
func (UnimplementedHandler) WaInstanceIdInstanceLeaveGroupApiTokenInstancePost(ctx context.Context, req OptWaInstanceIdInstanceLeaveGroupApiTokenInstancePostReq, params WaInstanceIdInstanceLeaveGroupApiTokenInstancePostParams) (r WaInstanceIdInstanceLeaveGroupApiTokenInstancePostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// WaInstanceIdInstanceLogoutApiTokenInstanceGet implements GET /waInstance{idInstance}/logout/{apiTokenInstance} operation.
//
// Документация [Logout](https://green-api.com/v3/docs/api/account/Logout/).
//
// GET /waInstance{idInstance}/logout/{apiTokenInstance}
func (UnimplementedHandler) WaInstanceIdInstanceLogoutApiTokenInstanceGet(ctx context.Context, params WaInstanceIdInstanceLogoutApiTokenInstanceGetParams) (r *WaInstanceIdInstanceLogoutApiTokenInstanceGetOKHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// WaInstanceIdInstanceQrApiTokenInstanceGet implements GET /waInstance{idInstance}/qr/{apiTokenInstance} operation.
//
// Документация [QR](https://green-api.com/v3/docs/api/account/QR/).
//
// GET /waInstance{idInstance}/qr/{apiTokenInstance}
func (UnimplementedHandler) WaInstanceIdInstanceQrApiTokenInstanceGet(ctx context.Context, params WaInstanceIdInstanceQrApiTokenInstanceGetParams) (r *WaInstanceIdInstanceQrApiTokenInstanceGetDefStatusCode, _ error) {
	return r, ht.ErrNotImplemented
}

// WaInstanceIdInstanceReadChatApiTokenInstancePost implements POST /waInstance{idInstance}/readChat/{apiTokenInstance} operation.
//
// Документация [ReadChat](https://green-api.com/v3/docs/api/marks/ReadChat/).
//
// POST /waInstance{idInstance}/readChat/{apiTokenInstance}
func (UnimplementedHandler) WaInstanceIdInstanceReadChatApiTokenInstancePost(ctx context.Context, req OptWaInstanceIdInstanceReadChatApiTokenInstancePostReq, params WaInstanceIdInstanceReadChatApiTokenInstancePostParams) (r WaInstanceIdInstanceReadChatApiTokenInstancePostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// WaInstanceIdInstanceRebootApiTokenInstanceGet implements GET /waInstance{idInstance}/reboot/{apiTokenInstance} operation.
//
// Документация [Reboot](https://green-api.com/v3/docs/api/account/Reboot/).
//
// GET /waInstance{idInstance}/reboot/{apiTokenInstance}
func (UnimplementedHandler) WaInstanceIdInstanceRebootApiTokenInstanceGet(ctx context.Context, params WaInstanceIdInstanceRebootApiTokenInstanceGetParams) (r *WaInstanceIdInstanceRebootApiTokenInstanceGetOKHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// WaInstanceIdInstanceReceiveNotificationApiTokenInstanceGet implements GET /waInstance{idInstance}/receiveNotification/{apiTokenInstance} operation.
//
// Документация [ReceiveNotification](https://green-api.
// com/v3/docs/api/receiving/technology-http-api/ReceiveNotification/).
//
// GET /waInstance{idInstance}/receiveNotification/{apiTokenInstance}
func (UnimplementedHandler) WaInstanceIdInstanceReceiveNotificationApiTokenInstanceGet(ctx context.Context, params WaInstanceIdInstanceReceiveNotificationApiTokenInstanceGetParams) (r *WaInstanceIdInstanceReceiveNotificationApiTokenInstanceGetOK, _ error) {
	return r, ht.ErrNotImplemented
}

// WaInstanceIdInstanceRemoveAdminApiTokenInstancePost implements POST /waInstance{idInstance}/removeAdmin/{apiTokenInstance} operation.
//
// Документация [RemoveAdmin](https://green-api.com/v3/docs/api/groups/RemoveAdmin/).
//
// POST /waInstance{idInstance}/removeAdmin/{apiTokenInstance}
func (UnimplementedHandler) WaInstanceIdInstanceRemoveAdminApiTokenInstancePost(ctx context.Context, req OptWaInstanceIdInstanceRemoveAdminApiTokenInstancePostReq, params WaInstanceIdInstanceRemoveAdminApiTokenInstancePostParams) (r WaInstanceIdInstanceRemoveAdminApiTokenInstancePostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// WaInstanceIdInstanceRemoveGroupParticipantApiTokenInstancePost implements POST /waInstance{idInstance}/removeGroupParticipant/{apiTokenInstance} operation.
//
// Документация [RemoveGroupParticipant](https://green-api.
// com/v3/docs/api/groups/RemoveGroupParticipant/).
//
// POST /waInstance{idInstance}/removeGroupParticipant/{apiTokenInstance}
func (UnimplementedHandler) WaInstanceIdInstanceRemoveGroupParticipantApiTokenInstancePost(ctx context.Context, req OptWaInstanceIdInstanceRemoveGroupParticipantApiTokenInstancePostReq, params WaInstanceIdInstanceRemoveGroupParticipantApiTokenInstancePostParams) (r WaInstanceIdInstanceRemoveGroupParticipantApiTokenInstancePostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// WaInstanceIdInstanceSendContactApiTokenInstancePost implements POST /waInstance{idInstance}/sendContact/{apiTokenInstance} operation.
//
// Документация [SendContact](https://green-api.com/v3/docs/api/sending/SendContact/).
//
// POST /waInstance{idInstance}/sendContact/{apiTokenInstance}
func (UnimplementedHandler) WaInstanceIdInstanceSendContactApiTokenInstancePost(ctx context.Context, req OptWaInstanceIdInstanceSendContactApiTokenInstancePostReq, params WaInstanceIdInstanceSendContactApiTokenInstancePostParams) (r WaInstanceIdInstanceSendContactApiTokenInstancePostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// WaInstanceIdInstanceSendFileByUploadApiTokenInstancePost implements POST /waInstance{idInstance}/sendFileByUpload/{apiTokenInstance} operation.
//
// Документация [SendFileByUpload](https://green-api.
// com/v3/docs/api/sending/SendFileByUpload).
//
// POST /waInstance{idInstance}/sendFileByUpload/{apiTokenInstance}
func (UnimplementedHandler) WaInstanceIdInstanceSendFileByUploadApiTokenInstancePost(ctx context.Context, params WaInstanceIdInstanceSendFileByUploadApiTokenInstancePostParams) (r WaInstanceIdInstanceSendFileByUploadApiTokenInstancePostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// WaInstanceIdInstanceSendFileByUrlApiTokenInstancePost implements POST /waInstance{idInstance}/sendFileByUrl/{apiTokenInstance} operation.
//
// Документация [SendFileByUrl](https://green-api.com/v3/docs/api/sending/SendFileByUrl).
//
// POST /waInstance{idInstance}/sendFileByUrl/{apiTokenInstance}
func (UnimplementedHandler) WaInstanceIdInstanceSendFileByUrlApiTokenInstancePost(ctx context.Context, req OptWaInstanceIdInstanceSendFileByUrlApiTokenInstancePostReq, params WaInstanceIdInstanceSendFileByUrlApiTokenInstancePostParams) (r WaInstanceIdInstanceSendFileByUrlApiTokenInstancePostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// WaInstanceIdInstanceSendLocationApiTokenInstancePost implements POST /waInstance{idInstance}/sendLocation/{apiTokenInstance} operation.
//
// Документация [SendLocation](https://green-api.com/v3/docs/api/sending/SendLocation/).
//
// POST /waInstance{idInstance}/sendLocation/{apiTokenInstance}
func (UnimplementedHandler) WaInstanceIdInstanceSendLocationApiTokenInstancePost(ctx context.Context, req OptWaInstanceIdInstanceSendLocationApiTokenInstancePostReq, params WaInstanceIdInstanceSendLocationApiTokenInstancePostParams) (r WaInstanceIdInstanceSendLocationApiTokenInstancePostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// WaInstanceIdInstanceSendMessageApiTokenInstancePost implements POST /waInstance{idInstance}/sendMessage/{apiTokenInstance} operation.
//
// Документация [SendMessage](https://green-api.com/v3/docs/api/sending/SendMessage/).
//
// POST /waInstance{idInstance}/sendMessage/{apiTokenInstance}
func (UnimplementedHandler) WaInstanceIdInstanceSendMessageApiTokenInstancePost(ctx context.Context, req OptWaInstanceIdInstanceSendMessageApiTokenInstancePostReq, params WaInstanceIdInstanceSendMessageApiTokenInstancePostParams) (r WaInstanceIdInstanceSendMessageApiTokenInstancePostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// WaInstanceIdInstanceSendTypingApiTokenInstancePost implements POST /waInstance{idInstance}/sendTyping/{apiTokenInstance} operation.
//
// Документация [SendTyping](https://green-api.com/v3/docs/api/service/SendTyping/).
//
// POST /waInstance{idInstance}/sendTyping/{apiTokenInstance}
func (UnimplementedHandler) WaInstanceIdInstanceSendTypingApiTokenInstancePost(ctx context.Context, req *WaInstanceIdInstanceSendTypingApiTokenInstancePostReq, params WaInstanceIdInstanceSendTypingApiTokenInstancePostParams) (r WaInstanceIdInstanceSendTypingApiTokenInstancePostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// WaInstanceIdInstanceSetGroupAdminApiTokenInstancePost implements POST /waInstance{idInstance}/setGroupAdmin/{apiTokenInstance} operation.
//
// Документация [SetGroupAdmin](https://green-api.com/v3/docs/api/groups/SetGroupAdmin/).
//
// POST /waInstance{idInstance}/setGroupAdmin/{apiTokenInstance}
func (UnimplementedHandler) WaInstanceIdInstanceSetGroupAdminApiTokenInstancePost(ctx context.Context, req OptWaInstanceIdInstanceSetGroupAdminApiTokenInstancePostReq, params WaInstanceIdInstanceSetGroupAdminApiTokenInstancePostParams) (r WaInstanceIdInstanceSetGroupAdminApiTokenInstancePostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// WaInstanceIdInstanceSetGroupPictureApiTokenInstancePost implements POST /waInstance{idInstance}/setGroupPicture/{apiTokenInstance} operation.
//
// Документация [SetGroupPicture](https://green-api.
// com/v3/docs/api/groups/SetGroupPicture/).
//
// POST /waInstance{idInstance}/setGroupPicture/{apiTokenInstance}
func (UnimplementedHandler) WaInstanceIdInstanceSetGroupPictureApiTokenInstancePost(ctx context.Context, params WaInstanceIdInstanceSetGroupPictureApiTokenInstancePostParams) (r WaInstanceIdInstanceSetGroupPictureApiTokenInstancePostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// WaInstanceIdInstanceSetProfilePictureApiTokenInstancePost implements POST /waInstance{idInstance}/setProfilePicture/{apiTokenInstance} operation.
//
// Документация [SetProfilePicture](https://green-api.
// com/v3/docs/api/account/SetProfilePicture/).
//
// POST /waInstance{idInstance}/setProfilePicture/{apiTokenInstance}
func (UnimplementedHandler) WaInstanceIdInstanceSetProfilePictureApiTokenInstancePost(ctx context.Context, params WaInstanceIdInstanceSetProfilePictureApiTokenInstancePostParams) (r WaInstanceIdInstanceSetProfilePictureApiTokenInstancePostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// WaInstanceIdInstanceSetSettingsApiTokenInstancePost implements POST /waInstance{idInstance}/setSettings/{apiTokenInstance} operation.
//
// Документация [SetSettings](https://green-api.com/v3/docs/api/account/SetSettings/).
//
// POST /waInstance{idInstance}/setSettings/{apiTokenInstance}
func (UnimplementedHandler) WaInstanceIdInstanceSetSettingsApiTokenInstancePost(ctx context.Context, req OptWaInstanceIdInstanceSetSettingsApiTokenInstancePostReq, params WaInstanceIdInstanceSetSettingsApiTokenInstancePostParams) (r *WaInstanceIdInstanceSetSettingsApiTokenInstancePostOKHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// WaInstanceIdInstanceShowMessagesQueueApiTokenInstanceGet implements GET /waInstance{idInstance}/showMessagesQueue/{apiTokenInstance} operation.
//
// Документация [ShowMessagesQueue](https://green-api.
// com/v3/docs/api/queues/ShowMessagesQueue/).
//
// GET /waInstance{idInstance}/showMessagesQueue/{apiTokenInstance}
func (UnimplementedHandler) WaInstanceIdInstanceShowMessagesQueueApiTokenInstanceGet(ctx context.Context, params WaInstanceIdInstanceShowMessagesQueueApiTokenInstanceGetParams) (r *WaInstanceIdInstanceShowMessagesQueueApiTokenInstanceGetOKHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// WaInstanceIdInstanceUpdateGroupNameApiTokenInstancePost implements POST /waInstance{idInstance}/updateGroupName/{apiTokenInstance} operation.
//
// Документация [UpdateGroupName](https://green-api.
// com/v3/docs/api/groups/UpdateGroupName/).
//
// POST /waInstance{idInstance}/updateGroupName/{apiTokenInstance}
func (UnimplementedHandler) WaInstanceIdInstanceUpdateGroupNameApiTokenInstancePost(ctx context.Context, req OptWaInstanceIdInstanceUpdateGroupNameApiTokenInstancePostReq, params WaInstanceIdInstanceUpdateGroupNameApiTokenInstancePostParams) (r WaInstanceIdInstanceUpdateGroupNameApiTokenInstancePostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// WaInstanceIdInstanceUpdateGroupSettingsApiTokenInstancePost implements POST /waInstance{idInstance}/updateGroupSettings/{apiTokenInstance} operation.
//
// Документация [UpdateGroupSettings](https://green-api.
// com/v3/docs/api/groups/UpdateGroupSettings/).
//
// POST /waInstance{idInstance}/updateGroupSettings/{apiTokenInstance}
func (UnimplementedHandler) WaInstanceIdInstanceUpdateGroupSettingsApiTokenInstancePost(ctx context.Context, req OptWaInstanceIdInstanceUpdateGroupSettingsApiTokenInstancePostReq, params WaInstanceIdInstanceUpdateGroupSettingsApiTokenInstancePostParams) (r WaInstanceIdInstanceUpdateGroupSettingsApiTokenInstancePostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// WaInstanceIdInstanceUploadFileApiTokenInstancePost implements POST /waInstance{idInstance}/uploadFile/{apiTokenInstance} operation.
//
// Документация [UploadFile](https://green-api.com/v3/docs/api/sending/UploadFile).
//
// POST /waInstance{idInstance}/uploadFile/{apiTokenInstance}
func (UnimplementedHandler) WaInstanceIdInstanceUploadFileApiTokenInstancePost(ctx context.Context, params WaInstanceIdInstanceUploadFileApiTokenInstancePostParams) (r WaInstanceIdInstanceUploadFileApiTokenInstancePostRes, _ error) {
	return r, ht.ErrNotImplemented
}
