// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"
	"strings"

	"github.com/ogen-go/ogen/uri"
)

func (s *Server) cutPrefix(path string) (string, bool) {
	prefix := s.cfg.Prefix
	if prefix == "" {
		return path, true
	}
	if !strings.HasPrefix(path, prefix) {
		// Prefix doesn't match.
		return "", false
	}
	// Cut prefix from the path.
	return strings.TrimPrefix(path, prefix), true
}

// ServeHTTP serves http request as defined by OpenAPI v3 specification,
// calling handler that matches the path or returning not found error.
func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	elem := r.URL.Path
	elemIsEscaped := false
	if rawPath := r.URL.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
			elemIsEscaped = strings.ContainsRune(elem, '%')
		}
	}

	elem, ok := s.cutPrefix(elem)
	if !ok || len(elem) == 0 {
		s.notFound(w, r)
		return
	}
	args := [3]string{}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/waInstance"

			if l := len("/waInstance"); len(elem) >= l && elem[0:l] == "/waInstance" {
				elem = elem[l:]
			} else {
				break
			}

			// Param: "idInstance"
			// Match until "/"
			idx := strings.IndexByte(elem, '/')
			if idx < 0 {
				idx = len(elem)
			}
			args[0] = elem[:idx]
			elem = elem[idx:]

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case '/': // Prefix: "/"

				if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'G': // Prefix: "GetC"

					if l := len("GetC"); len(elem) >= l && elem[0:l] == "GetC" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'h': // Prefix: "hats/"

						if l := len("hats/"); len(elem) >= l && elem[0:l] == "hats/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "apiTokenInstance"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[1] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleWaInstanceIdInstanceGetChatsApiTokenInstanceGetRequest([2]string{
									args[0],
									args[1],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "GET")
							}

							return
						}

					case 'o': // Prefix: "ontactInfo/"

						if l := len("ontactInfo/"); len(elem) >= l && elem[0:l] == "ontactInfo/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "apiTokenInstance"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[1] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "POST":
								s.handleWaInstanceIdInstanceGetContactInfoApiTokenInstancePostRequest([2]string{
									args[0],
									args[1],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "POST")
							}

							return
						}

					}

				case 'a': // Prefix: "addGroupParticipant/"

					if l := len("addGroupParticipant/"); len(elem) >= l && elem[0:l] == "addGroupParticipant/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "apiTokenInstance"
					// Leaf parameter, slashes are prohibited
					idx := strings.IndexByte(elem, '/')
					if idx >= 0 {
						break
					}
					args[1] = elem
					elem = ""

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "POST":
							s.handleWaInstanceIdInstanceAddGroupParticipantApiTokenInstancePostRequest([2]string{
								args[0],
								args[1],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "POST")
						}

						return
					}

				case 'c': // Prefix: "c"

					if l := len("c"); len(elem) >= l && elem[0:l] == "c" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'h': // Prefix: "heckAccount/"

						if l := len("heckAccount/"); len(elem) >= l && elem[0:l] == "heckAccount/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "apiTokenInstance"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[1] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "POST":
								s.handleWaInstanceIdInstanceCheckAccountApiTokenInstancePostRequest([2]string{
									args[0],
									args[1],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "POST")
							}

							return
						}

					case 'l': // Prefix: "lear"

						if l := len("lear"); len(elem) >= l && elem[0:l] == "lear" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'M': // Prefix: "MessagesQueue/"

							if l := len("MessagesQueue/"); len(elem) >= l && elem[0:l] == "MessagesQueue/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "apiTokenInstance"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[1] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleWaInstanceIdInstanceClearMessagesQueueApiTokenInstanceGetRequest([2]string{
										args[0],
										args[1],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "GET")
								}

								return
							}

						case 'W': // Prefix: "WebhooksQueue/"

							if l := len("WebhooksQueue/"); len(elem) >= l && elem[0:l] == "WebhooksQueue/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "apiTokenInstance"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[1] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "DELETE":
									s.handleWaInstanceIdInstanceClearWebhooksQueueApiTokenInstanceDeleteRequest([2]string{
										args[0],
										args[1],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "DELETE")
								}

								return
							}

						}

					case 'r': // Prefix: "reateGroup/"

						if l := len("reateGroup/"); len(elem) >= l && elem[0:l] == "reateGroup/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "apiTokenInstance"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[1] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "POST":
								s.handleWaInstanceIdInstanceCreateGroupApiTokenInstancePostRequest([2]string{
									args[0],
									args[1],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "POST")
							}

							return
						}

					}

				case 'd': // Prefix: "d"

					if l := len("d"); len(elem) >= l && elem[0:l] == "d" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'e': // Prefix: "elete"

						if l := len("elete"); len(elem) >= l && elem[0:l] == "elete" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'M': // Prefix: "Message/"

							if l := len("Message/"); len(elem) >= l && elem[0:l] == "Message/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "apiTokenInstance"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[1] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleWaInstanceIdInstanceDeleteMessageApiTokenInstancePostRequest([2]string{
										args[0],
										args[1],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "POST")
								}

								return
							}

						case 'N': // Prefix: "Notification/"

							if l := len("Notification/"); len(elem) >= l && elem[0:l] == "Notification/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "apiTokenInstance"
							// Match until "/"
							idx := strings.IndexByte(elem, '/')
							if idx < 0 {
								idx = len(elem)
							}
							args[1] = elem[:idx]
							elem = elem[idx:]

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "receiptId"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[2] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "DELETE":
										s.handleWaInstanceIdInstanceDeleteNotificationApiTokenInstanceReceiptIdDeleteRequest([3]string{
											args[0],
											args[1],
											args[2],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, "DELETE")
									}

									return
								}

							}

						}

					case 'o': // Prefix: "ownloadFile/"

						if l := len("ownloadFile/"); len(elem) >= l && elem[0:l] == "ownloadFile/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "apiTokenInstance"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[1] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "POST":
								s.handleWaInstanceIdInstanceDownloadFileApiTokenInstancePostRequest([2]string{
									args[0],
									args[1],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "POST")
							}

							return
						}

					}

				case 'e': // Prefix: "editMessage/"

					if l := len("editMessage/"); len(elem) >= l && elem[0:l] == "editMessage/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "apiTokenInstance"
					// Leaf parameter, slashes are prohibited
					idx := strings.IndexByte(elem, '/')
					if idx >= 0 {
						break
					}
					args[1] = elem
					elem = ""

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "POST":
							s.handleWaInstanceIdInstanceEditMessageApiTokenInstancePostRequest([2]string{
								args[0],
								args[1],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "POST")
						}

						return
					}

				case 'g': // Prefix: "get"

					if l := len("get"); len(elem) >= l && elem[0:l] == "get" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'A': // Prefix: "A"

						if l := len("A"); len(elem) >= l && elem[0:l] == "A" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'c': // Prefix: "ccountSettings/"

							if l := len("ccountSettings/"); len(elem) >= l && elem[0:l] == "ccountSettings/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "apiTokenInstance"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[1] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleWaInstanceIdInstanceGetAccountSettingsApiTokenInstanceGetRequest([2]string{
										args[0],
										args[1],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "GET")
								}

								return
							}

						case 'v': // Prefix: "vatar/"

							if l := len("vatar/"); len(elem) >= l && elem[0:l] == "vatar/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "apiTokenInstance"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[1] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleWaInstanceIdInstanceGetAvatarApiTokenInstancePostRequest([2]string{
										args[0],
										args[1],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "POST")
								}

								return
							}

						}

					case 'C': // Prefix: "C"

						if l := len("C"); len(elem) >= l && elem[0:l] == "C" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'h': // Prefix: "hatHistory/"

							if l := len("hatHistory/"); len(elem) >= l && elem[0:l] == "hatHistory/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "apiTokenInstance"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[1] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleWaInstanceIdInstanceGetChatHistoryApiTokenInstancePostRequest([2]string{
										args[0],
										args[1],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "POST")
								}

								return
							}

						case 'o': // Prefix: "ontacts/"

							if l := len("ontacts/"); len(elem) >= l && elem[0:l] == "ontacts/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "apiTokenInstance"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[1] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleWaInstanceIdInstanceGetContactsApiTokenInstanceGetRequest([2]string{
										args[0],
										args[1],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "GET")
								}

								return
							}

						}

					case 'G': // Prefix: "GroupData/"

						if l := len("GroupData/"); len(elem) >= l && elem[0:l] == "GroupData/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "apiTokenInstance"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[1] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "POST":
								s.handleWaInstanceIdInstanceGetGroupDataApiTokenInstancePostRequest([2]string{
									args[0],
									args[1],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "POST")
							}

							return
						}

					case 'M': // Prefix: "Message"

						if l := len("Message"); len(elem) >= l && elem[0:l] == "Message" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "apiTokenInstance"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[1] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleWaInstanceIdInstanceGetMessageApiTokenInstancePostRequest([2]string{
										args[0],
										args[1],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "POST")
								}

								return
							}

						case 's': // Prefix: "sCount/"

							if l := len("sCount/"); len(elem) >= l && elem[0:l] == "sCount/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "apiTokenInstance"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[1] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleWaInstanceIdInstanceGetMessagesCountApiTokenInstanceGetRequest([2]string{
										args[0],
										args[1],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "GET")
								}

								return
							}

						}

					case 'S': // Prefix: "S"

						if l := len("S"); len(elem) >= l && elem[0:l] == "S" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'e': // Prefix: "ettings/"

							if l := len("ettings/"); len(elem) >= l && elem[0:l] == "ettings/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "apiTokenInstance"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[1] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleWaInstanceIdInstanceGetSettingsApiTokenInstanceGetRequest([2]string{
										args[0],
										args[1],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "GET")
								}

								return
							}

						case 't': // Prefix: "tateInstance/"

							if l := len("tateInstance/"); len(elem) >= l && elem[0:l] == "tateInstance/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "apiTokenInstance"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[1] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleWaInstanceIdInstanceGetStateInstanceApiTokenInstanceGetRequest([2]string{
										args[0],
										args[1],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "GET")
								}

								return
							}

						}

					case 'W': // Prefix: "WebhooksCount/"

						if l := len("WebhooksCount/"); len(elem) >= l && elem[0:l] == "WebhooksCount/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "apiTokenInstance"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[1] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleWaInstanceIdInstanceGetWebhooksCountApiTokenInstanceGetRequest([2]string{
									args[0],
									args[1],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "GET")
							}

							return
						}

					}

				case 'l': // Prefix: "l"

					if l := len("l"); len(elem) >= l && elem[0:l] == "l" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'a': // Prefix: "ast"

						if l := len("ast"); len(elem) >= l && elem[0:l] == "ast" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'I': // Prefix: "IncomingMessages/"

							if l := len("IncomingMessages/"); len(elem) >= l && elem[0:l] == "IncomingMessages/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "apiTokenInstance"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[1] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleWaInstanceIdInstanceLastIncomingMessagesApiTokenInstanceGetRequest([2]string{
										args[0],
										args[1],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "GET")
								}

								return
							}

						case 'O': // Prefix: "OutgoingMessages/"

							if l := len("OutgoingMessages/"); len(elem) >= l && elem[0:l] == "OutgoingMessages/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "apiTokenInstance"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[1] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleWaInstanceIdInstanceLastOutgoingMessagesApiTokenInstanceGetRequest([2]string{
										args[0],
										args[1],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "GET")
								}

								return
							}

						}

					case 'e': // Prefix: "eaveGroup/"

						if l := len("eaveGroup/"); len(elem) >= l && elem[0:l] == "eaveGroup/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "apiTokenInstance"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[1] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "POST":
								s.handleWaInstanceIdInstanceLeaveGroupApiTokenInstancePostRequest([2]string{
									args[0],
									args[1],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "POST")
							}

							return
						}

					case 'o': // Prefix: "ogout/"

						if l := len("ogout/"); len(elem) >= l && elem[0:l] == "ogout/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "apiTokenInstance"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[1] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleWaInstanceIdInstanceLogoutApiTokenInstanceGetRequest([2]string{
									args[0],
									args[1],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "GET")
							}

							return
						}

					}

				case 'q': // Prefix: "qr/"

					if l := len("qr/"); len(elem) >= l && elem[0:l] == "qr/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "apiTokenInstance"
					// Leaf parameter, slashes are prohibited
					idx := strings.IndexByte(elem, '/')
					if idx >= 0 {
						break
					}
					args[1] = elem
					elem = ""

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handleWaInstanceIdInstanceQrApiTokenInstanceGetRequest([2]string{
								args[0],
								args[1],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "GET")
						}

						return
					}

				case 'r': // Prefix: "re"

					if l := len("re"); len(elem) >= l && elem[0:l] == "re" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'a': // Prefix: "adChat/"

						if l := len("adChat/"); len(elem) >= l && elem[0:l] == "adChat/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "apiTokenInstance"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[1] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "POST":
								s.handleWaInstanceIdInstanceReadChatApiTokenInstancePostRequest([2]string{
									args[0],
									args[1],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "POST")
							}

							return
						}

					case 'b': // Prefix: "boot/"

						if l := len("boot/"); len(elem) >= l && elem[0:l] == "boot/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "apiTokenInstance"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[1] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleWaInstanceIdInstanceRebootApiTokenInstanceGetRequest([2]string{
									args[0],
									args[1],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "GET")
							}

							return
						}

					case 'c': // Prefix: "ceiveNotification/"

						if l := len("ceiveNotification/"); len(elem) >= l && elem[0:l] == "ceiveNotification/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "apiTokenInstance"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[1] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleWaInstanceIdInstanceReceiveNotificationApiTokenInstanceGetRequest([2]string{
									args[0],
									args[1],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "GET")
							}

							return
						}

					case 'm': // Prefix: "move"

						if l := len("move"); len(elem) >= l && elem[0:l] == "move" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'A': // Prefix: "Admin/"

							if l := len("Admin/"); len(elem) >= l && elem[0:l] == "Admin/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "apiTokenInstance"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[1] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleWaInstanceIdInstanceRemoveAdminApiTokenInstancePostRequest([2]string{
										args[0],
										args[1],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "POST")
								}

								return
							}

						case 'G': // Prefix: "GroupParticipant/"

							if l := len("GroupParticipant/"); len(elem) >= l && elem[0:l] == "GroupParticipant/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "apiTokenInstance"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[1] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleWaInstanceIdInstanceRemoveGroupParticipantApiTokenInstancePostRequest([2]string{
										args[0],
										args[1],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "POST")
								}

								return
							}

						}

					}

				case 's': // Prefix: "s"

					if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'e': // Prefix: "e"

						if l := len("e"); len(elem) >= l && elem[0:l] == "e" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'n': // Prefix: "nd"

							if l := len("nd"); len(elem) >= l && elem[0:l] == "nd" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'C': // Prefix: "Contact/"

								if l := len("Contact/"); len(elem) >= l && elem[0:l] == "Contact/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "apiTokenInstance"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[1] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "POST":
										s.handleWaInstanceIdInstanceSendContactApiTokenInstancePostRequest([2]string{
											args[0],
											args[1],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, "POST")
									}

									return
								}

							case 'F': // Prefix: "FileByU"

								if l := len("FileByU"); len(elem) >= l && elem[0:l] == "FileByU" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 'p': // Prefix: "pload/"

									if l := len("pload/"); len(elem) >= l && elem[0:l] == "pload/" {
										elem = elem[l:]
									} else {
										break
									}

									// Param: "apiTokenInstance"
									// Leaf parameter, slashes are prohibited
									idx := strings.IndexByte(elem, '/')
									if idx >= 0 {
										break
									}
									args[1] = elem
									elem = ""

									if len(elem) == 0 {
										// Leaf node.
										switch r.Method {
										case "POST":
											s.handleWaInstanceIdInstanceSendFileByUploadApiTokenInstancePostRequest([2]string{
												args[0],
												args[1],
											}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, "POST")
										}

										return
									}

								case 'r': // Prefix: "rl/"

									if l := len("rl/"); len(elem) >= l && elem[0:l] == "rl/" {
										elem = elem[l:]
									} else {
										break
									}

									// Param: "apiTokenInstance"
									// Leaf parameter, slashes are prohibited
									idx := strings.IndexByte(elem, '/')
									if idx >= 0 {
										break
									}
									args[1] = elem
									elem = ""

									if len(elem) == 0 {
										// Leaf node.
										switch r.Method {
										case "POST":
											s.handleWaInstanceIdInstanceSendFileByUrlApiTokenInstancePostRequest([2]string{
												args[0],
												args[1],
											}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, "POST")
										}

										return
									}

								}

							case 'L': // Prefix: "Location/"

								if l := len("Location/"); len(elem) >= l && elem[0:l] == "Location/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "apiTokenInstance"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[1] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "POST":
										s.handleWaInstanceIdInstanceSendLocationApiTokenInstancePostRequest([2]string{
											args[0],
											args[1],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, "POST")
									}

									return
								}

							case 'M': // Prefix: "Message/"

								if l := len("Message/"); len(elem) >= l && elem[0:l] == "Message/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "apiTokenInstance"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[1] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "POST":
										s.handleWaInstanceIdInstanceSendMessageApiTokenInstancePostRequest([2]string{
											args[0],
											args[1],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, "POST")
									}

									return
								}

							case 'T': // Prefix: "Typing/"

								if l := len("Typing/"); len(elem) >= l && elem[0:l] == "Typing/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "apiTokenInstance"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[1] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "POST":
										s.handleWaInstanceIdInstanceSendTypingApiTokenInstancePostRequest([2]string{
											args[0],
											args[1],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, "POST")
									}

									return
								}

							}

						case 't': // Prefix: "t"

							if l := len("t"); len(elem) >= l && elem[0:l] == "t" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'G': // Prefix: "Group"

								if l := len("Group"); len(elem) >= l && elem[0:l] == "Group" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 'A': // Prefix: "Admin/"

									if l := len("Admin/"); len(elem) >= l && elem[0:l] == "Admin/" {
										elem = elem[l:]
									} else {
										break
									}

									// Param: "apiTokenInstance"
									// Leaf parameter, slashes are prohibited
									idx := strings.IndexByte(elem, '/')
									if idx >= 0 {
										break
									}
									args[1] = elem
									elem = ""

									if len(elem) == 0 {
										// Leaf node.
										switch r.Method {
										case "POST":
											s.handleWaInstanceIdInstanceSetGroupAdminApiTokenInstancePostRequest([2]string{
												args[0],
												args[1],
											}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, "POST")
										}

										return
									}

								case 'P': // Prefix: "Picture/"

									if l := len("Picture/"); len(elem) >= l && elem[0:l] == "Picture/" {
										elem = elem[l:]
									} else {
										break
									}

									// Param: "apiTokenInstance"
									// Leaf parameter, slashes are prohibited
									idx := strings.IndexByte(elem, '/')
									if idx >= 0 {
										break
									}
									args[1] = elem
									elem = ""

									if len(elem) == 0 {
										// Leaf node.
										switch r.Method {
										case "POST":
											s.handleWaInstanceIdInstanceSetGroupPictureApiTokenInstancePostRequest([2]string{
												args[0],
												args[1],
											}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, "POST")
										}

										return
									}

								}

							case 'P': // Prefix: "ProfilePicture/"

								if l := len("ProfilePicture/"); len(elem) >= l && elem[0:l] == "ProfilePicture/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "apiTokenInstance"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[1] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "POST":
										s.handleWaInstanceIdInstanceSetProfilePictureApiTokenInstancePostRequest([2]string{
											args[0],
											args[1],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, "POST")
									}

									return
								}

							case 'S': // Prefix: "Settings/"

								if l := len("Settings/"); len(elem) >= l && elem[0:l] == "Settings/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "apiTokenInstance"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[1] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "POST":
										s.handleWaInstanceIdInstanceSetSettingsApiTokenInstancePostRequest([2]string{
											args[0],
											args[1],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, "POST")
									}

									return
								}

							}

						}

					case 'h': // Prefix: "howMessagesQueue/"

						if l := len("howMessagesQueue/"); len(elem) >= l && elem[0:l] == "howMessagesQueue/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "apiTokenInstance"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[1] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleWaInstanceIdInstanceShowMessagesQueueApiTokenInstanceGetRequest([2]string{
									args[0],
									args[1],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "GET")
							}

							return
						}

					}

				case 'u': // Prefix: "up"

					if l := len("up"); len(elem) >= l && elem[0:l] == "up" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'd': // Prefix: "dateGroup"

						if l := len("dateGroup"); len(elem) >= l && elem[0:l] == "dateGroup" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'N': // Prefix: "Name/"

							if l := len("Name/"); len(elem) >= l && elem[0:l] == "Name/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "apiTokenInstance"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[1] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleWaInstanceIdInstanceUpdateGroupNameApiTokenInstancePostRequest([2]string{
										args[0],
										args[1],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "POST")
								}

								return
							}

						case 'S': // Prefix: "Settings/"

							if l := len("Settings/"); len(elem) >= l && elem[0:l] == "Settings/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "apiTokenInstance"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[1] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleWaInstanceIdInstanceUpdateGroupSettingsApiTokenInstancePostRequest([2]string{
										args[0],
										args[1],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "POST")
								}

								return
							}

						}

					case 'l': // Prefix: "loadFile/"

						if l := len("loadFile/"); len(elem) >= l && elem[0:l] == "loadFile/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "apiTokenInstance"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[1] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "POST":
								s.handleWaInstanceIdInstanceUploadFileApiTokenInstancePostRequest([2]string{
									args[0],
									args[1],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "POST")
							}

							return
						}

					}

				}

			}

		}
	}
	s.notFound(w, r)
}

// Route is route object.
type Route struct {
	name           string
	summary        string
	operationID    string
	operationGroup string
	pathPattern    string
	count          int
	args           [3]string
}

// Name returns ogen operation name.
//
// It is guaranteed to be unique and not empty.
func (r Route) Name() string {
	return r.name
}

// Summary returns OpenAPI summary.
func (r Route) Summary() string {
	return r.summary
}

// OperationID returns OpenAPI operationId.
func (r Route) OperationID() string {
	return r.operationID
}

// OperationGroup returns the x-ogen-operation-group value.
func (r Route) OperationGroup() string {
	return r.operationGroup
}

// PathPattern returns OpenAPI path.
func (r Route) PathPattern() string {
	return r.pathPattern
}

// Args returns parsed arguments.
func (r Route) Args() []string {
	return r.args[:r.count]
}

// FindRoute finds Route for given method and path.
//
// Note: this method does not unescape path or handle reserved characters in path properly. Use FindPath instead.
func (s *Server) FindRoute(method, path string) (Route, bool) {
	return s.FindPath(method, &url.URL{Path: path})
}

// FindPath finds Route for given method and URL.
func (s *Server) FindPath(method string, u *url.URL) (r Route, _ bool) {
	var (
		elem = u.Path
		args = r.args
	)
	if rawPath := u.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
		}
		defer func() {
			for i, arg := range r.args[:r.count] {
				if unescaped, err := url.PathUnescape(arg); err == nil {
					r.args[i] = unescaped
				}
			}
		}()
	}

	elem, ok := s.cutPrefix(elem)
	if !ok {
		return r, false
	}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/waInstance"

			if l := len("/waInstance"); len(elem) >= l && elem[0:l] == "/waInstance" {
				elem = elem[l:]
			} else {
				break
			}

			// Param: "idInstance"
			// Match until "/"
			idx := strings.IndexByte(elem, '/')
			if idx < 0 {
				idx = len(elem)
			}
			args[0] = elem[:idx]
			elem = elem[idx:]

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case '/': // Prefix: "/"

				if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'G': // Prefix: "GetC"

					if l := len("GetC"); len(elem) >= l && elem[0:l] == "GetC" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'h': // Prefix: "hats/"

						if l := len("hats/"); len(elem) >= l && elem[0:l] == "hats/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "apiTokenInstance"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[1] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = WaInstanceIdInstanceGetChatsApiTokenInstanceGetOperation
								r.summary = "Получить список чатов"
								r.operationID = ""
								r.operationGroup = ""
								r.pathPattern = "/waInstance{idInstance}/GetChats/{apiTokenInstance}"
								r.args = args
								r.count = 2
								return r, true
							default:
								return
							}
						}

					case 'o': // Prefix: "ontactInfo/"

						if l := len("ontactInfo/"); len(elem) >= l && elem[0:l] == "ontactInfo/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "apiTokenInstance"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[1] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "POST":
								r.name = WaInstanceIdInstanceGetContactInfoApiTokenInstancePostOperation
								r.summary = "Получить инфо контакта"
								r.operationID = ""
								r.operationGroup = ""
								r.pathPattern = "/waInstance{idInstance}/GetContactInfo/{apiTokenInstance}"
								r.args = args
								r.count = 2
								return r, true
							default:
								return
							}
						}

					}

				case 'a': // Prefix: "addGroupParticipant/"

					if l := len("addGroupParticipant/"); len(elem) >= l && elem[0:l] == "addGroupParticipant/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "apiTokenInstance"
					// Leaf parameter, slashes are prohibited
					idx := strings.IndexByte(elem, '/')
					if idx >= 0 {
						break
					}
					args[1] = elem
					elem = ""

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "POST":
							r.name = WaInstanceIdInstanceAddGroupParticipantApiTokenInstancePostOperation
							r.summary = "Добавить участника в группу"
							r.operationID = ""
							r.operationGroup = ""
							r.pathPattern = "/waInstance{idInstance}/addGroupParticipant/{apiTokenInstance}"
							r.args = args
							r.count = 2
							return r, true
						default:
							return
						}
					}

				case 'c': // Prefix: "c"

					if l := len("c"); len(elem) >= l && elem[0:l] == "c" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'h': // Prefix: "heckAccount/"

						if l := len("heckAccount/"); len(elem) >= l && elem[0:l] == "heckAccount/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "apiTokenInstance"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[1] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "POST":
								r.name = WaInstanceIdInstanceCheckAccountApiTokenInstancePostOperation
								r.summary = "Проверить наличие МАХ"
								r.operationID = ""
								r.operationGroup = ""
								r.pathPattern = "/waInstance{idInstance}/checkAccount/{apiTokenInstance}"
								r.args = args
								r.count = 2
								return r, true
							default:
								return
							}
						}

					case 'l': // Prefix: "lear"

						if l := len("lear"); len(elem) >= l && elem[0:l] == "lear" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'M': // Prefix: "MessagesQueue/"

							if l := len("MessagesQueue/"); len(elem) >= l && elem[0:l] == "MessagesQueue/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "apiTokenInstance"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[1] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = WaInstanceIdInstanceClearMessagesQueueApiTokenInstanceGetOperation
									r.summary = "Очистить очередь сообщений к отправке"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/waInstance{idInstance}/clearMessagesQueue/{apiTokenInstance}"
									r.args = args
									r.count = 2
									return r, true
								default:
									return
								}
							}

						case 'W': // Prefix: "WebhooksQueue/"

							if l := len("WebhooksQueue/"); len(elem) >= l && elem[0:l] == "WebhooksQueue/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "apiTokenInstance"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[1] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "DELETE":
									r.name = WaInstanceIdInstanceClearWebhooksQueueApiTokenInstanceDeleteOperation
									r.summary = "Очистить очередь входящих уведомлений"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/waInstance{idInstance}/clearWebhooksQueue/{apiTokenInstance}"
									r.args = args
									r.count = 2
									return r, true
								default:
									return
								}
							}

						}

					case 'r': // Prefix: "reateGroup/"

						if l := len("reateGroup/"); len(elem) >= l && elem[0:l] == "reateGroup/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "apiTokenInstance"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[1] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "POST":
								r.name = WaInstanceIdInstanceCreateGroupApiTokenInstancePostOperation
								r.summary = "Создать группу"
								r.operationID = ""
								r.operationGroup = ""
								r.pathPattern = "/waInstance{idInstance}/createGroup/{apiTokenInstance}"
								r.args = args
								r.count = 2
								return r, true
							default:
								return
							}
						}

					}

				case 'd': // Prefix: "d"

					if l := len("d"); len(elem) >= l && elem[0:l] == "d" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'e': // Prefix: "elete"

						if l := len("elete"); len(elem) >= l && elem[0:l] == "elete" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'M': // Prefix: "Message/"

							if l := len("Message/"); len(elem) >= l && elem[0:l] == "Message/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "apiTokenInstance"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[1] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = WaInstanceIdInstanceDeleteMessageApiTokenInstancePostOperation
									r.summary = "Удалить сообщение"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/waInstance{idInstance}/deleteMessage/{apiTokenInstance}"
									r.args = args
									r.count = 2
									return r, true
								default:
									return
								}
							}

						case 'N': // Prefix: "Notification/"

							if l := len("Notification/"); len(elem) >= l && elem[0:l] == "Notification/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "apiTokenInstance"
							// Match until "/"
							idx := strings.IndexByte(elem, '/')
							if idx < 0 {
								idx = len(elem)
							}
							args[1] = elem[:idx]
							elem = elem[idx:]

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "receiptId"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[2] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "DELETE":
										r.name = WaInstanceIdInstanceDeleteNotificationApiTokenInstanceReceiptIdDeleteOperation
										r.summary = "Удалить уведомление"
										r.operationID = ""
										r.operationGroup = ""
										r.pathPattern = "/waInstance{idInstance}/deleteNotification/{apiTokenInstance}/{receiptId}"
										r.args = args
										r.count = 3
										return r, true
									default:
										return
									}
								}

							}

						}

					case 'o': // Prefix: "ownloadFile/"

						if l := len("ownloadFile/"); len(elem) >= l && elem[0:l] == "ownloadFile/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "apiTokenInstance"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[1] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "POST":
								r.name = WaInstanceIdInstanceDownloadFileApiTokenInstancePostOperation
								r.summary = "Скачать файл из входящего сообщения"
								r.operationID = ""
								r.operationGroup = ""
								r.pathPattern = "/waInstance{idInstance}/downloadFile/{apiTokenInstance}"
								r.args = args
								r.count = 2
								return r, true
							default:
								return
							}
						}

					}

				case 'e': // Prefix: "editMessage/"

					if l := len("editMessage/"); len(elem) >= l && elem[0:l] == "editMessage/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "apiTokenInstance"
					// Leaf parameter, slashes are prohibited
					idx := strings.IndexByte(elem, '/')
					if idx >= 0 {
						break
					}
					args[1] = elem
					elem = ""

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "POST":
							r.name = WaInstanceIdInstanceEditMessageApiTokenInstancePostOperation
							r.summary = "Редактировать сообщение"
							r.operationID = ""
							r.operationGroup = ""
							r.pathPattern = "/waInstance{idInstance}/editMessage/{apiTokenInstance}"
							r.args = args
							r.count = 2
							return r, true
						default:
							return
						}
					}

				case 'g': // Prefix: "get"

					if l := len("get"); len(elem) >= l && elem[0:l] == "get" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'A': // Prefix: "A"

						if l := len("A"); len(elem) >= l && elem[0:l] == "A" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'c': // Prefix: "ccountSettings/"

							if l := len("ccountSettings/"); len(elem) >= l && elem[0:l] == "ccountSettings/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "apiTokenInstance"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[1] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = WaInstanceIdInstanceGetAccountSettingsApiTokenInstanceGetOperation
									r.summary = "Получить информацию об аккаунте"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/waInstance{idInstance}/getAccountSettings/{apiTokenInstance}"
									r.args = args
									r.count = 2
									return r, true
								default:
									return
								}
							}

						case 'v': // Prefix: "vatar/"

							if l := len("vatar/"); len(elem) >= l && elem[0:l] == "vatar/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "apiTokenInstance"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[1] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = WaInstanceIdInstanceGetAvatarApiTokenInstancePostOperation
									r.summary = "Получить аватар контакта"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/waInstance{idInstance}/getAvatar/{apiTokenInstance}"
									r.args = args
									r.count = 2
									return r, true
								default:
									return
								}
							}

						}

					case 'C': // Prefix: "C"

						if l := len("C"); len(elem) >= l && elem[0:l] == "C" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'h': // Prefix: "hatHistory/"

							if l := len("hatHistory/"); len(elem) >= l && elem[0:l] == "hatHistory/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "apiTokenInstance"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[1] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = WaInstanceIdInstanceGetChatHistoryApiTokenInstancePostOperation
									r.summary = "Получить историю сообщений чата"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/waInstance{idInstance}/getChatHistory/{apiTokenInstance}"
									r.args = args
									r.count = 2
									return r, true
								default:
									return
								}
							}

						case 'o': // Prefix: "ontacts/"

							if l := len("ontacts/"); len(elem) >= l && elem[0:l] == "ontacts/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "apiTokenInstance"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[1] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = WaInstanceIdInstanceGetContactsApiTokenInstanceGetOperation
									r.summary = "Получить контакты"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/waInstance{idInstance}/getContacts/{apiTokenInstance}"
									r.args = args
									r.count = 2
									return r, true
								default:
									return
								}
							}

						}

					case 'G': // Prefix: "GroupData/"

						if l := len("GroupData/"); len(elem) >= l && elem[0:l] == "GroupData/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "apiTokenInstance"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[1] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "POST":
								r.name = WaInstanceIdInstanceGetGroupDataApiTokenInstancePostOperation
								r.summary = "Получить информацию о группе"
								r.operationID = ""
								r.operationGroup = ""
								r.pathPattern = "/waInstance{idInstance}/getGroupData/{apiTokenInstance}"
								r.args = args
								r.count = 2
								return r, true
							default:
								return
							}
						}

					case 'M': // Prefix: "Message"

						if l := len("Message"); len(elem) >= l && elem[0:l] == "Message" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "apiTokenInstance"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[1] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = WaInstanceIdInstanceGetMessageApiTokenInstancePostOperation
									r.summary = "Получить сообщение чата"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/waInstance{idInstance}/getMessage/{apiTokenInstance}"
									r.args = args
									r.count = 2
									return r, true
								default:
									return
								}
							}

						case 's': // Prefix: "sCount/"

							if l := len("sCount/"); len(elem) >= l && elem[0:l] == "sCount/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "apiTokenInstance"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[1] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = WaInstanceIdInstanceGetMessagesCountApiTokenInstanceGetOperation
									r.summary = "Получить количество сообщений к отправке"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/waInstance{idInstance}/getMessagesCount/{apiTokenInstance}"
									r.args = args
									r.count = 2
									return r, true
								default:
									return
								}
							}

						}

					case 'S': // Prefix: "S"

						if l := len("S"); len(elem) >= l && elem[0:l] == "S" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'e': // Prefix: "ettings/"

							if l := len("ettings/"); len(elem) >= l && elem[0:l] == "ettings/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "apiTokenInstance"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[1] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = WaInstanceIdInstanceGetSettingsApiTokenInstanceGetOperation
									r.summary = "Получить настройки инстанса"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/waInstance{idInstance}/getSettings/{apiTokenInstance}"
									r.args = args
									r.count = 2
									return r, true
								default:
									return
								}
							}

						case 't': // Prefix: "tateInstance/"

							if l := len("tateInstance/"); len(elem) >= l && elem[0:l] == "tateInstance/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "apiTokenInstance"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[1] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = WaInstanceIdInstanceGetStateInstanceApiTokenInstanceGetOperation
									r.summary = "Получить состояние инстанса"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/waInstance{idInstance}/getStateInstance/{apiTokenInstance}"
									r.args = args
									r.count = 2
									return r, true
								default:
									return
								}
							}

						}

					case 'W': // Prefix: "WebhooksCount/"

						if l := len("WebhooksCount/"); len(elem) >= l && elem[0:l] == "WebhooksCount/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "apiTokenInstance"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[1] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = WaInstanceIdInstanceGetWebhooksCountApiTokenInstanceGetOperation
								r.summary = "Получить количество уведомлений во входящей очереди"
								r.operationID = ""
								r.operationGroup = ""
								r.pathPattern = "/waInstance{idInstance}/getWebhooksCount/{apiTokenInstance}"
								r.args = args
								r.count = 2
								return r, true
							default:
								return
							}
						}

					}

				case 'l': // Prefix: "l"

					if l := len("l"); len(elem) >= l && elem[0:l] == "l" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'a': // Prefix: "ast"

						if l := len("ast"); len(elem) >= l && elem[0:l] == "ast" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'I': // Prefix: "IncomingMessages/"

							if l := len("IncomingMessages/"); len(elem) >= l && elem[0:l] == "IncomingMessages/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "apiTokenInstance"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[1] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = WaInstanceIdInstanceLastIncomingMessagesApiTokenInstanceGetOperation
									r.summary = "Получить журнал входящих сообщений"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/waInstance{idInstance}/lastIncomingMessages/{apiTokenInstance}"
									r.args = args
									r.count = 2
									return r, true
								default:
									return
								}
							}

						case 'O': // Prefix: "OutgoingMessages/"

							if l := len("OutgoingMessages/"); len(elem) >= l && elem[0:l] == "OutgoingMessages/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "apiTokenInstance"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[1] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = WaInstanceIdInstanceLastOutgoingMessagesApiTokenInstanceGetOperation
									r.summary = "Получить журнал отправленных сообщений"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/waInstance{idInstance}/lastOutgoingMessages/{apiTokenInstance}"
									r.args = args
									r.count = 2
									return r, true
								default:
									return
								}
							}

						}

					case 'e': // Prefix: "eaveGroup/"

						if l := len("eaveGroup/"); len(elem) >= l && elem[0:l] == "eaveGroup/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "apiTokenInstance"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[1] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "POST":
								r.name = WaInstanceIdInstanceLeaveGroupApiTokenInstancePostOperation
								r.summary = "Выйти из группы"
								r.operationID = ""
								r.operationGroup = ""
								r.pathPattern = "/waInstance{idInstance}/leaveGroup/{apiTokenInstance}"
								r.args = args
								r.count = 2
								return r, true
							default:
								return
							}
						}

					case 'o': // Prefix: "ogout/"

						if l := len("ogout/"); len(elem) >= l && elem[0:l] == "ogout/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "apiTokenInstance"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[1] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = WaInstanceIdInstanceLogoutApiTokenInstanceGetOperation
								r.summary = "Разлогинить инстанс"
								r.operationID = ""
								r.operationGroup = ""
								r.pathPattern = "/waInstance{idInstance}/logout/{apiTokenInstance}"
								r.args = args
								r.count = 2
								return r, true
							default:
								return
							}
						}

					}

				case 'q': // Prefix: "qr/"

					if l := len("qr/"); len(elem) >= l && elem[0:l] == "qr/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "apiTokenInstance"
					// Leaf parameter, slashes are prohibited
					idx := strings.IndexByte(elem, '/')
					if idx >= 0 {
						break
					}
					args[1] = elem
					elem = ""

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = WaInstanceIdInstanceQrApiTokenInstanceGetOperation
							r.summary = "Получить QR-код"
							r.operationID = ""
							r.operationGroup = ""
							r.pathPattern = "/waInstance{idInstance}/qr/{apiTokenInstance}"
							r.args = args
							r.count = 2
							return r, true
						default:
							return
						}
					}

				case 'r': // Prefix: "re"

					if l := len("re"); len(elem) >= l && elem[0:l] == "re" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'a': // Prefix: "adChat/"

						if l := len("adChat/"); len(elem) >= l && elem[0:l] == "adChat/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "apiTokenInstance"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[1] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "POST":
								r.name = WaInstanceIdInstanceReadChatApiTokenInstancePostOperation
								r.summary = "Отметить сообщение в чате прочитанным"
								r.operationID = ""
								r.operationGroup = ""
								r.pathPattern = "/waInstance{idInstance}/readChat/{apiTokenInstance}"
								r.args = args
								r.count = 2
								return r, true
							default:
								return
							}
						}

					case 'b': // Prefix: "boot/"

						if l := len("boot/"); len(elem) >= l && elem[0:l] == "boot/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "apiTokenInstance"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[1] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = WaInstanceIdInstanceRebootApiTokenInstanceGetOperation
								r.summary = "Перезапустить инстанс"
								r.operationID = ""
								r.operationGroup = ""
								r.pathPattern = "/waInstance{idInstance}/reboot/{apiTokenInstance}"
								r.args = args
								r.count = 2
								return r, true
							default:
								return
							}
						}

					case 'c': // Prefix: "ceiveNotification/"

						if l := len("ceiveNotification/"); len(elem) >= l && elem[0:l] == "ceiveNotification/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "apiTokenInstance"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[1] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = WaInstanceIdInstanceReceiveNotificationApiTokenInstanceGetOperation
								r.summary = "Получить уведомление"
								r.operationID = ""
								r.operationGroup = ""
								r.pathPattern = "/waInstance{idInstance}/receiveNotification/{apiTokenInstance}"
								r.args = args
								r.count = 2
								return r, true
							default:
								return
							}
						}

					case 'm': // Prefix: "move"

						if l := len("move"); len(elem) >= l && elem[0:l] == "move" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'A': // Prefix: "Admin/"

							if l := len("Admin/"); len(elem) >= l && elem[0:l] == "Admin/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "apiTokenInstance"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[1] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = WaInstanceIdInstanceRemoveAdminApiTokenInstancePostOperation
									r.summary = "Отозвать права администратора группы"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/waInstance{idInstance}/removeAdmin/{apiTokenInstance}"
									r.args = args
									r.count = 2
									return r, true
								default:
									return
								}
							}

						case 'G': // Prefix: "GroupParticipant/"

							if l := len("GroupParticipant/"); len(elem) >= l && elem[0:l] == "GroupParticipant/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "apiTokenInstance"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[1] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = WaInstanceIdInstanceRemoveGroupParticipantApiTokenInstancePostOperation
									r.summary = "Удалить участника из группы"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/waInstance{idInstance}/removeGroupParticipant/{apiTokenInstance}"
									r.args = args
									r.count = 2
									return r, true
								default:
									return
								}
							}

						}

					}

				case 's': // Prefix: "s"

					if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'e': // Prefix: "e"

						if l := len("e"); len(elem) >= l && elem[0:l] == "e" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'n': // Prefix: "nd"

							if l := len("nd"); len(elem) >= l && elem[0:l] == "nd" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'C': // Prefix: "Contact/"

								if l := len("Contact/"); len(elem) >= l && elem[0:l] == "Contact/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "apiTokenInstance"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[1] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "POST":
										r.name = WaInstanceIdInstanceSendContactApiTokenInstancePostOperation
										r.summary = "Отправить контакт"
										r.operationID = ""
										r.operationGroup = ""
										r.pathPattern = "/waInstance{idInstance}/sendContact/{apiTokenInstance}"
										r.args = args
										r.count = 2
										return r, true
									default:
										return
									}
								}

							case 'F': // Prefix: "FileByU"

								if l := len("FileByU"); len(elem) >= l && elem[0:l] == "FileByU" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 'p': // Prefix: "pload/"

									if l := len("pload/"); len(elem) >= l && elem[0:l] == "pload/" {
										elem = elem[l:]
									} else {
										break
									}

									// Param: "apiTokenInstance"
									// Leaf parameter, slashes are prohibited
									idx := strings.IndexByte(elem, '/')
									if idx >= 0 {
										break
									}
									args[1] = elem
									elem = ""

									if len(elem) == 0 {
										// Leaf node.
										switch method {
										case "POST":
											r.name = WaInstanceIdInstanceSendFileByUploadApiTokenInstancePostOperation
											r.summary = "Отправить видео, аудио, изображение, документ"
											r.operationID = ""
											r.operationGroup = ""
											r.pathPattern = "/waInstance{idInstance}/sendFileByUpload/{apiTokenInstance}"
											r.args = args
											r.count = 2
											return r, true
										default:
											return
										}
									}

								case 'r': // Prefix: "rl/"

									if l := len("rl/"); len(elem) >= l && elem[0:l] == "rl/" {
										elem = elem[l:]
									} else {
										break
									}

									// Param: "apiTokenInstance"
									// Leaf parameter, slashes are prohibited
									idx := strings.IndexByte(elem, '/')
									if idx >= 0 {
										break
									}
									args[1] = elem
									elem = ""

									if len(elem) == 0 {
										// Leaf node.
										switch method {
										case "POST":
											r.name = WaInstanceIdInstanceSendFileByUrlApiTokenInstancePostOperation
											r.summary = "Отправить видео, аудио, изображение, документ по URL"
											r.operationID = ""
											r.operationGroup = ""
											r.pathPattern = "/waInstance{idInstance}/sendFileByUrl/{apiTokenInstance}"
											r.args = args
											r.count = 2
											return r, true
										default:
											return
										}
									}

								}

							case 'L': // Prefix: "Location/"

								if l := len("Location/"); len(elem) >= l && elem[0:l] == "Location/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "apiTokenInstance"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[1] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "POST":
										r.name = WaInstanceIdInstanceSendLocationApiTokenInstancePostOperation
										r.summary = "Отправить геолокацию"
										r.operationID = ""
										r.operationGroup = ""
										r.pathPattern = "/waInstance{idInstance}/sendLocation/{apiTokenInstance}"
										r.args = args
										r.count = 2
										return r, true
									default:
										return
									}
								}

							case 'M': // Prefix: "Message/"

								if l := len("Message/"); len(elem) >= l && elem[0:l] == "Message/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "apiTokenInstance"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[1] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "POST":
										r.name = WaInstanceIdInstanceSendMessageApiTokenInstancePostOperation
										r.summary = "Отправить текст"
										r.operationID = ""
										r.operationGroup = ""
										r.pathPattern = "/waInstance{idInstance}/sendMessage/{apiTokenInstance}"
										r.args = args
										r.count = 2
										return r, true
									default:
										return
									}
								}

							case 'T': // Prefix: "Typing/"

								if l := len("Typing/"); len(elem) >= l && elem[0:l] == "Typing/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "apiTokenInstance"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[1] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "POST":
										r.name = WaInstanceIdInstanceSendTypingApiTokenInstancePostOperation
										r.summary = "Отправить уведомление набора"
										r.operationID = ""
										r.operationGroup = ""
										r.pathPattern = "/waInstance{idInstance}/sendTyping/{apiTokenInstance}"
										r.args = args
										r.count = 2
										return r, true
									default:
										return
									}
								}

							}

						case 't': // Prefix: "t"

							if l := len("t"); len(elem) >= l && elem[0:l] == "t" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'G': // Prefix: "Group"

								if l := len("Group"); len(elem) >= l && elem[0:l] == "Group" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 'A': // Prefix: "Admin/"

									if l := len("Admin/"); len(elem) >= l && elem[0:l] == "Admin/" {
										elem = elem[l:]
									} else {
										break
									}

									// Param: "apiTokenInstance"
									// Leaf parameter, slashes are prohibited
									idx := strings.IndexByte(elem, '/')
									if idx >= 0 {
										break
									}
									args[1] = elem
									elem = ""

									if len(elem) == 0 {
										// Leaf node.
										switch method {
										case "POST":
											r.name = WaInstanceIdInstanceSetGroupAdminApiTokenInstancePostOperation
											r.summary = "Назначить права администратора группы"
											r.operationID = ""
											r.operationGroup = ""
											r.pathPattern = "/waInstance{idInstance}/setGroupAdmin/{apiTokenInstance}"
											r.args = args
											r.count = 2
											return r, true
										default:
											return
										}
									}

								case 'P': // Prefix: "Picture/"

									if l := len("Picture/"); len(elem) >= l && elem[0:l] == "Picture/" {
										elem = elem[l:]
									} else {
										break
									}

									// Param: "apiTokenInstance"
									// Leaf parameter, slashes are prohibited
									idx := strings.IndexByte(elem, '/')
									if idx >= 0 {
										break
									}
									args[1] = elem
									elem = ""

									if len(elem) == 0 {
										// Leaf node.
										switch method {
										case "POST":
											r.name = WaInstanceIdInstanceSetGroupPictureApiTokenInstancePostOperation
											r.summary = "Установить фото группы"
											r.operationID = ""
											r.operationGroup = ""
											r.pathPattern = "/waInstance{idInstance}/setGroupPicture/{apiTokenInstance}"
											r.args = args
											r.count = 2
											return r, true
										default:
											return
										}
									}

								}

							case 'P': // Prefix: "ProfilePicture/"

								if l := len("ProfilePicture/"); len(elem) >= l && elem[0:l] == "ProfilePicture/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "apiTokenInstance"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[1] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "POST":
										r.name = WaInstanceIdInstanceSetProfilePictureApiTokenInstancePostOperation
										r.summary = "Установить фото профиля"
										r.operationID = ""
										r.operationGroup = ""
										r.pathPattern = "/waInstance{idInstance}/setProfilePicture/{apiTokenInstance}"
										r.args = args
										r.count = 2
										return r, true
									default:
										return
									}
								}

							case 'S': // Prefix: "Settings/"

								if l := len("Settings/"); len(elem) >= l && elem[0:l] == "Settings/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "apiTokenInstance"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[1] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "POST":
										r.name = WaInstanceIdInstanceSetSettingsApiTokenInstancePostOperation
										r.summary = "Установить настройки инстанса"
										r.operationID = ""
										r.operationGroup = ""
										r.pathPattern = "/waInstance{idInstance}/setSettings/{apiTokenInstance}"
										r.args = args
										r.count = 2
										return r, true
									default:
										return
									}
								}

							}

						}

					case 'h': // Prefix: "howMessagesQueue/"

						if l := len("howMessagesQueue/"); len(elem) >= l && elem[0:l] == "howMessagesQueue/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "apiTokenInstance"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[1] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = WaInstanceIdInstanceShowMessagesQueueApiTokenInstanceGetOperation
								r.summary = "Получить очередь сообщений к отправке"
								r.operationID = ""
								r.operationGroup = ""
								r.pathPattern = "/waInstance{idInstance}/showMessagesQueue/{apiTokenInstance}"
								r.args = args
								r.count = 2
								return r, true
							default:
								return
							}
						}

					}

				case 'u': // Prefix: "up"

					if l := len("up"); len(elem) >= l && elem[0:l] == "up" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'd': // Prefix: "dateGroup"

						if l := len("dateGroup"); len(elem) >= l && elem[0:l] == "dateGroup" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'N': // Prefix: "Name/"

							if l := len("Name/"); len(elem) >= l && elem[0:l] == "Name/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "apiTokenInstance"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[1] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = WaInstanceIdInstanceUpdateGroupNameApiTokenInstancePostOperation
									r.summary = "Изменить имя группы"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/waInstance{idInstance}/updateGroupName/{apiTokenInstance}"
									r.args = args
									r.count = 2
									return r, true
								default:
									return
								}
							}

						case 'S': // Prefix: "Settings/"

							if l := len("Settings/"); len(elem) >= l && elem[0:l] == "Settings/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "apiTokenInstance"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[1] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = WaInstanceIdInstanceUpdateGroupSettingsApiTokenInstancePostOperation
									r.summary = "Обновить настройки группы"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/waInstance{idInstance}/updateGroupSettings/{apiTokenInstance}"
									r.args = args
									r.count = 2
									return r, true
								default:
									return
								}
							}

						}

					case 'l': // Prefix: "loadFile/"

						if l := len("loadFile/"); len(elem) >= l && elem[0:l] == "loadFile/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "apiTokenInstance"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[1] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "POST":
								r.name = WaInstanceIdInstanceUploadFileApiTokenInstancePostOperation
								r.summary = "Выгрузить файл"
								r.operationID = ""
								r.operationGroup = ""
								r.pathPattern = "/waInstance{idInstance}/uploadFile/{apiTokenInstance}"
								r.args = args
								r.count = 2
								return r, true
							default:
								return
							}
						}

					}

				}

			}

		}
	}
	return r, false
}
