// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// WaInstanceIdInstanceAddGroupParticipantApiTokenInstancePost implements POST /waInstance{idInstance}/addGroupParticipant/{apiTokenInstance} operation.
	//
	// Документация [AddGroupParticipant](https://green-api.
	// com/v3/docs/api/groups/AddGroupParticipant/).
	//
	// POST /waInstance{idInstance}/addGroupParticipant/{apiTokenInstance}
	WaInstanceIdInstanceAddGroupParticipantApiTokenInstancePost(ctx context.Context, req OptWaInstanceIdInstanceAddGroupParticipantApiTokenInstancePostReq, params WaInstanceIdInstanceAddGroupParticipantApiTokenInstancePostParams) (WaInstanceIdInstanceAddGroupParticipantApiTokenInstancePostRes, error)
	// WaInstanceIdInstanceCheckAccountApiTokenInstancePost implements POST /waInstance{idInstance}/checkAccount/{apiTokenInstance} operation.
	//
	// Документация [CheckAccount](https://green-api.com/v3/docs/api/service/CheckAccount/).
	//
	// POST /waInstance{idInstance}/checkAccount/{apiTokenInstance}
	WaInstanceIdInstanceCheckAccountApiTokenInstancePost(ctx context.Context, req OptWaInstanceIdInstanceCheckAccountApiTokenInstancePostReq, params WaInstanceIdInstanceCheckAccountApiTokenInstancePostParams) (WaInstanceIdInstanceCheckAccountApiTokenInstancePostRes, error)
	// WaInstanceIdInstanceClearMessagesQueueApiTokenInstanceGet implements GET /waInstance{idInstance}/clearMessagesQueue/{apiTokenInstance} operation.
	//
	// Документация [ClearMessagesQueue](https://green-api.
	// com/v3/docs/api/queues/ClearMessagesQueue/).
	//
	// GET /waInstance{idInstance}/clearMessagesQueue/{apiTokenInstance}
	WaInstanceIdInstanceClearMessagesQueueApiTokenInstanceGet(ctx context.Context, params WaInstanceIdInstanceClearMessagesQueueApiTokenInstanceGetParams) (*WaInstanceIdInstanceClearMessagesQueueApiTokenInstanceGetOKHeaders, error)
	// WaInstanceIdInstanceClearWebhooksQueueApiTokenInstanceDelete implements DELETE /waInstance{idInstance}/clearWebhooksQueue/{apiTokenInstance} operation.
	//
	// Документация [ClearWebhooksQueue](https://green-api.
	// com/v3/docs/api/queues/ClearWebhooksQueue/).
	//
	// DELETE /waInstance{idInstance}/clearWebhooksQueue/{apiTokenInstance}
	WaInstanceIdInstanceClearWebhooksQueueApiTokenInstanceDelete(ctx context.Context, params WaInstanceIdInstanceClearWebhooksQueueApiTokenInstanceDeleteParams) (*WaInstanceIdInstanceClearWebhooksQueueApiTokenInstanceDeleteOKHeaders, error)
	// WaInstanceIdInstanceCreateGroupApiTokenInstancePost implements POST /waInstance{idInstance}/createGroup/{apiTokenInstance} operation.
	//
	// Документация [CreateGroup](https://green-api.com/v3/docs/api/groups/CreateGroup/).
	//
	// POST /waInstance{idInstance}/createGroup/{apiTokenInstance}
	WaInstanceIdInstanceCreateGroupApiTokenInstancePost(ctx context.Context, req OptWaInstanceIdInstanceCreateGroupApiTokenInstancePostReq, params WaInstanceIdInstanceCreateGroupApiTokenInstancePostParams) (WaInstanceIdInstanceCreateGroupApiTokenInstancePostRes, error)
	// WaInstanceIdInstanceDeleteMessageApiTokenInstancePost implements POST /waInstance{idInstance}/deleteMessage/{apiTokenInstance} operation.
	//
	// Документация [DeleteMessage](https://green-api.com/v3/docs/api/service/DeleteMessage).
	//
	// POST /waInstance{idInstance}/deleteMessage/{apiTokenInstance}
	WaInstanceIdInstanceDeleteMessageApiTokenInstancePost(ctx context.Context, req *WaInstanceIdInstanceDeleteMessageApiTokenInstancePostReq, params WaInstanceIdInstanceDeleteMessageApiTokenInstancePostParams) (WaInstanceIdInstanceDeleteMessageApiTokenInstancePostRes, error)
	// WaInstanceIdInstanceDeleteNotificationApiTokenInstanceReceiptIdDelete implements DELETE /waInstance{idInstance}/deleteNotification/{apiTokenInstance}/{receiptId} operation.
	//
	// Документация [DeleteNotification](https://green-api.
	// com/v3/docs/api/receiving/technology-http-api/DeleteNotification/).
	//
	// DELETE /waInstance{idInstance}/deleteNotification/{apiTokenInstance}/{receiptId}
	WaInstanceIdInstanceDeleteNotificationApiTokenInstanceReceiptIdDelete(ctx context.Context, params WaInstanceIdInstanceDeleteNotificationApiTokenInstanceReceiptIdDeleteParams) (*WaInstanceIdInstanceDeleteNotificationApiTokenInstanceReceiptIdDeleteOK, error)
	// WaInstanceIdInstanceDownloadFileApiTokenInstancePost implements POST /waInstance{idInstance}/downloadFile/{apiTokenInstance} operation.
	//
	// Документация [DownloadFile](https://green-api.
	// com/v3/docs/api/receiving/files/DownloadFile/).
	//
	// POST /waInstance{idInstance}/downloadFile/{apiTokenInstance}
	WaInstanceIdInstanceDownloadFileApiTokenInstancePost(ctx context.Context, req OptWaInstanceIdInstanceDownloadFileApiTokenInstancePostReq, params WaInstanceIdInstanceDownloadFileApiTokenInstancePostParams) (WaInstanceIdInstanceDownloadFileApiTokenInstancePostRes, error)
	// WaInstanceIdInstanceEditMessageApiTokenInstancePost implements POST /waInstance{idInstance}/editMessage/{apiTokenInstance} operation.
	//
	// Документация [EditMessage](https://green-api.com/v3/docs/api/service/EditMessage).
	//
	// POST /waInstance{idInstance}/editMessage/{apiTokenInstance}
	WaInstanceIdInstanceEditMessageApiTokenInstancePost(ctx context.Context, req OptWaInstanceIdInstanceEditMessageApiTokenInstancePostReq, params WaInstanceIdInstanceEditMessageApiTokenInstancePostParams) (WaInstanceIdInstanceEditMessageApiTokenInstancePostRes, error)
	// WaInstanceIdInstanceGetAccountSettingsApiTokenInstanceGet implements GET /waInstance{idInstance}/getAccountSettings/{apiTokenInstance} operation.
	//
	// Документация [GetAccountSettings](https://green-api.
	// com/v3/docs/api/account/GetAccountSettings/).
	//
	// GET /waInstance{idInstance}/getAccountSettings/{apiTokenInstance}
	WaInstanceIdInstanceGetAccountSettingsApiTokenInstanceGet(ctx context.Context, req *WaInstanceIdInstanceGetAccountSettingsApiTokenInstanceGetReq, params WaInstanceIdInstanceGetAccountSettingsApiTokenInstanceGetParams) (*WaInstanceIdInstanceGetAccountSettingsApiTokenInstanceGetOKHeaders, error)
	// WaInstanceIdInstanceGetAvatarApiTokenInstancePost implements POST /waInstance{idInstance}/getAvatar/{apiTokenInstance} operation.
	//
	// Документация [GetAvatar](https://green-api.com/v3/docs/api/service/GetAvatar).
	//
	// POST /waInstance{idInstance}/getAvatar/{apiTokenInstance}
	WaInstanceIdInstanceGetAvatarApiTokenInstancePost(ctx context.Context, req OptWaInstanceIdInstanceGetAvatarApiTokenInstancePostReq, params WaInstanceIdInstanceGetAvatarApiTokenInstancePostParams) (WaInstanceIdInstanceGetAvatarApiTokenInstancePostRes, error)
	// WaInstanceIdInstanceGetChatHistoryApiTokenInstancePost implements POST /waInstance{idInstance}/getChatHistory/{apiTokenInstance} operation.
	//
	// Документация [GetChatHistory](https://green-api.
	// com/v3/docs/api/journals/GetChatHistory/).
	//
	// POST /waInstance{idInstance}/getChatHistory/{apiTokenInstance}
	WaInstanceIdInstanceGetChatHistoryApiTokenInstancePost(ctx context.Context, req OptWaInstanceIdInstanceGetChatHistoryApiTokenInstancePostReq, params WaInstanceIdInstanceGetChatHistoryApiTokenInstancePostParams) (WaInstanceIdInstanceGetChatHistoryApiTokenInstancePostRes, error)
	// WaInstanceIdInstanceGetChatsApiTokenInstanceGet implements GET /waInstance{idInstance}/GetChats/{apiTokenInstance} operation.
	//
	// Документация [GetChats](https://green-api.com/v3/docs/api/service/GetChats/).
	//
	// GET /waInstance{idInstance}/GetChats/{apiTokenInstance}
	WaInstanceIdInstanceGetChatsApiTokenInstanceGet(ctx context.Context, params WaInstanceIdInstanceGetChatsApiTokenInstanceGetParams) (*WaInstanceIdInstanceGetChatsApiTokenInstanceGetOKHeaders, error)
	// WaInstanceIdInstanceGetContactInfoApiTokenInstancePost implements POST /waInstance{idInstance}/GetContactInfo/{apiTokenInstance} operation.
	//
	// Документация [GetContactInfo](https://green-api.
	// com/v3/docs/api/service/GetContactInfo/).
	//
	// POST /waInstance{idInstance}/GetContactInfo/{apiTokenInstance}
	WaInstanceIdInstanceGetContactInfoApiTokenInstancePost(ctx context.Context, req OptWaInstanceIdInstanceGetContactInfoApiTokenInstancePostReq, params WaInstanceIdInstanceGetContactInfoApiTokenInstancePostParams) (WaInstanceIdInstanceGetContactInfoApiTokenInstancePostRes, error)
	// WaInstanceIdInstanceGetContactsApiTokenInstanceGet implements GET /waInstance{idInstance}/getContacts/{apiTokenInstance} operation.
	//
	// Документация [GetContacts](https://green-api.com/v3/docs/api/service/GetContacts/).
	//
	// GET /waInstance{idInstance}/getContacts/{apiTokenInstance}
	WaInstanceIdInstanceGetContactsApiTokenInstanceGet(ctx context.Context, params WaInstanceIdInstanceGetContactsApiTokenInstanceGetParams) (*WaInstanceIdInstanceGetContactsApiTokenInstanceGetOKHeaders, error)
	// WaInstanceIdInstanceGetGroupDataApiTokenInstancePost implements POST /waInstance{idInstance}/getGroupData/{apiTokenInstance} operation.
	//
	// Документация [GetGroupData](https://green-api.com/v3/docs/api/groups/GetGroupData/).
	//
	// POST /waInstance{idInstance}/getGroupData/{apiTokenInstance}
	WaInstanceIdInstanceGetGroupDataApiTokenInstancePost(ctx context.Context, req OptWaInstanceIdInstanceGetGroupDataApiTokenInstancePostReq, params WaInstanceIdInstanceGetGroupDataApiTokenInstancePostParams) (WaInstanceIdInstanceGetGroupDataApiTokenInstancePostRes, error)
	// WaInstanceIdInstanceGetMessageApiTokenInstancePost implements POST /waInstance{idInstance}/getMessage/{apiTokenInstance} operation.
	//
	// Документация [GetMessage](https://green-api.com/v3/docs/api/journals/GetMessage/).
	//
	// POST /waInstance{idInstance}/getMessage/{apiTokenInstance}
	WaInstanceIdInstanceGetMessageApiTokenInstancePost(ctx context.Context, req OptWaInstanceIdInstanceGetMessageApiTokenInstancePostReq, params WaInstanceIdInstanceGetMessageApiTokenInstancePostParams) (WaInstanceIdInstanceGetMessageApiTokenInstancePostRes, error)
	// WaInstanceIdInstanceGetMessagesCountApiTokenInstanceGet implements GET /waInstance{idInstance}/getMessagesCount/{apiTokenInstance} operation.
	//
	// Документация [GetMessagesCount](https://green-api.
	// com/v3/docs/api/queues/GetMessagesCount).
	//
	// GET /waInstance{idInstance}/getMessagesCount/{apiTokenInstance}
	WaInstanceIdInstanceGetMessagesCountApiTokenInstanceGet(ctx context.Context, params WaInstanceIdInstanceGetMessagesCountApiTokenInstanceGetParams) (*WaInstanceIdInstanceGetMessagesCountApiTokenInstanceGetOKHeaders, error)
	// WaInstanceIdInstanceGetSettingsApiTokenInstanceGet implements GET /waInstance{idInstance}/getSettings/{apiTokenInstance} operation.
	//
	// Документация [GetSettings](https://green-api.com/v3/docs/api/account/GetSettings/).
	//
	// GET /waInstance{idInstance}/getSettings/{apiTokenInstance}
	WaInstanceIdInstanceGetSettingsApiTokenInstanceGet(ctx context.Context, params WaInstanceIdInstanceGetSettingsApiTokenInstanceGetParams) (*WaInstanceIdInstanceGetSettingsApiTokenInstanceGetOKHeaders, error)
	// WaInstanceIdInstanceGetStateInstanceApiTokenInstanceGet implements GET /waInstance{idInstance}/getStateInstance/{apiTokenInstance} operation.
	//
	// Документация [GetStateInstance](https://green-api.
	// com/v3/docs/api/account/GetStateInstance/).
	//
	// GET /waInstance{idInstance}/getStateInstance/{apiTokenInstance}
	WaInstanceIdInstanceGetStateInstanceApiTokenInstanceGet(ctx context.Context, params WaInstanceIdInstanceGetStateInstanceApiTokenInstanceGetParams) (*WaInstanceIdInstanceGetStateInstanceApiTokenInstanceGetOKHeaders, error)
	// WaInstanceIdInstanceGetWebhooksCountApiTokenInstanceGet implements GET /waInstance{idInstance}/getWebhooksCount/{apiTokenInstance} operation.
	//
	// Документация [GetWebhooksCount](https://green-api.
	// com/v3/docs/api/queues/GetWebhooksCount/).
	//
	// GET /waInstance{idInstance}/getWebhooksCount/{apiTokenInstance}
	WaInstanceIdInstanceGetWebhooksCountApiTokenInstanceGet(ctx context.Context, params WaInstanceIdInstanceGetWebhooksCountApiTokenInstanceGetParams) (*WaInstanceIdInstanceGetWebhooksCountApiTokenInstanceGetOKHeaders, error)
	// WaInstanceIdInstanceLastIncomingMessagesApiTokenInstanceGet implements GET /waInstance{idInstance}/lastIncomingMessages/{apiTokenInstance} operation.
	//
	// Документация [LastIncomingMessages](https://green-api.
	// com/v3/docs/api/journals/LastIncomingMessages/).
	//
	// GET /waInstance{idInstance}/lastIncomingMessages/{apiTokenInstance}
	WaInstanceIdInstanceLastIncomingMessagesApiTokenInstanceGet(ctx context.Context, params WaInstanceIdInstanceLastIncomingMessagesApiTokenInstanceGetParams) (*WaInstanceIdInstanceLastIncomingMessagesApiTokenInstanceGetOKHeaders, error)
	// WaInstanceIdInstanceLastOutgoingMessagesApiTokenInstanceGet implements GET /waInstance{idInstance}/lastOutgoingMessages/{apiTokenInstance} operation.
	//
	// Документация [LastOutgoingMessages](https://green-api.
	// com/v3/docs/api/journals/LastOutgoingMessages/).
	//
	// GET /waInstance{idInstance}/lastOutgoingMessages/{apiTokenInstance}
	WaInstanceIdInstanceLastOutgoingMessagesApiTokenInstanceGet(ctx context.Context, params WaInstanceIdInstanceLastOutgoingMessagesApiTokenInstanceGetParams) (*WaInstanceIdInstanceLastOutgoingMessagesApiTokenInstanceGetOKHeaders, error)
	// WaInstanceIdInstanceLeaveGroupApiTokenInstancePost implements POST /waInstance{idInstance}/leaveGroup/{apiTokenInstance} operation.
	//
	// Документация [LeaveGroup](https://green-api.com/v3/docs/api/groups/LeaveGroup/).
	//
	// POST /waInstance{idInstance}/leaveGroup/{apiTokenInstance}
	WaInstanceIdInstanceLeaveGroupApiTokenInstancePost(ctx context.Context, req OptWaInstanceIdInstanceLeaveGroupApiTokenInstancePostReq, params WaInstanceIdInstanceLeaveGroupApiTokenInstancePostParams) (WaInstanceIdInstanceLeaveGroupApiTokenInstancePostRes, error)
	// WaInstanceIdInstanceLogoutApiTokenInstanceGet implements GET /waInstance{idInstance}/logout/{apiTokenInstance} operation.
	//
	// Документация [Logout](https://green-api.com/v3/docs/api/account/Logout/).
	//
	// GET /waInstance{idInstance}/logout/{apiTokenInstance}
	WaInstanceIdInstanceLogoutApiTokenInstanceGet(ctx context.Context, params WaInstanceIdInstanceLogoutApiTokenInstanceGetParams) (*WaInstanceIdInstanceLogoutApiTokenInstanceGetOKHeaders, error)
	// WaInstanceIdInstanceQrApiTokenInstanceGet implements GET /waInstance{idInstance}/qr/{apiTokenInstance} operation.
	//
	// Документация [QR](https://green-api.com/v3/docs/api/account/QR/).
	//
	// GET /waInstance{idInstance}/qr/{apiTokenInstance}
	WaInstanceIdInstanceQrApiTokenInstanceGet(ctx context.Context, params WaInstanceIdInstanceQrApiTokenInstanceGetParams) (*WaInstanceIdInstanceQrApiTokenInstanceGetDefStatusCode, error)
	// WaInstanceIdInstanceReadChatApiTokenInstancePost implements POST /waInstance{idInstance}/readChat/{apiTokenInstance} operation.
	//
	// Документация [ReadChat](https://green-api.com/v3/docs/api/marks/ReadChat/).
	//
	// POST /waInstance{idInstance}/readChat/{apiTokenInstance}
	WaInstanceIdInstanceReadChatApiTokenInstancePost(ctx context.Context, req OptWaInstanceIdInstanceReadChatApiTokenInstancePostReq, params WaInstanceIdInstanceReadChatApiTokenInstancePostParams) (WaInstanceIdInstanceReadChatApiTokenInstancePostRes, error)
	// WaInstanceIdInstanceRebootApiTokenInstanceGet implements GET /waInstance{idInstance}/reboot/{apiTokenInstance} operation.
	//
	// Документация [Reboot](https://green-api.com/v3/docs/api/account/Reboot/).
	//
	// GET /waInstance{idInstance}/reboot/{apiTokenInstance}
	WaInstanceIdInstanceRebootApiTokenInstanceGet(ctx context.Context, params WaInstanceIdInstanceRebootApiTokenInstanceGetParams) (*WaInstanceIdInstanceRebootApiTokenInstanceGetOKHeaders, error)
	// WaInstanceIdInstanceReceiveNotificationApiTokenInstanceGet implements GET /waInstance{idInstance}/receiveNotification/{apiTokenInstance} operation.
	//
	// Документация [ReceiveNotification](https://green-api.
	// com/v3/docs/api/receiving/technology-http-api/ReceiveNotification/).
	//
	// GET /waInstance{idInstance}/receiveNotification/{apiTokenInstance}
	WaInstanceIdInstanceReceiveNotificationApiTokenInstanceGet(ctx context.Context, params WaInstanceIdInstanceReceiveNotificationApiTokenInstanceGetParams) (*WaInstanceIdInstanceReceiveNotificationApiTokenInstanceGetOK, error)
	// WaInstanceIdInstanceRemoveAdminApiTokenInstancePost implements POST /waInstance{idInstance}/removeAdmin/{apiTokenInstance} operation.
	//
	// Документация [RemoveAdmin](https://green-api.com/v3/docs/api/groups/RemoveAdmin/).
	//
	// POST /waInstance{idInstance}/removeAdmin/{apiTokenInstance}
	WaInstanceIdInstanceRemoveAdminApiTokenInstancePost(ctx context.Context, req OptWaInstanceIdInstanceRemoveAdminApiTokenInstancePostReq, params WaInstanceIdInstanceRemoveAdminApiTokenInstancePostParams) (WaInstanceIdInstanceRemoveAdminApiTokenInstancePostRes, error)
	// WaInstanceIdInstanceRemoveGroupParticipantApiTokenInstancePost implements POST /waInstance{idInstance}/removeGroupParticipant/{apiTokenInstance} operation.
	//
	// Документация [RemoveGroupParticipant](https://green-api.
	// com/v3/docs/api/groups/RemoveGroupParticipant/).
	//
	// POST /waInstance{idInstance}/removeGroupParticipant/{apiTokenInstance}
	WaInstanceIdInstanceRemoveGroupParticipantApiTokenInstancePost(ctx context.Context, req OptWaInstanceIdInstanceRemoveGroupParticipantApiTokenInstancePostReq, params WaInstanceIdInstanceRemoveGroupParticipantApiTokenInstancePostParams) (WaInstanceIdInstanceRemoveGroupParticipantApiTokenInstancePostRes, error)
	// WaInstanceIdInstanceSendContactApiTokenInstancePost implements POST /waInstance{idInstance}/sendContact/{apiTokenInstance} operation.
	//
	// Документация [SendContact](https://green-api.com/v3/docs/api/sending/SendContact/).
	//
	// POST /waInstance{idInstance}/sendContact/{apiTokenInstance}
	WaInstanceIdInstanceSendContactApiTokenInstancePost(ctx context.Context, req OptWaInstanceIdInstanceSendContactApiTokenInstancePostReq, params WaInstanceIdInstanceSendContactApiTokenInstancePostParams) (WaInstanceIdInstanceSendContactApiTokenInstancePostRes, error)
	// WaInstanceIdInstanceSendFileByUploadApiTokenInstancePost implements POST /waInstance{idInstance}/sendFileByUpload/{apiTokenInstance} operation.
	//
	// Документация [SendFileByUpload](https://green-api.
	// com/v3/docs/api/sending/SendFileByUpload).
	//
	// POST /waInstance{idInstance}/sendFileByUpload/{apiTokenInstance}
	WaInstanceIdInstanceSendFileByUploadApiTokenInstancePost(ctx context.Context, params WaInstanceIdInstanceSendFileByUploadApiTokenInstancePostParams) (WaInstanceIdInstanceSendFileByUploadApiTokenInstancePostRes, error)
	// WaInstanceIdInstanceSendFileByUrlApiTokenInstancePost implements POST /waInstance{idInstance}/sendFileByUrl/{apiTokenInstance} operation.
	//
	// Документация [SendFileByUrl](https://green-api.com/v3/docs/api/sending/SendFileByUrl).
	//
	// POST /waInstance{idInstance}/sendFileByUrl/{apiTokenInstance}
	WaInstanceIdInstanceSendFileByUrlApiTokenInstancePost(ctx context.Context, req OptWaInstanceIdInstanceSendFileByUrlApiTokenInstancePostReq, params WaInstanceIdInstanceSendFileByUrlApiTokenInstancePostParams) (WaInstanceIdInstanceSendFileByUrlApiTokenInstancePostRes, error)
	// WaInstanceIdInstanceSendLocationApiTokenInstancePost implements POST /waInstance{idInstance}/sendLocation/{apiTokenInstance} operation.
	//
	// Документация [SendLocation](https://green-api.com/v3/docs/api/sending/SendLocation/).
	//
	// POST /waInstance{idInstance}/sendLocation/{apiTokenInstance}
	WaInstanceIdInstanceSendLocationApiTokenInstancePost(ctx context.Context, req OptWaInstanceIdInstanceSendLocationApiTokenInstancePostReq, params WaInstanceIdInstanceSendLocationApiTokenInstancePostParams) (WaInstanceIdInstanceSendLocationApiTokenInstancePostRes, error)
	// WaInstanceIdInstanceSendMessageApiTokenInstancePost implements POST /waInstance{idInstance}/sendMessage/{apiTokenInstance} operation.
	//
	// Документация [SendMessage](https://green-api.com/v3/docs/api/sending/SendMessage/).
	//
	// POST /waInstance{idInstance}/sendMessage/{apiTokenInstance}
	WaInstanceIdInstanceSendMessageApiTokenInstancePost(ctx context.Context, req OptWaInstanceIdInstanceSendMessageApiTokenInstancePostReq, params WaInstanceIdInstanceSendMessageApiTokenInstancePostParams) (WaInstanceIdInstanceSendMessageApiTokenInstancePostRes, error)
	// WaInstanceIdInstanceSendTypingApiTokenInstancePost implements POST /waInstance{idInstance}/sendTyping/{apiTokenInstance} operation.
	//
	// Документация [SendTyping](https://green-api.com/v3/docs/api/service/SendTyping/).
	//
	// POST /waInstance{idInstance}/sendTyping/{apiTokenInstance}
	WaInstanceIdInstanceSendTypingApiTokenInstancePost(ctx context.Context, req *WaInstanceIdInstanceSendTypingApiTokenInstancePostReq, params WaInstanceIdInstanceSendTypingApiTokenInstancePostParams) (WaInstanceIdInstanceSendTypingApiTokenInstancePostRes, error)
	// WaInstanceIdInstanceSetGroupAdminApiTokenInstancePost implements POST /waInstance{idInstance}/setGroupAdmin/{apiTokenInstance} operation.
	//
	// Документация [SetGroupAdmin](https://green-api.com/v3/docs/api/groups/SetGroupAdmin/).
	//
	// POST /waInstance{idInstance}/setGroupAdmin/{apiTokenInstance}
	WaInstanceIdInstanceSetGroupAdminApiTokenInstancePost(ctx context.Context, req OptWaInstanceIdInstanceSetGroupAdminApiTokenInstancePostReq, params WaInstanceIdInstanceSetGroupAdminApiTokenInstancePostParams) (WaInstanceIdInstanceSetGroupAdminApiTokenInstancePostRes, error)
	// WaInstanceIdInstanceSetGroupPictureApiTokenInstancePost implements POST /waInstance{idInstance}/setGroupPicture/{apiTokenInstance} operation.
	//
	// Документация [SetGroupPicture](https://green-api.
	// com/v3/docs/api/groups/SetGroupPicture/).
	//
	// POST /waInstance{idInstance}/setGroupPicture/{apiTokenInstance}
	WaInstanceIdInstanceSetGroupPictureApiTokenInstancePost(ctx context.Context, params WaInstanceIdInstanceSetGroupPictureApiTokenInstancePostParams) (WaInstanceIdInstanceSetGroupPictureApiTokenInstancePostRes, error)
	// WaInstanceIdInstanceSetProfilePictureApiTokenInstancePost implements POST /waInstance{idInstance}/setProfilePicture/{apiTokenInstance} operation.
	//
	// Документация [SetProfilePicture](https://green-api.
	// com/v3/docs/api/account/SetProfilePicture/).
	//
	// POST /waInstance{idInstance}/setProfilePicture/{apiTokenInstance}
	WaInstanceIdInstanceSetProfilePictureApiTokenInstancePost(ctx context.Context, params WaInstanceIdInstanceSetProfilePictureApiTokenInstancePostParams) (WaInstanceIdInstanceSetProfilePictureApiTokenInstancePostRes, error)
	// WaInstanceIdInstanceSetSettingsApiTokenInstancePost implements POST /waInstance{idInstance}/setSettings/{apiTokenInstance} operation.
	//
	// Документация [SetSettings](https://green-api.com/v3/docs/api/account/SetSettings/).
	//
	// POST /waInstance{idInstance}/setSettings/{apiTokenInstance}
	WaInstanceIdInstanceSetSettingsApiTokenInstancePost(ctx context.Context, req OptWaInstanceIdInstanceSetSettingsApiTokenInstancePostReq, params WaInstanceIdInstanceSetSettingsApiTokenInstancePostParams) (*WaInstanceIdInstanceSetSettingsApiTokenInstancePostOKHeaders, error)
	// WaInstanceIdInstanceShowMessagesQueueApiTokenInstanceGet implements GET /waInstance{idInstance}/showMessagesQueue/{apiTokenInstance} operation.
	//
	// Документация [ShowMessagesQueue](https://green-api.
	// com/v3/docs/api/queues/ShowMessagesQueue/).
	//
	// GET /waInstance{idInstance}/showMessagesQueue/{apiTokenInstance}
	WaInstanceIdInstanceShowMessagesQueueApiTokenInstanceGet(ctx context.Context, params WaInstanceIdInstanceShowMessagesQueueApiTokenInstanceGetParams) (*WaInstanceIdInstanceShowMessagesQueueApiTokenInstanceGetOKHeaders, error)
	// WaInstanceIdInstanceUpdateGroupNameApiTokenInstancePost implements POST /waInstance{idInstance}/updateGroupName/{apiTokenInstance} operation.
	//
	// Документация [UpdateGroupName](https://green-api.
	// com/v3/docs/api/groups/UpdateGroupName/).
	//
	// POST /waInstance{idInstance}/updateGroupName/{apiTokenInstance}
	WaInstanceIdInstanceUpdateGroupNameApiTokenInstancePost(ctx context.Context, req OptWaInstanceIdInstanceUpdateGroupNameApiTokenInstancePostReq, params WaInstanceIdInstanceUpdateGroupNameApiTokenInstancePostParams) (WaInstanceIdInstanceUpdateGroupNameApiTokenInstancePostRes, error)
	// WaInstanceIdInstanceUpdateGroupSettingsApiTokenInstancePost implements POST /waInstance{idInstance}/updateGroupSettings/{apiTokenInstance} operation.
	//
	// Документация [UpdateGroupSettings](https://green-api.
	// com/v3/docs/api/groups/UpdateGroupSettings/).
	//
	// POST /waInstance{idInstance}/updateGroupSettings/{apiTokenInstance}
	WaInstanceIdInstanceUpdateGroupSettingsApiTokenInstancePost(ctx context.Context, req OptWaInstanceIdInstanceUpdateGroupSettingsApiTokenInstancePostReq, params WaInstanceIdInstanceUpdateGroupSettingsApiTokenInstancePostParams) (WaInstanceIdInstanceUpdateGroupSettingsApiTokenInstancePostRes, error)
	// WaInstanceIdInstanceUploadFileApiTokenInstancePost implements POST /waInstance{idInstance}/uploadFile/{apiTokenInstance} operation.
	//
	// Документация [UploadFile](https://green-api.com/v3/docs/api/sending/UploadFile).
	//
	// POST /waInstance{idInstance}/uploadFile/{apiTokenInstance}
	WaInstanceIdInstanceUploadFileApiTokenInstancePost(ctx context.Context, params WaInstanceIdInstanceUploadFileApiTokenInstancePostParams) (WaInstanceIdInstanceUploadFileApiTokenInstancePostRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
