// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
	"net/url"
	"strings"
	"time"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	ht "github.com/ogen-go/ogen/http"
	"github.com/ogen-go/ogen/otelogen"
	"github.com/ogen-go/ogen/uri"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/metric"
	semconv "go.opentelemetry.io/otel/semconv/v1.37.0"
	"go.opentelemetry.io/otel/trace"
)

func trimTrailingSlashes(u *url.URL) {
	u.Path = strings.TrimRight(u.Path, "/")
	u.RawPath = strings.TrimRight(u.RawPath, "/")
}

// Invoker invokes operations described by OpenAPI v3 specification.
type Invoker interface {
	// CreateInstance invokes createInstance operation.
	//
	// Создание инстанса.
	//
	// POST /partner/createInstance/{partnerToken}
	CreateInstance(ctx context.Context, request *CreateInstanceRequest, params CreateInstanceParams) (CreateInstanceResponse, error)
	// DeleteInstanceAccount invokes deleteInstanceAccount operation.
	//
	// Метод предназначен для удаления инстанса на аккаунте
	// партнера.
	// В случае ошибок (Unauthorized, Not found) API возвращает HTTP 200
	// с телом ошибки (code, description).
	//
	// POST /partner/deleteInstanceAccount/{partnerToken}
	DeleteInstanceAccount(ctx context.Context, request *DeleteInstanceRequest, params DeleteInstanceAccountParams) (DeleteInstanceAccountResponse, error)
	// GetInstances invokes getInstances operation.
	//
	// Метод предназначен для получения всех инстансов на
	// аккаунте партнера.
	// В случае ошибки авторизации API может вернуть HTTP 200
	// с телом ошибки (code, description).
	//
	// GET /partner/getInstances/{partnerToken}
	GetInstances(ctx context.Context, params GetInstancesParams) (GetInstancesRes, error)
}

// Client implements OAS client.
type Client struct {
	serverURL *url.URL
	baseClient
}

var _ Handler = struct {
	*Client
}{}

// NewClient initializes new Client defined by OAS.
func NewClient(serverURL string, opts ...ClientOption) (*Client, error) {
	u, err := url.Parse(serverURL)
	if err != nil {
		return nil, err
	}
	trimTrailingSlashes(u)

	c, err := newClientConfig(opts...).baseClient()
	if err != nil {
		return nil, err
	}
	return &Client{
		serverURL:  u,
		baseClient: c,
	}, nil
}

type serverURLKey struct{}

// WithServerURL sets context key to override server URL.
func WithServerURL(ctx context.Context, u *url.URL) context.Context {
	return context.WithValue(ctx, serverURLKey{}, u)
}

func (c *Client) requestURL(ctx context.Context) *url.URL {
	u, ok := ctx.Value(serverURLKey{}).(*url.URL)
	if !ok {
		return c.serverURL
	}
	return u
}

// CreateInstance invokes createInstance operation.
//
// Создание инстанса.
//
// POST /partner/createInstance/{partnerToken}
func (c *Client) CreateInstance(ctx context.Context, request *CreateInstanceRequest, params CreateInstanceParams) (CreateInstanceResponse, error) {
	res, err := c.sendCreateInstance(ctx, request, params)
	return res, err
}

func (c *Client) sendCreateInstance(ctx context.Context, request *CreateInstanceRequest, params CreateInstanceParams) (res CreateInstanceResponse, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("createInstance"),
		semconv.HTTPRequestMethodKey.String("POST"),
		semconv.URLTemplateKey.String("/partner/createInstance/{partnerToken}"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, CreateInstanceOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/partner/createInstance/"
	{
		// Encode "partnerToken" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "partnerToken",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.PartnerToken))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeCreateInstanceRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	stage = "DecodeResponse"
	result, err := decodeCreateInstanceResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// DeleteInstanceAccount invokes deleteInstanceAccount operation.
//
// Метод предназначен для удаления инстанса на аккаунте
// партнера.
// В случае ошибок (Unauthorized, Not found) API возвращает HTTP 200
// с телом ошибки (code, description).
//
// POST /partner/deleteInstanceAccount/{partnerToken}
func (c *Client) DeleteInstanceAccount(ctx context.Context, request *DeleteInstanceRequest, params DeleteInstanceAccountParams) (DeleteInstanceAccountResponse, error) {
	res, err := c.sendDeleteInstanceAccount(ctx, request, params)
	return res, err
}

func (c *Client) sendDeleteInstanceAccount(ctx context.Context, request *DeleteInstanceRequest, params DeleteInstanceAccountParams) (res DeleteInstanceAccountResponse, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("deleteInstanceAccount"),
		semconv.HTTPRequestMethodKey.String("POST"),
		semconv.URLTemplateKey.String("/partner/deleteInstanceAccount/{partnerToken}"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, DeleteInstanceAccountOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/partner/deleteInstanceAccount/"
	{
		// Encode "partnerToken" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "partnerToken",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.PartnerToken))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeDeleteInstanceAccountRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	stage = "DecodeResponse"
	result, err := decodeDeleteInstanceAccountResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetInstances invokes getInstances operation.
//
// Метод предназначен для получения всех инстансов на
// аккаунте партнера.
// В случае ошибки авторизации API может вернуть HTTP 200
// с телом ошибки (code, description).
//
// GET /partner/getInstances/{partnerToken}
func (c *Client) GetInstances(ctx context.Context, params GetInstancesParams) (GetInstancesRes, error) {
	res, err := c.sendGetInstances(ctx, params)
	return res, err
}

func (c *Client) sendGetInstances(ctx context.Context, params GetInstancesParams) (res GetInstancesRes, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("getInstances"),
		semconv.HTTPRequestMethodKey.String("GET"),
		semconv.URLTemplateKey.String("/partner/getInstances/{partnerToken}"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, GetInstancesOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/partner/getInstances/"
	{
		// Encode "partnerToken" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "partnerToken",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.PartnerToken))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	stage = "DecodeResponse"
	result, err := decodeGetInstancesResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}
