// Code generated by ogen, DO NOT EDIT.

package api

import (
	"math/bits"
	"strconv"
	"time"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
	"github.com/ogen-go/ogen/json"
	"github.com/ogen-go/ogen/validate"
)

// Encode implements json.Marshaler.
func (s *CreateInstanceRequest) Encode(e *jx.Encoder) {
	e.ObjStart()
	s.encodeFields(e)
	e.ObjEnd()
}

// encodeFields encodes fields.
func (s *CreateInstanceRequest) encodeFields(e *jx.Encoder) {
	{
		if s.Name.Set {
			e.FieldStart("name")
			s.Name.Encode(e)
		}
	}
	{
		if s.WebhookUrl.Set {
			e.FieldStart("webhookUrl")
			s.WebhookUrl.Encode(e)
		}
	}
	{
		if s.WebhookUrlToken.Set {
			e.FieldStart("webhookUrlToken")
			s.WebhookUrlToken.Encode(e)
		}
	}
	{
		if s.DelaySendMessagesMilliseconds.Set {
			e.FieldStart("delaySendMessagesMilliseconds")
			s.DelaySendMessagesMilliseconds.Encode(e)
		}
	}
	{
		if s.MarkIncomingMessagesReaded.Set {
			e.FieldStart("markIncomingMessagesReaded")
			s.MarkIncomingMessagesReaded.Encode(e)
		}
	}
	{
		if s.MarkIncomingMessagesReadedOnReply.Set {
			e.FieldStart("markIncomingMessagesReadedOnReply")
			s.MarkIncomingMessagesReadedOnReply.Encode(e)
		}
	}
	{
		if s.OutgoingAPIMessageWebhook.Set {
			e.FieldStart("outgoingAPIMessageWebhook")
			s.OutgoingAPIMessageWebhook.Encode(e)
		}
	}
	{
		if s.OutgoingWebhook.Set {
			e.FieldStart("outgoingWebhook")
			s.OutgoingWebhook.Encode(e)
		}
	}
	{
		if s.OutgoingMessageWebhook.Set {
			e.FieldStart("outgoingMessageWebhook")
			s.OutgoingMessageWebhook.Encode(e)
		}
	}
	{
		if s.IncomingWebhook.Set {
			e.FieldStart("incomingWebhook")
			s.IncomingWebhook.Encode(e)
		}
	}
	{
		if s.StateWebhook.Set {
			e.FieldStart("stateWebhook")
			s.StateWebhook.Encode(e)
		}
	}
}

var jsonFieldsNameOfCreateInstanceRequest = [11]string{
	0:  "name",
	1:  "webhookUrl",
	2:  "webhookUrlToken",
	3:  "delaySendMessagesMilliseconds",
	4:  "markIncomingMessagesReaded",
	5:  "markIncomingMessagesReadedOnReply",
	6:  "outgoingAPIMessageWebhook",
	7:  "outgoingWebhook",
	8:  "outgoingMessageWebhook",
	9:  "incomingWebhook",
	10: "stateWebhook",
}

// Decode decodes CreateInstanceRequest from json.
func (s *CreateInstanceRequest) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode CreateInstanceRequest to nil")
	}

	if err := d.ObjBytes(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "name":
			if err := func() error {
				s.Name.Reset()
				if err := s.Name.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"name\"")
			}
		case "webhookUrl":
			if err := func() error {
				s.WebhookUrl.Reset()
				if err := s.WebhookUrl.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"webhookUrl\"")
			}
		case "webhookUrlToken":
			if err := func() error {
				s.WebhookUrlToken.Reset()
				if err := s.WebhookUrlToken.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"webhookUrlToken\"")
			}
		case "delaySendMessagesMilliseconds":
			if err := func() error {
				s.DelaySendMessagesMilliseconds.Reset()
				if err := s.DelaySendMessagesMilliseconds.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"delaySendMessagesMilliseconds\"")
			}
		case "markIncomingMessagesReaded":
			if err := func() error {
				s.MarkIncomingMessagesReaded.Reset()
				if err := s.MarkIncomingMessagesReaded.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"markIncomingMessagesReaded\"")
			}
		case "markIncomingMessagesReadedOnReply":
			if err := func() error {
				s.MarkIncomingMessagesReadedOnReply.Reset()
				if err := s.MarkIncomingMessagesReadedOnReply.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"markIncomingMessagesReadedOnReply\"")
			}
		case "outgoingAPIMessageWebhook":
			if err := func() error {
				s.OutgoingAPIMessageWebhook.Reset()
				if err := s.OutgoingAPIMessageWebhook.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"outgoingAPIMessageWebhook\"")
			}
		case "outgoingWebhook":
			if err := func() error {
				s.OutgoingWebhook.Reset()
				if err := s.OutgoingWebhook.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"outgoingWebhook\"")
			}
		case "outgoingMessageWebhook":
			if err := func() error {
				s.OutgoingMessageWebhook.Reset()
				if err := s.OutgoingMessageWebhook.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"outgoingMessageWebhook\"")
			}
		case "incomingWebhook":
			if err := func() error {
				s.IncomingWebhook.Reset()
				if err := s.IncomingWebhook.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"incomingWebhook\"")
			}
		case "stateWebhook":
			if err := func() error {
				s.StateWebhook.Reset()
				if err := s.StateWebhook.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"stateWebhook\"")
			}
		default:
			return d.Skip()
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode CreateInstanceRequest")
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *CreateInstanceRequest) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateInstanceRequest) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes CreateInstanceRequestIncomingWebhook as json.
func (s CreateInstanceRequestIncomingWebhook) Encode(e *jx.Encoder) {
	e.Str(string(s))
}

// Decode decodes CreateInstanceRequestIncomingWebhook from json.
func (s *CreateInstanceRequestIncomingWebhook) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode CreateInstanceRequestIncomingWebhook to nil")
	}
	v, err := d.StrBytes()
	if err != nil {
		return err
	}
	// Try to use constant string.
	switch CreateInstanceRequestIncomingWebhook(v) {
	case CreateInstanceRequestIncomingWebhookYes:
		*s = CreateInstanceRequestIncomingWebhookYes
	case CreateInstanceRequestIncomingWebhookNo:
		*s = CreateInstanceRequestIncomingWebhookNo
	default:
		*s = CreateInstanceRequestIncomingWebhook(v)
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s CreateInstanceRequestIncomingWebhook) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateInstanceRequestIncomingWebhook) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes CreateInstanceRequestMarkIncomingMessagesReaded as json.
func (s CreateInstanceRequestMarkIncomingMessagesReaded) Encode(e *jx.Encoder) {
	e.Str(string(s))
}

// Decode decodes CreateInstanceRequestMarkIncomingMessagesReaded from json.
func (s *CreateInstanceRequestMarkIncomingMessagesReaded) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode CreateInstanceRequestMarkIncomingMessagesReaded to nil")
	}
	v, err := d.StrBytes()
	if err != nil {
		return err
	}
	// Try to use constant string.
	switch CreateInstanceRequestMarkIncomingMessagesReaded(v) {
	case CreateInstanceRequestMarkIncomingMessagesReadedYes:
		*s = CreateInstanceRequestMarkIncomingMessagesReadedYes
	case CreateInstanceRequestMarkIncomingMessagesReadedNo:
		*s = CreateInstanceRequestMarkIncomingMessagesReadedNo
	default:
		*s = CreateInstanceRequestMarkIncomingMessagesReaded(v)
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s CreateInstanceRequestMarkIncomingMessagesReaded) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateInstanceRequestMarkIncomingMessagesReaded) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes CreateInstanceRequestMarkIncomingMessagesReadedOnReply as json.
func (s CreateInstanceRequestMarkIncomingMessagesReadedOnReply) Encode(e *jx.Encoder) {
	e.Str(string(s))
}

// Decode decodes CreateInstanceRequestMarkIncomingMessagesReadedOnReply from json.
func (s *CreateInstanceRequestMarkIncomingMessagesReadedOnReply) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode CreateInstanceRequestMarkIncomingMessagesReadedOnReply to nil")
	}
	v, err := d.StrBytes()
	if err != nil {
		return err
	}
	// Try to use constant string.
	switch CreateInstanceRequestMarkIncomingMessagesReadedOnReply(v) {
	case CreateInstanceRequestMarkIncomingMessagesReadedOnReplyYes:
		*s = CreateInstanceRequestMarkIncomingMessagesReadedOnReplyYes
	case CreateInstanceRequestMarkIncomingMessagesReadedOnReplyNo:
		*s = CreateInstanceRequestMarkIncomingMessagesReadedOnReplyNo
	default:
		*s = CreateInstanceRequestMarkIncomingMessagesReadedOnReply(v)
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s CreateInstanceRequestMarkIncomingMessagesReadedOnReply) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateInstanceRequestMarkIncomingMessagesReadedOnReply) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes CreateInstanceRequestOutgoingAPIMessageWebhook as json.
func (s CreateInstanceRequestOutgoingAPIMessageWebhook) Encode(e *jx.Encoder) {
	e.Str(string(s))
}

// Decode decodes CreateInstanceRequestOutgoingAPIMessageWebhook from json.
func (s *CreateInstanceRequestOutgoingAPIMessageWebhook) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode CreateInstanceRequestOutgoingAPIMessageWebhook to nil")
	}
	v, err := d.StrBytes()
	if err != nil {
		return err
	}
	// Try to use constant string.
	switch CreateInstanceRequestOutgoingAPIMessageWebhook(v) {
	case CreateInstanceRequestOutgoingAPIMessageWebhookYes:
		*s = CreateInstanceRequestOutgoingAPIMessageWebhookYes
	case CreateInstanceRequestOutgoingAPIMessageWebhookNo:
		*s = CreateInstanceRequestOutgoingAPIMessageWebhookNo
	default:
		*s = CreateInstanceRequestOutgoingAPIMessageWebhook(v)
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s CreateInstanceRequestOutgoingAPIMessageWebhook) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateInstanceRequestOutgoingAPIMessageWebhook) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes CreateInstanceRequestOutgoingMessageWebhook as json.
func (s CreateInstanceRequestOutgoingMessageWebhook) Encode(e *jx.Encoder) {
	e.Str(string(s))
}

// Decode decodes CreateInstanceRequestOutgoingMessageWebhook from json.
func (s *CreateInstanceRequestOutgoingMessageWebhook) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode CreateInstanceRequestOutgoingMessageWebhook to nil")
	}
	v, err := d.StrBytes()
	if err != nil {
		return err
	}
	// Try to use constant string.
	switch CreateInstanceRequestOutgoingMessageWebhook(v) {
	case CreateInstanceRequestOutgoingMessageWebhookYes:
		*s = CreateInstanceRequestOutgoingMessageWebhookYes
	case CreateInstanceRequestOutgoingMessageWebhookNo:
		*s = CreateInstanceRequestOutgoingMessageWebhookNo
	default:
		*s = CreateInstanceRequestOutgoingMessageWebhook(v)
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s CreateInstanceRequestOutgoingMessageWebhook) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateInstanceRequestOutgoingMessageWebhook) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes CreateInstanceRequestOutgoingWebhook as json.
func (s CreateInstanceRequestOutgoingWebhook) Encode(e *jx.Encoder) {
	e.Str(string(s))
}

// Decode decodes CreateInstanceRequestOutgoingWebhook from json.
func (s *CreateInstanceRequestOutgoingWebhook) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode CreateInstanceRequestOutgoingWebhook to nil")
	}
	v, err := d.StrBytes()
	if err != nil {
		return err
	}
	// Try to use constant string.
	switch CreateInstanceRequestOutgoingWebhook(v) {
	case CreateInstanceRequestOutgoingWebhookYes:
		*s = CreateInstanceRequestOutgoingWebhookYes
	case CreateInstanceRequestOutgoingWebhookNo:
		*s = CreateInstanceRequestOutgoingWebhookNo
	default:
		*s = CreateInstanceRequestOutgoingWebhook(v)
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s CreateInstanceRequestOutgoingWebhook) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateInstanceRequestOutgoingWebhook) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes CreateInstanceRequestStateWebhook as json.
func (s CreateInstanceRequestStateWebhook) Encode(e *jx.Encoder) {
	e.Str(string(s))
}

// Decode decodes CreateInstanceRequestStateWebhook from json.
func (s *CreateInstanceRequestStateWebhook) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode CreateInstanceRequestStateWebhook to nil")
	}
	v, err := d.StrBytes()
	if err != nil {
		return err
	}
	// Try to use constant string.
	switch CreateInstanceRequestStateWebhook(v) {
	case CreateInstanceRequestStateWebhookYes:
		*s = CreateInstanceRequestStateWebhookYes
	case CreateInstanceRequestStateWebhookNo:
		*s = CreateInstanceRequestStateWebhookNo
	default:
		*s = CreateInstanceRequestStateWebhook(v)
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s CreateInstanceRequestStateWebhook) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateInstanceRequestStateWebhook) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes CreateInstanceResponse as json.
func (s CreateInstanceResponse) Encode(e *jx.Encoder) {
	switch s.Type {
	case CreateInstanceSuccessResponseCreateInstanceResponse:
		s.CreateInstanceSuccessResponse.Encode(e)
	case ErrorResponseCreateInstanceResponse:
		s.ErrorResponse.Encode(e)
	}
}

func (s CreateInstanceResponse) encodeFields(e *jx.Encoder) {
	switch s.Type {
	case CreateInstanceSuccessResponseCreateInstanceResponse:
		s.CreateInstanceSuccessResponse.encodeFields(e)
	case ErrorResponseCreateInstanceResponse:
		s.ErrorResponse.encodeFields(e)
	}
}

// Decode decodes CreateInstanceResponse from json.
func (s *CreateInstanceResponse) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode CreateInstanceResponse to nil")
	}
	// Sum type fields.
	if typ := d.Next(); typ != jx.Object {
		return errors.Errorf("unexpected json type %q", typ)
	}

	var found bool
	if err := d.Capture(func(d *jx.Decoder) error {
		return d.ObjBytes(func(d *jx.Decoder, key []byte) error {
			switch string(key) {
			case "apiTokenInstance":
				// Type-based discrimination: check if field has expected JSON type
				if typ := d.Next(); typ != jx.String {
					// Field exists but has wrong type, not a match for this variant
					return d.Skip()
				}
				match := CreateInstanceSuccessResponseCreateInstanceResponse
				if found && s.Type != match {
					s.Type = ""
					return errors.Errorf("multiple oneOf matches: (%v, %v)", s.Type, match)
				}
				found = true
				s.Type = match
			case "apiUrl":
				match := CreateInstanceSuccessResponseCreateInstanceResponse
				if found && s.Type != match {
					s.Type = ""
					return errors.Errorf("multiple oneOf matches: (%v, %v)", s.Type, match)
				}
				found = true
				s.Type = match
			case "code":
				// Type-based discrimination: check if field has expected JSON type
				if typ := d.Next(); typ != jx.Number {
					// Field exists but has wrong type, not a match for this variant
					return d.Skip()
				}
				match := ErrorResponseCreateInstanceResponse
				if found && s.Type != match {
					s.Type = ""
					return errors.Errorf("multiple oneOf matches: (%v, %v)", s.Type, match)
				}
				found = true
				s.Type = match
			case "description":
				// Type-based discrimination: check if field has expected JSON type
				if typ := d.Next(); typ != jx.String {
					// Field exists but has wrong type, not a match for this variant
					return d.Skip()
				}
				match := ErrorResponseCreateInstanceResponse
				if found && s.Type != match {
					s.Type = ""
					return errors.Errorf("multiple oneOf matches: (%v, %v)", s.Type, match)
				}
				found = true
				s.Type = match
			case "idInstance":
				// Type-based discrimination: check if field has expected JSON type
				if typ := d.Next(); typ != jx.Number {
					// Field exists but has wrong type, not a match for this variant
					return d.Skip()
				}
				match := CreateInstanceSuccessResponseCreateInstanceResponse
				if found && s.Type != match {
					s.Type = ""
					return errors.Errorf("multiple oneOf matches: (%v, %v)", s.Type, match)
				}
				found = true
				s.Type = match
			case "mediaUrl":
				match := CreateInstanceSuccessResponseCreateInstanceResponse
				if found && s.Type != match {
					s.Type = ""
					return errors.Errorf("multiple oneOf matches: (%v, %v)", s.Type, match)
				}
				found = true
				s.Type = match
			case "typeInstance":
				// Type-based discrimination: check if field has expected JSON type
				if typ := d.Next(); typ != jx.String {
					// Field exists but has wrong type, not a match for this variant
					return d.Skip()
				}
				match := CreateInstanceSuccessResponseCreateInstanceResponse
				if found && s.Type != match {
					s.Type = ""
					return errors.Errorf("multiple oneOf matches: (%v, %v)", s.Type, match)
				}
				found = true
				s.Type = match
			}
			return d.Skip()
		})
	}); err != nil {
		return errors.Wrap(err, "capture")
	}
	if !found {
		return errors.New("unable to detect sum type variant")
	}
	switch s.Type {
	case CreateInstanceSuccessResponseCreateInstanceResponse:
		if err := s.CreateInstanceSuccessResponse.Decode(d); err != nil {
			return err
		}
	case ErrorResponseCreateInstanceResponse:
		if err := s.ErrorResponse.Decode(d); err != nil {
			return err
		}
	default:
		return errors.Errorf("inferred invalid type: %s", s.Type)
	}
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s CreateInstanceResponse) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateInstanceResponse) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode implements json.Marshaler.
func (s *CreateInstanceSuccessResponse) Encode(e *jx.Encoder) {
	e.ObjStart()
	s.encodeFields(e)
	e.ObjEnd()
}

// encodeFields encodes fields.
func (s *CreateInstanceSuccessResponse) encodeFields(e *jx.Encoder) {
	{
		if s.ApiTokenInstance.Set {
			e.FieldStart("apiTokenInstance")
			s.ApiTokenInstance.Encode(e)
		}
	}
	{
		if s.ApiUrl.Set {
			e.FieldStart("apiUrl")
			s.ApiUrl.Encode(e)
		}
	}
	{
		if s.IdInstance.Set {
			e.FieldStart("idInstance")
			s.IdInstance.Encode(e)
		}
	}
	{
		if s.MediaUrl.Set {
			e.FieldStart("mediaUrl")
			s.MediaUrl.Encode(e)
		}
	}
	{
		if s.TypeInstance.Set {
			e.FieldStart("typeInstance")
			s.TypeInstance.Encode(e)
		}
	}
}

var jsonFieldsNameOfCreateInstanceSuccessResponse = [5]string{
	0: "apiTokenInstance",
	1: "apiUrl",
	2: "idInstance",
	3: "mediaUrl",
	4: "typeInstance",
}

// Decode decodes CreateInstanceSuccessResponse from json.
func (s *CreateInstanceSuccessResponse) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode CreateInstanceSuccessResponse to nil")
	}

	if err := d.ObjBytes(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "apiTokenInstance":
			if err := func() error {
				s.ApiTokenInstance.Reset()
				if err := s.ApiTokenInstance.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"apiTokenInstance\"")
			}
		case "apiUrl":
			if err := func() error {
				s.ApiUrl.Reset()
				if err := s.ApiUrl.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"apiUrl\"")
			}
		case "idInstance":
			if err := func() error {
				s.IdInstance.Reset()
				if err := s.IdInstance.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"idInstance\"")
			}
		case "mediaUrl":
			if err := func() error {
				s.MediaUrl.Reset()
				if err := s.MediaUrl.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"mediaUrl\"")
			}
		case "typeInstance":
			if err := func() error {
				s.TypeInstance.Reset()
				if err := s.TypeInstance.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"typeInstance\"")
			}
		default:
			return d.Skip()
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode CreateInstanceSuccessResponse")
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *CreateInstanceSuccessResponse) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CreateInstanceSuccessResponse) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes DeleteInstanceAccountResponse as json.
func (s DeleteInstanceAccountResponse) Encode(e *jx.Encoder) {
	switch s.Type {
	case DeleteInstanceSuccessResponseDeleteInstanceAccountResponse:
		s.DeleteInstanceSuccessResponse.Encode(e)
	case ErrorResponseDeleteInstanceAccountResponse:
		s.ErrorResponse.Encode(e)
	}
}

func (s DeleteInstanceAccountResponse) encodeFields(e *jx.Encoder) {
	switch s.Type {
	case DeleteInstanceSuccessResponseDeleteInstanceAccountResponse:
		s.DeleteInstanceSuccessResponse.encodeFields(e)
	case ErrorResponseDeleteInstanceAccountResponse:
		s.ErrorResponse.encodeFields(e)
	}
}

// Decode decodes DeleteInstanceAccountResponse from json.
func (s *DeleteInstanceAccountResponse) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode DeleteInstanceAccountResponse to nil")
	}
	// Sum type fields.
	if typ := d.Next(); typ != jx.Object {
		return errors.Errorf("unexpected json type %q", typ)
	}

	var found bool
	if err := d.Capture(func(d *jx.Decoder) error {
		return d.ObjBytes(func(d *jx.Decoder, key []byte) error {
			switch string(key) {
			case "code":
				// Type-based discrimination: check if field has expected JSON type
				if typ := d.Next(); typ != jx.Number {
					// Field exists but has wrong type, not a match for this variant
					return d.Skip()
				}
				match := ErrorResponseDeleteInstanceAccountResponse
				if found && s.Type != match {
					s.Type = ""
					return errors.Errorf("multiple oneOf matches: (%v, %v)", s.Type, match)
				}
				found = true
				s.Type = match
			case "deleteInstanceAccount":
				// Type-based discrimination: check if field has expected JSON type
				if typ := d.Next(); typ != jx.Bool {
					// Field exists but has wrong type, not a match for this variant
					return d.Skip()
				}
				match := DeleteInstanceSuccessResponseDeleteInstanceAccountResponse
				if found && s.Type != match {
					s.Type = ""
					return errors.Errorf("multiple oneOf matches: (%v, %v)", s.Type, match)
				}
				found = true
				s.Type = match
			case "description":
				// Type-based discrimination: check if field has expected JSON type
				if typ := d.Next(); typ != jx.String {
					// Field exists but has wrong type, not a match for this variant
					return d.Skip()
				}
				match := ErrorResponseDeleteInstanceAccountResponse
				if found && s.Type != match {
					s.Type = ""
					return errors.Errorf("multiple oneOf matches: (%v, %v)", s.Type, match)
				}
				found = true
				s.Type = match
			}
			return d.Skip()
		})
	}); err != nil {
		return errors.Wrap(err, "capture")
	}
	if !found {
		return errors.New("unable to detect sum type variant")
	}
	switch s.Type {
	case DeleteInstanceSuccessResponseDeleteInstanceAccountResponse:
		if err := s.DeleteInstanceSuccessResponse.Decode(d); err != nil {
			return err
		}
	case ErrorResponseDeleteInstanceAccountResponse:
		if err := s.ErrorResponse.Decode(d); err != nil {
			return err
		}
	default:
		return errors.Errorf("inferred invalid type: %s", s.Type)
	}
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s DeleteInstanceAccountResponse) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *DeleteInstanceAccountResponse) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode implements json.Marshaler.
func (s *DeleteInstanceRequest) Encode(e *jx.Encoder) {
	e.ObjStart()
	s.encodeFields(e)
	e.ObjEnd()
}

// encodeFields encodes fields.
func (s *DeleteInstanceRequest) encodeFields(e *jx.Encoder) {
	{
		e.FieldStart("idInstance")
		e.Int64(s.IdInstance)
	}
}

var jsonFieldsNameOfDeleteInstanceRequest = [1]string{
	0: "idInstance",
}

// Decode decodes DeleteInstanceRequest from json.
func (s *DeleteInstanceRequest) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode DeleteInstanceRequest to nil")
	}
	var requiredBitSet [1]uint8

	if err := d.ObjBytes(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "idInstance":
			requiredBitSet[0] |= 1 << 0
			if err := func() error {
				v, err := d.Int64()
				s.IdInstance = int64(v)
				if err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"idInstance\"")
			}
		default:
			return d.Skip()
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode DeleteInstanceRequest")
	}
	// Validate required fields.
	var failures []validate.FieldError
	for i, mask := range [1]uint8{
		0b00000001,
	} {
		if result := (requiredBitSet[i] & mask) ^ mask; result != 0 {
			// Mask only required fields and check equality to mask using XOR.
			//
			// If XOR result is not zero, result is not equal to expected, so some fields are missed.
			// Bits of fields which would be set are actually bits of missed fields.
			missed := bits.OnesCount8(result)
			for bitN := 0; bitN < missed; bitN++ {
				bitIdx := bits.TrailingZeros8(result)
				fieldIdx := i*8 + bitIdx
				var name string
				if fieldIdx < len(jsonFieldsNameOfDeleteInstanceRequest) {
					name = jsonFieldsNameOfDeleteInstanceRequest[fieldIdx]
				} else {
					name = strconv.Itoa(fieldIdx)
				}
				failures = append(failures, validate.FieldError{
					Name:  name,
					Error: validate.ErrFieldRequired,
				})
				// Reset bit.
				result &^= 1 << bitIdx
			}
		}
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *DeleteInstanceRequest) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *DeleteInstanceRequest) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode implements json.Marshaler.
func (s *DeleteInstanceSuccessResponse) Encode(e *jx.Encoder) {
	e.ObjStart()
	s.encodeFields(e)
	e.ObjEnd()
}

// encodeFields encodes fields.
func (s *DeleteInstanceSuccessResponse) encodeFields(e *jx.Encoder) {
	{
		e.FieldStart("deleteInstanceAccount")
		e.Bool(s.DeleteInstanceAccount)
	}
}

var jsonFieldsNameOfDeleteInstanceSuccessResponse = [1]string{
	0: "deleteInstanceAccount",
}

// Decode decodes DeleteInstanceSuccessResponse from json.
func (s *DeleteInstanceSuccessResponse) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode DeleteInstanceSuccessResponse to nil")
	}
	var requiredBitSet [1]uint8

	if err := d.ObjBytes(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "deleteInstanceAccount":
			requiredBitSet[0] |= 1 << 0
			if err := func() error {
				v, err := d.Bool()
				s.DeleteInstanceAccount = bool(v)
				if err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"deleteInstanceAccount\"")
			}
		default:
			return d.Skip()
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode DeleteInstanceSuccessResponse")
	}
	// Validate required fields.
	var failures []validate.FieldError
	for i, mask := range [1]uint8{
		0b00000001,
	} {
		if result := (requiredBitSet[i] & mask) ^ mask; result != 0 {
			// Mask only required fields and check equality to mask using XOR.
			//
			// If XOR result is not zero, result is not equal to expected, so some fields are missed.
			// Bits of fields which would be set are actually bits of missed fields.
			missed := bits.OnesCount8(result)
			for bitN := 0; bitN < missed; bitN++ {
				bitIdx := bits.TrailingZeros8(result)
				fieldIdx := i*8 + bitIdx
				var name string
				if fieldIdx < len(jsonFieldsNameOfDeleteInstanceSuccessResponse) {
					name = jsonFieldsNameOfDeleteInstanceSuccessResponse[fieldIdx]
				} else {
					name = strconv.Itoa(fieldIdx)
				}
				failures = append(failures, validate.FieldError{
					Name:  name,
					Error: validate.ErrFieldRequired,
				})
				// Reset bit.
				result &^= 1 << bitIdx
			}
		}
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *DeleteInstanceSuccessResponse) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *DeleteInstanceSuccessResponse) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode implements json.Marshaler.
func (s *ErrorResponse) Encode(e *jx.Encoder) {
	e.ObjStart()
	s.encodeFields(e)
	e.ObjEnd()
}

// encodeFields encodes fields.
func (s *ErrorResponse) encodeFields(e *jx.Encoder) {
	{
		e.FieldStart("code")
		e.Int(s.Code)
	}
	{
		e.FieldStart("description")
		e.Str(s.Description)
	}
}

var jsonFieldsNameOfErrorResponse = [2]string{
	0: "code",
	1: "description",
}

// Decode decodes ErrorResponse from json.
func (s *ErrorResponse) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode ErrorResponse to nil")
	}
	var requiredBitSet [1]uint8

	if err := d.ObjBytes(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "code":
			requiredBitSet[0] |= 1 << 0
			if err := func() error {
				v, err := d.Int()
				s.Code = int(v)
				if err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"code\"")
			}
		case "description":
			requiredBitSet[0] |= 1 << 1
			if err := func() error {
				v, err := d.Str()
				s.Description = string(v)
				if err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"description\"")
			}
		default:
			return d.Skip()
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode ErrorResponse")
	}
	// Validate required fields.
	var failures []validate.FieldError
	for i, mask := range [1]uint8{
		0b00000011,
	} {
		if result := (requiredBitSet[i] & mask) ^ mask; result != 0 {
			// Mask only required fields and check equality to mask using XOR.
			//
			// If XOR result is not zero, result is not equal to expected, so some fields are missed.
			// Bits of fields which would be set are actually bits of missed fields.
			missed := bits.OnesCount8(result)
			for bitN := 0; bitN < missed; bitN++ {
				bitIdx := bits.TrailingZeros8(result)
				fieldIdx := i*8 + bitIdx
				var name string
				if fieldIdx < len(jsonFieldsNameOfErrorResponse) {
					name = jsonFieldsNameOfErrorResponse[fieldIdx]
				} else {
					name = strconv.Itoa(fieldIdx)
				}
				failures = append(failures, validate.FieldError{
					Name:  name,
					Error: validate.ErrFieldRequired,
				})
				// Reset bit.
				result &^= 1 << bitIdx
			}
		}
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *ErrorResponse) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *ErrorResponse) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes GetInstancesResponse as json.
func (s GetInstancesResponse) Encode(e *jx.Encoder) {
	switch s.Type {
	case PartnerInstanceArrayGetInstancesResponse:
		e.ArrStart()
		for _, elem := range s.PartnerInstanceArray {
			elem.Encode(e)
		}
		e.ArrEnd()
	case ErrorResponseGetInstancesResponse:
		s.ErrorResponse.Encode(e)
	}
}

// Decode decodes GetInstancesResponse from json.
func (s *GetInstancesResponse) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode GetInstancesResponse to nil")
	}
	// Sum type type_discriminator.
	switch t := d.Next(); t {
	case jx.Array:
		s.PartnerInstanceArray = make([]PartnerInstance, 0)
		if err := d.Arr(func(d *jx.Decoder) error {
			var elem PartnerInstance
			if err := elem.Decode(d); err != nil {
				return err
			}
			s.PartnerInstanceArray = append(s.PartnerInstanceArray, elem)
			return nil
		}); err != nil {
			return err
		}
		s.Type = PartnerInstanceArrayGetInstancesResponse
	case jx.Object:
		if err := s.ErrorResponse.Decode(d); err != nil {
			return err
		}
		s.Type = ErrorResponseGetInstancesResponse
	default:
		return errors.Errorf("unexpected json type %q", t)
	}
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s GetInstancesResponse) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *GetInstancesResponse) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes CreateInstanceRequestIncomingWebhook as json.
func (o OptCreateInstanceRequestIncomingWebhook) Encode(e *jx.Encoder) {
	if !o.Set {
		return
	}
	e.Str(string(o.Value))
}

// Decode decodes CreateInstanceRequestIncomingWebhook from json.
func (o *OptCreateInstanceRequestIncomingWebhook) Decode(d *jx.Decoder) error {
	if o == nil {
		return errors.New("invalid: unable to decode OptCreateInstanceRequestIncomingWebhook to nil")
	}
	o.Set = true
	if err := o.Value.Decode(d); err != nil {
		return err
	}
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptCreateInstanceRequestIncomingWebhook) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptCreateInstanceRequestIncomingWebhook) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes CreateInstanceRequestMarkIncomingMessagesReaded as json.
func (o OptCreateInstanceRequestMarkIncomingMessagesReaded) Encode(e *jx.Encoder) {
	if !o.Set {
		return
	}
	e.Str(string(o.Value))
}

// Decode decodes CreateInstanceRequestMarkIncomingMessagesReaded from json.
func (o *OptCreateInstanceRequestMarkIncomingMessagesReaded) Decode(d *jx.Decoder) error {
	if o == nil {
		return errors.New("invalid: unable to decode OptCreateInstanceRequestMarkIncomingMessagesReaded to nil")
	}
	o.Set = true
	if err := o.Value.Decode(d); err != nil {
		return err
	}
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptCreateInstanceRequestMarkIncomingMessagesReaded) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptCreateInstanceRequestMarkIncomingMessagesReaded) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes CreateInstanceRequestMarkIncomingMessagesReadedOnReply as json.
func (o OptCreateInstanceRequestMarkIncomingMessagesReadedOnReply) Encode(e *jx.Encoder) {
	if !o.Set {
		return
	}
	e.Str(string(o.Value))
}

// Decode decodes CreateInstanceRequestMarkIncomingMessagesReadedOnReply from json.
func (o *OptCreateInstanceRequestMarkIncomingMessagesReadedOnReply) Decode(d *jx.Decoder) error {
	if o == nil {
		return errors.New("invalid: unable to decode OptCreateInstanceRequestMarkIncomingMessagesReadedOnReply to nil")
	}
	o.Set = true
	if err := o.Value.Decode(d); err != nil {
		return err
	}
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptCreateInstanceRequestMarkIncomingMessagesReadedOnReply) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptCreateInstanceRequestMarkIncomingMessagesReadedOnReply) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes CreateInstanceRequestOutgoingAPIMessageWebhook as json.
func (o OptCreateInstanceRequestOutgoingAPIMessageWebhook) Encode(e *jx.Encoder) {
	if !o.Set {
		return
	}
	e.Str(string(o.Value))
}

// Decode decodes CreateInstanceRequestOutgoingAPIMessageWebhook from json.
func (o *OptCreateInstanceRequestOutgoingAPIMessageWebhook) Decode(d *jx.Decoder) error {
	if o == nil {
		return errors.New("invalid: unable to decode OptCreateInstanceRequestOutgoingAPIMessageWebhook to nil")
	}
	o.Set = true
	if err := o.Value.Decode(d); err != nil {
		return err
	}
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptCreateInstanceRequestOutgoingAPIMessageWebhook) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptCreateInstanceRequestOutgoingAPIMessageWebhook) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes CreateInstanceRequestOutgoingMessageWebhook as json.
func (o OptCreateInstanceRequestOutgoingMessageWebhook) Encode(e *jx.Encoder) {
	if !o.Set {
		return
	}
	e.Str(string(o.Value))
}

// Decode decodes CreateInstanceRequestOutgoingMessageWebhook from json.
func (o *OptCreateInstanceRequestOutgoingMessageWebhook) Decode(d *jx.Decoder) error {
	if o == nil {
		return errors.New("invalid: unable to decode OptCreateInstanceRequestOutgoingMessageWebhook to nil")
	}
	o.Set = true
	if err := o.Value.Decode(d); err != nil {
		return err
	}
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptCreateInstanceRequestOutgoingMessageWebhook) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptCreateInstanceRequestOutgoingMessageWebhook) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes CreateInstanceRequestOutgoingWebhook as json.
func (o OptCreateInstanceRequestOutgoingWebhook) Encode(e *jx.Encoder) {
	if !o.Set {
		return
	}
	e.Str(string(o.Value))
}

// Decode decodes CreateInstanceRequestOutgoingWebhook from json.
func (o *OptCreateInstanceRequestOutgoingWebhook) Decode(d *jx.Decoder) error {
	if o == nil {
		return errors.New("invalid: unable to decode OptCreateInstanceRequestOutgoingWebhook to nil")
	}
	o.Set = true
	if err := o.Value.Decode(d); err != nil {
		return err
	}
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptCreateInstanceRequestOutgoingWebhook) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptCreateInstanceRequestOutgoingWebhook) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes CreateInstanceRequestStateWebhook as json.
func (o OptCreateInstanceRequestStateWebhook) Encode(e *jx.Encoder) {
	if !o.Set {
		return
	}
	e.Str(string(o.Value))
}

// Decode decodes CreateInstanceRequestStateWebhook from json.
func (o *OptCreateInstanceRequestStateWebhook) Decode(d *jx.Decoder) error {
	if o == nil {
		return errors.New("invalid: unable to decode OptCreateInstanceRequestStateWebhook to nil")
	}
	o.Set = true
	if err := o.Value.Decode(d); err != nil {
		return err
	}
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptCreateInstanceRequestStateWebhook) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptCreateInstanceRequestStateWebhook) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes time.Time as json.
func (o OptDateTime) Encode(e *jx.Encoder, format func(*jx.Encoder, time.Time)) {
	if !o.Set {
		return
	}
	format(e, o.Value)
}

// Decode decodes time.Time from json.
func (o *OptDateTime) Decode(d *jx.Decoder, format func(*jx.Decoder) (time.Time, error)) error {
	if o == nil {
		return errors.New("invalid: unable to decode OptDateTime to nil")
	}
	o.Set = true
	v, err := format(d)
	if err != nil {
		return err
	}
	o.Value = v
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptDateTime) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e, json.EncodeDateTime)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptDateTime) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d, json.DecodeDateTime)
}

// Encode encodes float64 as json.
func (o OptFloat64) Encode(e *jx.Encoder) {
	if !o.Set {
		return
	}
	e.Float64(float64(o.Value))
}

// Decode decodes float64 from json.
func (o *OptFloat64) Decode(d *jx.Decoder) error {
	if o == nil {
		return errors.New("invalid: unable to decode OptFloat64 to nil")
	}
	o.Set = true
	v, err := d.Float64()
	if err != nil {
		return err
	}
	o.Value = float64(v)
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptFloat64) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptFloat64) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes int as json.
func (o OptInt) Encode(e *jx.Encoder) {
	if !o.Set {
		return
	}
	e.Int(int(o.Value))
}

// Decode decodes int from json.
func (o *OptInt) Decode(d *jx.Decoder) error {
	if o == nil {
		return errors.New("invalid: unable to decode OptInt to nil")
	}
	o.Set = true
	v, err := d.Int()
	if err != nil {
		return err
	}
	o.Value = int(v)
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptInt) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptInt) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes string as json.
func (o OptString) Encode(e *jx.Encoder) {
	if !o.Set {
		return
	}
	e.Str(string(o.Value))
}

// Decode decodes string from json.
func (o *OptString) Decode(d *jx.Decoder) error {
	if o == nil {
		return errors.New("invalid: unable to decode OptString to nil")
	}
	o.Set = true
	v, err := d.Str()
	if err != nil {
		return err
	}
	o.Value = string(v)
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptString) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptString) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes url.URL as json.
func (o OptURI) Encode(e *jx.Encoder) {
	if !o.Set {
		return
	}
	json.EncodeURI(e, o.Value)
}

// Decode decodes url.URL from json.
func (o *OptURI) Decode(d *jx.Decoder) error {
	if o == nil {
		return errors.New("invalid: unable to decode OptURI to nil")
	}
	o.Set = true
	v, err := json.DecodeURI(d)
	if err != nil {
		return err
	}
	o.Value = v
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptURI) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptURI) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode implements json.Marshaler.
func (s *PartnerInstance) Encode(e *jx.Encoder) {
	e.ObjStart()
	s.encodeFields(e)
	e.ObjEnd()
}

// encodeFields encodes fields.
func (s *PartnerInstance) encodeFields(e *jx.Encoder) {
	{
		e.FieldStart("idInstance")
		e.Int64(s.IdInstance)
	}
	{
		e.FieldStart("name")
		e.Str(s.Name)
	}
	{
		e.FieldStart("typeInstance")
		e.Str(s.TypeInstance)
	}
	{
		if s.TypeAccount.Set {
			e.FieldStart("typeAccount")
			s.TypeAccount.Encode(e)
		}
	}
	{
		if s.PartnerUserUiid.Set {
			e.FieldStart("partnerUserUiid")
			s.PartnerUserUiid.Encode(e)
		}
	}
	{
		e.FieldStart("timeCreated")
		json.EncodeDateTime(e, s.TimeCreated)
	}
	{
		if s.TimeDeleted.Set {
			e.FieldStart("timeDeleted")
			s.TimeDeleted.Encode(e, json.EncodeDateTime)
		}
	}
	{
		e.FieldStart("apiTokenInstance")
		e.Str(s.ApiTokenInstance)
	}
	{
		e.FieldStart("deleted")
		e.Bool(s.Deleted)
	}
	{
		e.FieldStart("tariff")
		e.Str(s.Tariff)
	}
	{
		e.FieldStart("isFree")
		e.Bool(s.IsFree)
	}
	{
		e.FieldStart("isPartner")
		e.Bool(s.IsPartner)
	}
	{
		e.FieldStart("expirationDate")
		json.EncodeDateTime(e, s.ExpirationDate)
	}
	{
		e.FieldStart("isExpired")
		e.Bool(s.IsExpired)
	}
}

var jsonFieldsNameOfPartnerInstance = [14]string{
	0:  "idInstance",
	1:  "name",
	2:  "typeInstance",
	3:  "typeAccount",
	4:  "partnerUserUiid",
	5:  "timeCreated",
	6:  "timeDeleted",
	7:  "apiTokenInstance",
	8:  "deleted",
	9:  "tariff",
	10: "isFree",
	11: "isPartner",
	12: "expirationDate",
	13: "isExpired",
}

// Decode decodes PartnerInstance from json.
func (s *PartnerInstance) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode PartnerInstance to nil")
	}
	var requiredBitSet [2]uint8

	if err := d.ObjBytes(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "idInstance":
			requiredBitSet[0] |= 1 << 0
			if err := func() error {
				v, err := d.Int64()
				s.IdInstance = int64(v)
				if err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"idInstance\"")
			}
		case "name":
			requiredBitSet[0] |= 1 << 1
			if err := func() error {
				v, err := d.Str()
				s.Name = string(v)
				if err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"name\"")
			}
		case "typeInstance":
			requiredBitSet[0] |= 1 << 2
			if err := func() error {
				v, err := d.Str()
				s.TypeInstance = string(v)
				if err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"typeInstance\"")
			}
		case "typeAccount":
			if err := func() error {
				s.TypeAccount.Reset()
				if err := s.TypeAccount.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"typeAccount\"")
			}
		case "partnerUserUiid":
			if err := func() error {
				s.PartnerUserUiid.Reset()
				if err := s.PartnerUserUiid.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"partnerUserUiid\"")
			}
		case "timeCreated":
			requiredBitSet[0] |= 1 << 5
			if err := func() error {
				v, err := json.DecodeDateTime(d)
				s.TimeCreated = v
				if err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"timeCreated\"")
			}
		case "timeDeleted":
			if err := func() error {
				s.TimeDeleted.Reset()
				if err := s.TimeDeleted.Decode(d, json.DecodeDateTime); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"timeDeleted\"")
			}
		case "apiTokenInstance":
			requiredBitSet[0] |= 1 << 7
			if err := func() error {
				v, err := d.Str()
				s.ApiTokenInstance = string(v)
				if err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"apiTokenInstance\"")
			}
		case "deleted":
			requiredBitSet[1] |= 1 << 0
			if err := func() error {
				v, err := d.Bool()
				s.Deleted = bool(v)
				if err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"deleted\"")
			}
		case "tariff":
			requiredBitSet[1] |= 1 << 1
			if err := func() error {
				v, err := d.Str()
				s.Tariff = string(v)
				if err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"tariff\"")
			}
		case "isFree":
			requiredBitSet[1] |= 1 << 2
			if err := func() error {
				v, err := d.Bool()
				s.IsFree = bool(v)
				if err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"isFree\"")
			}
		case "isPartner":
			requiredBitSet[1] |= 1 << 3
			if err := func() error {
				v, err := d.Bool()
				s.IsPartner = bool(v)
				if err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"isPartner\"")
			}
		case "expirationDate":
			requiredBitSet[1] |= 1 << 4
			if err := func() error {
				v, err := json.DecodeDateTime(d)
				s.ExpirationDate = v
				if err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"expirationDate\"")
			}
		case "isExpired":
			requiredBitSet[1] |= 1 << 5
			if err := func() error {
				v, err := d.Bool()
				s.IsExpired = bool(v)
				if err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"isExpired\"")
			}
		default:
			return d.Skip()
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode PartnerInstance")
	}
	// Validate required fields.
	var failures []validate.FieldError
	for i, mask := range [2]uint8{
		0b10100111,
		0b00111111,
	} {
		if result := (requiredBitSet[i] & mask) ^ mask; result != 0 {
			// Mask only required fields and check equality to mask using XOR.
			//
			// If XOR result is not zero, result is not equal to expected, so some fields are missed.
			// Bits of fields which would be set are actually bits of missed fields.
			missed := bits.OnesCount8(result)
			for bitN := 0; bitN < missed; bitN++ {
				bitIdx := bits.TrailingZeros8(result)
				fieldIdx := i*8 + bitIdx
				var name string
				if fieldIdx < len(jsonFieldsNameOfPartnerInstance) {
					name = jsonFieldsNameOfPartnerInstance[fieldIdx]
				} else {
					name = strconv.Itoa(fieldIdx)
				}
				failures = append(failures, validate.FieldError{
					Name:  name,
					Error: validate.ErrFieldRequired,
				})
				// Reset bit.
				result &^= 1 << bitIdx
			}
		}
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *PartnerInstance) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *PartnerInstance) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}
