// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateInstance implements createInstance operation.
//
// Создание инстанса.
//
// POST /partners/createInstance/{partnerToken}
func (UnimplementedHandler) CreateInstance(ctx context.Context, req *CreateInstanceRequest, params CreateInstanceParams) (r CreateInstanceResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteInstanceAccount implements deleteInstanceAccount operation.
//
// Метод предназначен для удаления инстанса на аккаунте
// партнера.
// В случае ошибок (Unauthorized, Not found) API возвращает HTTP 200
// с телом ошибки (code, description).
//
// POST /partner/deleteInstanceAccount/{partnerToken}
func (UnimplementedHandler) DeleteInstanceAccount(ctx context.Context, req *DeleteInstanceRequest, params DeleteInstanceAccountParams) (r DeleteInstanceAccountResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// GetInstances implements getInstances operation.
//
// Метод предназначен для получения всех инстансов на
// аккаунте партнера.
// В случае ошибки авторизации API может вернуть HTTP 200
// с телом ошибки (code, description).
//
// GET /partner/getInstances/{partnerToken}
func (UnimplementedHandler) GetInstances(ctx context.Context, params GetInstancesParams) (r GetInstancesRes, _ error) {
	return r, ht.ErrNotImplemented
}
