// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateInstance implements createInstance operation.
	//
	// Создание инстанса.
	//
	// POST /partner/createInstance/{partnerToken}
	CreateInstance(ctx context.Context, req *CreateInstanceRequest, params CreateInstanceParams) (CreateInstanceResponse, error)
	// DeleteInstanceAccount implements deleteInstanceAccount operation.
	//
	// Метод предназначен для удаления инстанса на аккаунте
	// партнера.
	// В случае ошибок (Unauthorized, Not found) API возвращает HTTP 200
	// с телом ошибки (code, description).
	//
	// POST /partner/deleteInstanceAccount/{partnerToken}
	DeleteInstanceAccount(ctx context.Context, req *DeleteInstanceRequest, params DeleteInstanceAccountParams) (DeleteInstanceAccountResponse, error)
	// GetInstances implements getInstances operation.
	//
	// Метод предназначен для получения всех инстансов на
	// аккаунте партнера.
	// В случае ошибки авторизации API может вернуть HTTP 200
	// с телом ошибки (code, description).
	//
	// GET /partner/getInstances/{partnerToken}
	GetInstances(ctx context.Context, params GetInstancesParams) (GetInstancesRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
