// Code generated by ogen, DO NOT EDIT.

package api

import (
	"io"
	"net/url"
	"time"

	"github.com/go-faster/errors"
)

// Ref: #/components/schemas/CreateInstanceRequest
type CreateInstanceRequest struct {
	// Название инстанса.
	Name OptString `json:"name"`
	// URL webhook.
	WebhookUrl OptURI `json:"webhookUrl"`
	// Токен для валидации webhook.
	WebhookUrlToken                   OptString                                                 `json:"webhookUrlToken"`
	DelaySendMessagesMilliseconds     OptInt                                                    `json:"delaySendMessagesMilliseconds"`
	MarkIncomingMessagesReaded        OptCreateInstanceRequestMarkIncomingMessagesReaded        `json:"markIncomingMessagesReaded"`
	MarkIncomingMessagesReadedOnReply OptCreateInstanceRequestMarkIncomingMessagesReadedOnReply `json:"markIncomingMessagesReadedOnReply"`
	OutgoingAPIMessageWebhook         OptCreateInstanceRequestOutgoingAPIMessageWebhook         `json:"outgoingAPIMessageWebhook"`
	OutgoingWebhook                   OptCreateInstanceRequestOutgoingWebhook                   `json:"outgoingWebhook"`
	OutgoingMessageWebhook            OptCreateInstanceRequestOutgoingMessageWebhook            `json:"outgoingMessageWebhook"`
	IncomingWebhook                   OptCreateInstanceRequestIncomingWebhook                   `json:"incomingWebhook"`
	StateWebhook                      OptCreateInstanceRequestStateWebhook                      `json:"stateWebhook"`
}

// GetName returns the value of Name.
func (s *CreateInstanceRequest) GetName() OptString {
	return s.Name
}

// GetWebhookUrl returns the value of WebhookUrl.
func (s *CreateInstanceRequest) GetWebhookUrl() OptURI {
	return s.WebhookUrl
}

// GetWebhookUrlToken returns the value of WebhookUrlToken.
func (s *CreateInstanceRequest) GetWebhookUrlToken() OptString {
	return s.WebhookUrlToken
}

// GetDelaySendMessagesMilliseconds returns the value of DelaySendMessagesMilliseconds.
func (s *CreateInstanceRequest) GetDelaySendMessagesMilliseconds() OptInt {
	return s.DelaySendMessagesMilliseconds
}

// GetMarkIncomingMessagesReaded returns the value of MarkIncomingMessagesReaded.
func (s *CreateInstanceRequest) GetMarkIncomingMessagesReaded() OptCreateInstanceRequestMarkIncomingMessagesReaded {
	return s.MarkIncomingMessagesReaded
}

// GetMarkIncomingMessagesReadedOnReply returns the value of MarkIncomingMessagesReadedOnReply.
func (s *CreateInstanceRequest) GetMarkIncomingMessagesReadedOnReply() OptCreateInstanceRequestMarkIncomingMessagesReadedOnReply {
	return s.MarkIncomingMessagesReadedOnReply
}

// GetOutgoingAPIMessageWebhook returns the value of OutgoingAPIMessageWebhook.
func (s *CreateInstanceRequest) GetOutgoingAPIMessageWebhook() OptCreateInstanceRequestOutgoingAPIMessageWebhook {
	return s.OutgoingAPIMessageWebhook
}

// GetOutgoingWebhook returns the value of OutgoingWebhook.
func (s *CreateInstanceRequest) GetOutgoingWebhook() OptCreateInstanceRequestOutgoingWebhook {
	return s.OutgoingWebhook
}

// GetOutgoingMessageWebhook returns the value of OutgoingMessageWebhook.
func (s *CreateInstanceRequest) GetOutgoingMessageWebhook() OptCreateInstanceRequestOutgoingMessageWebhook {
	return s.OutgoingMessageWebhook
}

// GetIncomingWebhook returns the value of IncomingWebhook.
func (s *CreateInstanceRequest) GetIncomingWebhook() OptCreateInstanceRequestIncomingWebhook {
	return s.IncomingWebhook
}

// GetStateWebhook returns the value of StateWebhook.
func (s *CreateInstanceRequest) GetStateWebhook() OptCreateInstanceRequestStateWebhook {
	return s.StateWebhook
}

// SetName sets the value of Name.
func (s *CreateInstanceRequest) SetName(val OptString) {
	s.Name = val
}

// SetWebhookUrl sets the value of WebhookUrl.
func (s *CreateInstanceRequest) SetWebhookUrl(val OptURI) {
	s.WebhookUrl = val
}

// SetWebhookUrlToken sets the value of WebhookUrlToken.
func (s *CreateInstanceRequest) SetWebhookUrlToken(val OptString) {
	s.WebhookUrlToken = val
}

// SetDelaySendMessagesMilliseconds sets the value of DelaySendMessagesMilliseconds.
func (s *CreateInstanceRequest) SetDelaySendMessagesMilliseconds(val OptInt) {
	s.DelaySendMessagesMilliseconds = val
}

// SetMarkIncomingMessagesReaded sets the value of MarkIncomingMessagesReaded.
func (s *CreateInstanceRequest) SetMarkIncomingMessagesReaded(val OptCreateInstanceRequestMarkIncomingMessagesReaded) {
	s.MarkIncomingMessagesReaded = val
}

// SetMarkIncomingMessagesReadedOnReply sets the value of MarkIncomingMessagesReadedOnReply.
func (s *CreateInstanceRequest) SetMarkIncomingMessagesReadedOnReply(val OptCreateInstanceRequestMarkIncomingMessagesReadedOnReply) {
	s.MarkIncomingMessagesReadedOnReply = val
}

// SetOutgoingAPIMessageWebhook sets the value of OutgoingAPIMessageWebhook.
func (s *CreateInstanceRequest) SetOutgoingAPIMessageWebhook(val OptCreateInstanceRequestOutgoingAPIMessageWebhook) {
	s.OutgoingAPIMessageWebhook = val
}

// SetOutgoingWebhook sets the value of OutgoingWebhook.
func (s *CreateInstanceRequest) SetOutgoingWebhook(val OptCreateInstanceRequestOutgoingWebhook) {
	s.OutgoingWebhook = val
}

// SetOutgoingMessageWebhook sets the value of OutgoingMessageWebhook.
func (s *CreateInstanceRequest) SetOutgoingMessageWebhook(val OptCreateInstanceRequestOutgoingMessageWebhook) {
	s.OutgoingMessageWebhook = val
}

// SetIncomingWebhook sets the value of IncomingWebhook.
func (s *CreateInstanceRequest) SetIncomingWebhook(val OptCreateInstanceRequestIncomingWebhook) {
	s.IncomingWebhook = val
}

// SetStateWebhook sets the value of StateWebhook.
func (s *CreateInstanceRequest) SetStateWebhook(val OptCreateInstanceRequestStateWebhook) {
	s.StateWebhook = val
}

type CreateInstanceRequestIncomingWebhook string

const (
	CreateInstanceRequestIncomingWebhookYes CreateInstanceRequestIncomingWebhook = "yes"
	CreateInstanceRequestIncomingWebhookNo  CreateInstanceRequestIncomingWebhook = "no"
)

// AllValues returns all CreateInstanceRequestIncomingWebhook values.
func (CreateInstanceRequestIncomingWebhook) AllValues() []CreateInstanceRequestIncomingWebhook {
	return []CreateInstanceRequestIncomingWebhook{
		CreateInstanceRequestIncomingWebhookYes,
		CreateInstanceRequestIncomingWebhookNo,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CreateInstanceRequestIncomingWebhook) MarshalText() ([]byte, error) {
	switch s {
	case CreateInstanceRequestIncomingWebhookYes:
		return []byte(s), nil
	case CreateInstanceRequestIncomingWebhookNo:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CreateInstanceRequestIncomingWebhook) UnmarshalText(data []byte) error {
	switch CreateInstanceRequestIncomingWebhook(data) {
	case CreateInstanceRequestIncomingWebhookYes:
		*s = CreateInstanceRequestIncomingWebhookYes
		return nil
	case CreateInstanceRequestIncomingWebhookNo:
		*s = CreateInstanceRequestIncomingWebhookNo
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type CreateInstanceRequestMarkIncomingMessagesReaded string

const (
	CreateInstanceRequestMarkIncomingMessagesReadedYes CreateInstanceRequestMarkIncomingMessagesReaded = "yes"
	CreateInstanceRequestMarkIncomingMessagesReadedNo  CreateInstanceRequestMarkIncomingMessagesReaded = "no"
)

// AllValues returns all CreateInstanceRequestMarkIncomingMessagesReaded values.
func (CreateInstanceRequestMarkIncomingMessagesReaded) AllValues() []CreateInstanceRequestMarkIncomingMessagesReaded {
	return []CreateInstanceRequestMarkIncomingMessagesReaded{
		CreateInstanceRequestMarkIncomingMessagesReadedYes,
		CreateInstanceRequestMarkIncomingMessagesReadedNo,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CreateInstanceRequestMarkIncomingMessagesReaded) MarshalText() ([]byte, error) {
	switch s {
	case CreateInstanceRequestMarkIncomingMessagesReadedYes:
		return []byte(s), nil
	case CreateInstanceRequestMarkIncomingMessagesReadedNo:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CreateInstanceRequestMarkIncomingMessagesReaded) UnmarshalText(data []byte) error {
	switch CreateInstanceRequestMarkIncomingMessagesReaded(data) {
	case CreateInstanceRequestMarkIncomingMessagesReadedYes:
		*s = CreateInstanceRequestMarkIncomingMessagesReadedYes
		return nil
	case CreateInstanceRequestMarkIncomingMessagesReadedNo:
		*s = CreateInstanceRequestMarkIncomingMessagesReadedNo
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type CreateInstanceRequestMarkIncomingMessagesReadedOnReply string

const (
	CreateInstanceRequestMarkIncomingMessagesReadedOnReplyYes CreateInstanceRequestMarkIncomingMessagesReadedOnReply = "yes"
	CreateInstanceRequestMarkIncomingMessagesReadedOnReplyNo  CreateInstanceRequestMarkIncomingMessagesReadedOnReply = "no"
)

// AllValues returns all CreateInstanceRequestMarkIncomingMessagesReadedOnReply values.
func (CreateInstanceRequestMarkIncomingMessagesReadedOnReply) AllValues() []CreateInstanceRequestMarkIncomingMessagesReadedOnReply {
	return []CreateInstanceRequestMarkIncomingMessagesReadedOnReply{
		CreateInstanceRequestMarkIncomingMessagesReadedOnReplyYes,
		CreateInstanceRequestMarkIncomingMessagesReadedOnReplyNo,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CreateInstanceRequestMarkIncomingMessagesReadedOnReply) MarshalText() ([]byte, error) {
	switch s {
	case CreateInstanceRequestMarkIncomingMessagesReadedOnReplyYes:
		return []byte(s), nil
	case CreateInstanceRequestMarkIncomingMessagesReadedOnReplyNo:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CreateInstanceRequestMarkIncomingMessagesReadedOnReply) UnmarshalText(data []byte) error {
	switch CreateInstanceRequestMarkIncomingMessagesReadedOnReply(data) {
	case CreateInstanceRequestMarkIncomingMessagesReadedOnReplyYes:
		*s = CreateInstanceRequestMarkIncomingMessagesReadedOnReplyYes
		return nil
	case CreateInstanceRequestMarkIncomingMessagesReadedOnReplyNo:
		*s = CreateInstanceRequestMarkIncomingMessagesReadedOnReplyNo
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type CreateInstanceRequestOutgoingAPIMessageWebhook string

const (
	CreateInstanceRequestOutgoingAPIMessageWebhookYes CreateInstanceRequestOutgoingAPIMessageWebhook = "yes"
	CreateInstanceRequestOutgoingAPIMessageWebhookNo  CreateInstanceRequestOutgoingAPIMessageWebhook = "no"
)

// AllValues returns all CreateInstanceRequestOutgoingAPIMessageWebhook values.
func (CreateInstanceRequestOutgoingAPIMessageWebhook) AllValues() []CreateInstanceRequestOutgoingAPIMessageWebhook {
	return []CreateInstanceRequestOutgoingAPIMessageWebhook{
		CreateInstanceRequestOutgoingAPIMessageWebhookYes,
		CreateInstanceRequestOutgoingAPIMessageWebhookNo,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CreateInstanceRequestOutgoingAPIMessageWebhook) MarshalText() ([]byte, error) {
	switch s {
	case CreateInstanceRequestOutgoingAPIMessageWebhookYes:
		return []byte(s), nil
	case CreateInstanceRequestOutgoingAPIMessageWebhookNo:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CreateInstanceRequestOutgoingAPIMessageWebhook) UnmarshalText(data []byte) error {
	switch CreateInstanceRequestOutgoingAPIMessageWebhook(data) {
	case CreateInstanceRequestOutgoingAPIMessageWebhookYes:
		*s = CreateInstanceRequestOutgoingAPIMessageWebhookYes
		return nil
	case CreateInstanceRequestOutgoingAPIMessageWebhookNo:
		*s = CreateInstanceRequestOutgoingAPIMessageWebhookNo
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type CreateInstanceRequestOutgoingMessageWebhook string

const (
	CreateInstanceRequestOutgoingMessageWebhookYes CreateInstanceRequestOutgoingMessageWebhook = "yes"
	CreateInstanceRequestOutgoingMessageWebhookNo  CreateInstanceRequestOutgoingMessageWebhook = "no"
)

// AllValues returns all CreateInstanceRequestOutgoingMessageWebhook values.
func (CreateInstanceRequestOutgoingMessageWebhook) AllValues() []CreateInstanceRequestOutgoingMessageWebhook {
	return []CreateInstanceRequestOutgoingMessageWebhook{
		CreateInstanceRequestOutgoingMessageWebhookYes,
		CreateInstanceRequestOutgoingMessageWebhookNo,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CreateInstanceRequestOutgoingMessageWebhook) MarshalText() ([]byte, error) {
	switch s {
	case CreateInstanceRequestOutgoingMessageWebhookYes:
		return []byte(s), nil
	case CreateInstanceRequestOutgoingMessageWebhookNo:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CreateInstanceRequestOutgoingMessageWebhook) UnmarshalText(data []byte) error {
	switch CreateInstanceRequestOutgoingMessageWebhook(data) {
	case CreateInstanceRequestOutgoingMessageWebhookYes:
		*s = CreateInstanceRequestOutgoingMessageWebhookYes
		return nil
	case CreateInstanceRequestOutgoingMessageWebhookNo:
		*s = CreateInstanceRequestOutgoingMessageWebhookNo
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type CreateInstanceRequestOutgoingWebhook string

const (
	CreateInstanceRequestOutgoingWebhookYes CreateInstanceRequestOutgoingWebhook = "yes"
	CreateInstanceRequestOutgoingWebhookNo  CreateInstanceRequestOutgoingWebhook = "no"
)

// AllValues returns all CreateInstanceRequestOutgoingWebhook values.
func (CreateInstanceRequestOutgoingWebhook) AllValues() []CreateInstanceRequestOutgoingWebhook {
	return []CreateInstanceRequestOutgoingWebhook{
		CreateInstanceRequestOutgoingWebhookYes,
		CreateInstanceRequestOutgoingWebhookNo,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CreateInstanceRequestOutgoingWebhook) MarshalText() ([]byte, error) {
	switch s {
	case CreateInstanceRequestOutgoingWebhookYes:
		return []byte(s), nil
	case CreateInstanceRequestOutgoingWebhookNo:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CreateInstanceRequestOutgoingWebhook) UnmarshalText(data []byte) error {
	switch CreateInstanceRequestOutgoingWebhook(data) {
	case CreateInstanceRequestOutgoingWebhookYes:
		*s = CreateInstanceRequestOutgoingWebhookYes
		return nil
	case CreateInstanceRequestOutgoingWebhookNo:
		*s = CreateInstanceRequestOutgoingWebhookNo
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type CreateInstanceRequestStateWebhook string

const (
	CreateInstanceRequestStateWebhookYes CreateInstanceRequestStateWebhook = "yes"
	CreateInstanceRequestStateWebhookNo  CreateInstanceRequestStateWebhook = "no"
)

// AllValues returns all CreateInstanceRequestStateWebhook values.
func (CreateInstanceRequestStateWebhook) AllValues() []CreateInstanceRequestStateWebhook {
	return []CreateInstanceRequestStateWebhook{
		CreateInstanceRequestStateWebhookYes,
		CreateInstanceRequestStateWebhookNo,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CreateInstanceRequestStateWebhook) MarshalText() ([]byte, error) {
	switch s {
	case CreateInstanceRequestStateWebhookYes:
		return []byte(s), nil
	case CreateInstanceRequestStateWebhookNo:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CreateInstanceRequestStateWebhook) UnmarshalText(data []byte) error {
	switch CreateInstanceRequestStateWebhook(data) {
	case CreateInstanceRequestStateWebhookYes:
		*s = CreateInstanceRequestStateWebhookYes
		return nil
	case CreateInstanceRequestStateWebhookNo:
		*s = CreateInstanceRequestStateWebhookNo
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Успешное создание инстанса или ошибка.
// В случае ошибки HTTP статус всегда 200, тип ответа
// определяется телом.
// Ref: #/components/schemas/CreateInstanceResponse
// CreateInstanceResponse represents sum type.
type CreateInstanceResponse struct {
	Type                          CreateInstanceResponseType // switch on this field
	CreateInstanceSuccessResponse CreateInstanceSuccessResponse
	ErrorResponse                 ErrorResponse
}

// CreateInstanceResponseType is oneOf type of CreateInstanceResponse.
type CreateInstanceResponseType string

// Possible values for CreateInstanceResponseType.
const (
	CreateInstanceSuccessResponseCreateInstanceResponse CreateInstanceResponseType = "CreateInstanceSuccessResponse"
	ErrorResponseCreateInstanceResponse                 CreateInstanceResponseType = "ErrorResponse"
)

// IsCreateInstanceSuccessResponse reports whether CreateInstanceResponse is CreateInstanceSuccessResponse.
func (s CreateInstanceResponse) IsCreateInstanceSuccessResponse() bool {
	return s.Type == CreateInstanceSuccessResponseCreateInstanceResponse
}

// IsErrorResponse reports whether CreateInstanceResponse is ErrorResponse.
func (s CreateInstanceResponse) IsErrorResponse() bool {
	return s.Type == ErrorResponseCreateInstanceResponse
}

// SetCreateInstanceSuccessResponse sets CreateInstanceResponse to CreateInstanceSuccessResponse.
func (s *CreateInstanceResponse) SetCreateInstanceSuccessResponse(v CreateInstanceSuccessResponse) {
	s.Type = CreateInstanceSuccessResponseCreateInstanceResponse
	s.CreateInstanceSuccessResponse = v
}

// GetCreateInstanceSuccessResponse returns CreateInstanceSuccessResponse and true boolean if CreateInstanceResponse is CreateInstanceSuccessResponse.
func (s CreateInstanceResponse) GetCreateInstanceSuccessResponse() (v CreateInstanceSuccessResponse, ok bool) {
	if !s.IsCreateInstanceSuccessResponse() {
		return v, false
	}
	return s.CreateInstanceSuccessResponse, true
}

// NewCreateInstanceSuccessResponseCreateInstanceResponse returns new CreateInstanceResponse from CreateInstanceSuccessResponse.
func NewCreateInstanceSuccessResponseCreateInstanceResponse(v CreateInstanceSuccessResponse) CreateInstanceResponse {
	var s CreateInstanceResponse
	s.SetCreateInstanceSuccessResponse(v)
	return s
}

// SetErrorResponse sets CreateInstanceResponse to ErrorResponse.
func (s *CreateInstanceResponse) SetErrorResponse(v ErrorResponse) {
	s.Type = ErrorResponseCreateInstanceResponse
	s.ErrorResponse = v
}

// GetErrorResponse returns ErrorResponse and true boolean if CreateInstanceResponse is ErrorResponse.
func (s CreateInstanceResponse) GetErrorResponse() (v ErrorResponse, ok bool) {
	if !s.IsErrorResponse() {
		return v, false
	}
	return s.ErrorResponse, true
}

// NewErrorResponseCreateInstanceResponse returns new CreateInstanceResponse from ErrorResponse.
func NewErrorResponseCreateInstanceResponse(v ErrorResponse) CreateInstanceResponse {
	var s CreateInstanceResponse
	s.SetErrorResponse(v)
	return s
}

// Ref: #/components/schemas/CreateInstanceSuccessResponse
type CreateInstanceSuccessResponse struct {
	// API токен инстанса.
	ApiTokenInstance OptString `json:"apiTokenInstance"`
	// Базовый URL API.
	ApiUrl OptURI `json:"apiUrl"`
	// Идентификатор инстанса.
	IdInstance OptFloat64 `json:"idInstance"`
	// URL для работы с медиа.
	MediaUrl OptURI `json:"mediaUrl"`
	// Тип инстанса (например, v3).
	TypeInstance OptString `json:"typeInstance"`
}

// GetApiTokenInstance returns the value of ApiTokenInstance.
func (s *CreateInstanceSuccessResponse) GetApiTokenInstance() OptString {
	return s.ApiTokenInstance
}

// GetApiUrl returns the value of ApiUrl.
func (s *CreateInstanceSuccessResponse) GetApiUrl() OptURI {
	return s.ApiUrl
}

// GetIdInstance returns the value of IdInstance.
func (s *CreateInstanceSuccessResponse) GetIdInstance() OptFloat64 {
	return s.IdInstance
}

// GetMediaUrl returns the value of MediaUrl.
func (s *CreateInstanceSuccessResponse) GetMediaUrl() OptURI {
	return s.MediaUrl
}

// GetTypeInstance returns the value of TypeInstance.
func (s *CreateInstanceSuccessResponse) GetTypeInstance() OptString {
	return s.TypeInstance
}

// SetApiTokenInstance sets the value of ApiTokenInstance.
func (s *CreateInstanceSuccessResponse) SetApiTokenInstance(val OptString) {
	s.ApiTokenInstance = val
}

// SetApiUrl sets the value of ApiUrl.
func (s *CreateInstanceSuccessResponse) SetApiUrl(val OptURI) {
	s.ApiUrl = val
}

// SetIdInstance sets the value of IdInstance.
func (s *CreateInstanceSuccessResponse) SetIdInstance(val OptFloat64) {
	s.IdInstance = val
}

// SetMediaUrl sets the value of MediaUrl.
func (s *CreateInstanceSuccessResponse) SetMediaUrl(val OptURI) {
	s.MediaUrl = val
}

// SetTypeInstance sets the value of TypeInstance.
func (s *CreateInstanceSuccessResponse) SetTypeInstance(val OptString) {
	s.TypeInstance = val
}

// Результат удаления инстанса или ошибка.
// Тип фактического ответа определяется телом.
// Ref: #/components/schemas/DeleteInstanceAccountResponse
// DeleteInstanceAccountResponse represents sum type.
type DeleteInstanceAccountResponse struct {
	Type                          DeleteInstanceAccountResponseType // switch on this field
	DeleteInstanceSuccessResponse DeleteInstanceSuccessResponse
	ErrorResponse                 ErrorResponse
}

// DeleteInstanceAccountResponseType is oneOf type of DeleteInstanceAccountResponse.
type DeleteInstanceAccountResponseType string

// Possible values for DeleteInstanceAccountResponseType.
const (
	DeleteInstanceSuccessResponseDeleteInstanceAccountResponse DeleteInstanceAccountResponseType = "DeleteInstanceSuccessResponse"
	ErrorResponseDeleteInstanceAccountResponse                 DeleteInstanceAccountResponseType = "ErrorResponse"
)

// IsDeleteInstanceSuccessResponse reports whether DeleteInstanceAccountResponse is DeleteInstanceSuccessResponse.
func (s DeleteInstanceAccountResponse) IsDeleteInstanceSuccessResponse() bool {
	return s.Type == DeleteInstanceSuccessResponseDeleteInstanceAccountResponse
}

// IsErrorResponse reports whether DeleteInstanceAccountResponse is ErrorResponse.
func (s DeleteInstanceAccountResponse) IsErrorResponse() bool {
	return s.Type == ErrorResponseDeleteInstanceAccountResponse
}

// SetDeleteInstanceSuccessResponse sets DeleteInstanceAccountResponse to DeleteInstanceSuccessResponse.
func (s *DeleteInstanceAccountResponse) SetDeleteInstanceSuccessResponse(v DeleteInstanceSuccessResponse) {
	s.Type = DeleteInstanceSuccessResponseDeleteInstanceAccountResponse
	s.DeleteInstanceSuccessResponse = v
}

// GetDeleteInstanceSuccessResponse returns DeleteInstanceSuccessResponse and true boolean if DeleteInstanceAccountResponse is DeleteInstanceSuccessResponse.
func (s DeleteInstanceAccountResponse) GetDeleteInstanceSuccessResponse() (v DeleteInstanceSuccessResponse, ok bool) {
	if !s.IsDeleteInstanceSuccessResponse() {
		return v, false
	}
	return s.DeleteInstanceSuccessResponse, true
}

// NewDeleteInstanceSuccessResponseDeleteInstanceAccountResponse returns new DeleteInstanceAccountResponse from DeleteInstanceSuccessResponse.
func NewDeleteInstanceSuccessResponseDeleteInstanceAccountResponse(v DeleteInstanceSuccessResponse) DeleteInstanceAccountResponse {
	var s DeleteInstanceAccountResponse
	s.SetDeleteInstanceSuccessResponse(v)
	return s
}

// SetErrorResponse sets DeleteInstanceAccountResponse to ErrorResponse.
func (s *DeleteInstanceAccountResponse) SetErrorResponse(v ErrorResponse) {
	s.Type = ErrorResponseDeleteInstanceAccountResponse
	s.ErrorResponse = v
}

// GetErrorResponse returns ErrorResponse and true boolean if DeleteInstanceAccountResponse is ErrorResponse.
func (s DeleteInstanceAccountResponse) GetErrorResponse() (v ErrorResponse, ok bool) {
	if !s.IsErrorResponse() {
		return v, false
	}
	return s.ErrorResponse, true
}

// NewErrorResponseDeleteInstanceAccountResponse returns new DeleteInstanceAccountResponse from ErrorResponse.
func NewErrorResponseDeleteInstanceAccountResponse(v ErrorResponse) DeleteInstanceAccountResponse {
	var s DeleteInstanceAccountResponse
	s.SetErrorResponse(v)
	return s
}

// Запрос на удаление инстанса партнерского аккаунта.
// Ref: #/components/schemas/DeleteInstanceRequest
type DeleteInstanceRequest struct {
	// Идентификатор инстанса аккаунта.
	// Значение типа uint64, 10 разрядов.
	IdInstance int64 `json:"idInstance"`
}

// GetIdInstance returns the value of IdInstance.
func (s *DeleteInstanceRequest) GetIdInstance() int64 {
	return s.IdInstance
}

// SetIdInstance sets the value of IdInstance.
func (s *DeleteInstanceRequest) SetIdInstance(val int64) {
	s.IdInstance = val
}

// Результат удаления инстанса партнерского аккаунта.
// Ref: #/components/schemas/DeleteInstanceSuccessResponse
type DeleteInstanceSuccessResponse struct {
	// Флаг удаления инстанса аккаунта.
	// true — инстанс успешно удален.
	DeleteInstanceAccount bool `json:"deleteInstanceAccount"`
}

// GetDeleteInstanceAccount returns the value of DeleteInstanceAccount.
func (s *DeleteInstanceSuccessResponse) GetDeleteInstanceAccount() bool {
	return s.DeleteInstanceAccount
}

// SetDeleteInstanceAccount sets the value of DeleteInstanceAccount.
func (s *DeleteInstanceSuccessResponse) SetDeleteInstanceAccount(val bool) {
	s.DeleteInstanceAccount = val
}

// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	// Код ошибки.
	Code int `json:"code"`
	// Описание ошибки.
	Description string `json:"description"`
}

// GetCode returns the value of Code.
func (s *ErrorResponse) GetCode() int {
	return s.Code
}

// GetDescription returns the value of Description.
func (s *ErrorResponse) GetDescription() string {
	return s.Description
}

// SetCode sets the value of Code.
func (s *ErrorResponse) SetCode(val int) {
	s.Code = val
}

// SetDescription sets the value of Description.
func (s *ErrorResponse) SetDescription(val string) {
	s.Description = val
}

type GetInstancesBadRequest struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetInstancesBadRequest) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetInstancesBadRequest) getInstancesRes() {}

// Успешный ответ (массив инстансов) или ошибка
// авторизации.
// Тип фактического ответа определяется телом.
// Ref: #/components/schemas/GetInstancesResponse
// GetInstancesResponse represents sum type.
type GetInstancesResponse struct {
	Type                 GetInstancesResponseType // switch on this field
	PartnerInstanceArray []PartnerInstance
	ErrorResponse        ErrorResponse
}

// GetInstancesResponseType is oneOf type of GetInstancesResponse.
type GetInstancesResponseType string

// Possible values for GetInstancesResponseType.
const (
	PartnerInstanceArrayGetInstancesResponse GetInstancesResponseType = "[]PartnerInstance"
	ErrorResponseGetInstancesResponse        GetInstancesResponseType = "ErrorResponse"
)

// IsPartnerInstanceArray reports whether GetInstancesResponse is []PartnerInstance.
func (s GetInstancesResponse) IsPartnerInstanceArray() bool {
	return s.Type == PartnerInstanceArrayGetInstancesResponse
}

// IsErrorResponse reports whether GetInstancesResponse is ErrorResponse.
func (s GetInstancesResponse) IsErrorResponse() bool {
	return s.Type == ErrorResponseGetInstancesResponse
}

// SetPartnerInstanceArray sets GetInstancesResponse to []PartnerInstance.
func (s *GetInstancesResponse) SetPartnerInstanceArray(v []PartnerInstance) {
	s.Type = PartnerInstanceArrayGetInstancesResponse
	s.PartnerInstanceArray = v
}

// GetPartnerInstanceArray returns []PartnerInstance and true boolean if GetInstancesResponse is []PartnerInstance.
func (s GetInstancesResponse) GetPartnerInstanceArray() (v []PartnerInstance, ok bool) {
	if !s.IsPartnerInstanceArray() {
		return v, false
	}
	return s.PartnerInstanceArray, true
}

// NewPartnerInstanceArrayGetInstancesResponse returns new GetInstancesResponse from []PartnerInstance.
func NewPartnerInstanceArrayGetInstancesResponse(v []PartnerInstance) GetInstancesResponse {
	var s GetInstancesResponse
	s.SetPartnerInstanceArray(v)
	return s
}

// SetErrorResponse sets GetInstancesResponse to ErrorResponse.
func (s *GetInstancesResponse) SetErrorResponse(v ErrorResponse) {
	s.Type = ErrorResponseGetInstancesResponse
	s.ErrorResponse = v
}

// GetErrorResponse returns ErrorResponse and true boolean if GetInstancesResponse is ErrorResponse.
func (s GetInstancesResponse) GetErrorResponse() (v ErrorResponse, ok bool) {
	if !s.IsErrorResponse() {
		return v, false
	}
	return s.ErrorResponse, true
}

// NewErrorResponseGetInstancesResponse returns new GetInstancesResponse from ErrorResponse.
func NewErrorResponseGetInstancesResponse(v ErrorResponse) GetInstancesResponse {
	var s GetInstancesResponse
	s.SetErrorResponse(v)
	return s
}

func (*GetInstancesResponse) getInstancesRes() {}

// NewOptCreateInstanceRequestIncomingWebhook returns new OptCreateInstanceRequestIncomingWebhook with value set to v.
func NewOptCreateInstanceRequestIncomingWebhook(v CreateInstanceRequestIncomingWebhook) OptCreateInstanceRequestIncomingWebhook {
	return OptCreateInstanceRequestIncomingWebhook{
		Value: v,
		Set:   true,
	}
}

// OptCreateInstanceRequestIncomingWebhook is optional CreateInstanceRequestIncomingWebhook.
type OptCreateInstanceRequestIncomingWebhook struct {
	Value CreateInstanceRequestIncomingWebhook
	Set   bool
}

// IsSet returns true if OptCreateInstanceRequestIncomingWebhook was set.
func (o OptCreateInstanceRequestIncomingWebhook) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCreateInstanceRequestIncomingWebhook) Reset() {
	var v CreateInstanceRequestIncomingWebhook
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCreateInstanceRequestIncomingWebhook) SetTo(v CreateInstanceRequestIncomingWebhook) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCreateInstanceRequestIncomingWebhook) Get() (v CreateInstanceRequestIncomingWebhook, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCreateInstanceRequestIncomingWebhook) Or(d CreateInstanceRequestIncomingWebhook) CreateInstanceRequestIncomingWebhook {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCreateInstanceRequestMarkIncomingMessagesReaded returns new OptCreateInstanceRequestMarkIncomingMessagesReaded with value set to v.
func NewOptCreateInstanceRequestMarkIncomingMessagesReaded(v CreateInstanceRequestMarkIncomingMessagesReaded) OptCreateInstanceRequestMarkIncomingMessagesReaded {
	return OptCreateInstanceRequestMarkIncomingMessagesReaded{
		Value: v,
		Set:   true,
	}
}

// OptCreateInstanceRequestMarkIncomingMessagesReaded is optional CreateInstanceRequestMarkIncomingMessagesReaded.
type OptCreateInstanceRequestMarkIncomingMessagesReaded struct {
	Value CreateInstanceRequestMarkIncomingMessagesReaded
	Set   bool
}

// IsSet returns true if OptCreateInstanceRequestMarkIncomingMessagesReaded was set.
func (o OptCreateInstanceRequestMarkIncomingMessagesReaded) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCreateInstanceRequestMarkIncomingMessagesReaded) Reset() {
	var v CreateInstanceRequestMarkIncomingMessagesReaded
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCreateInstanceRequestMarkIncomingMessagesReaded) SetTo(v CreateInstanceRequestMarkIncomingMessagesReaded) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCreateInstanceRequestMarkIncomingMessagesReaded) Get() (v CreateInstanceRequestMarkIncomingMessagesReaded, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCreateInstanceRequestMarkIncomingMessagesReaded) Or(d CreateInstanceRequestMarkIncomingMessagesReaded) CreateInstanceRequestMarkIncomingMessagesReaded {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCreateInstanceRequestMarkIncomingMessagesReadedOnReply returns new OptCreateInstanceRequestMarkIncomingMessagesReadedOnReply with value set to v.
func NewOptCreateInstanceRequestMarkIncomingMessagesReadedOnReply(v CreateInstanceRequestMarkIncomingMessagesReadedOnReply) OptCreateInstanceRequestMarkIncomingMessagesReadedOnReply {
	return OptCreateInstanceRequestMarkIncomingMessagesReadedOnReply{
		Value: v,
		Set:   true,
	}
}

// OptCreateInstanceRequestMarkIncomingMessagesReadedOnReply is optional CreateInstanceRequestMarkIncomingMessagesReadedOnReply.
type OptCreateInstanceRequestMarkIncomingMessagesReadedOnReply struct {
	Value CreateInstanceRequestMarkIncomingMessagesReadedOnReply
	Set   bool
}

// IsSet returns true if OptCreateInstanceRequestMarkIncomingMessagesReadedOnReply was set.
func (o OptCreateInstanceRequestMarkIncomingMessagesReadedOnReply) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCreateInstanceRequestMarkIncomingMessagesReadedOnReply) Reset() {
	var v CreateInstanceRequestMarkIncomingMessagesReadedOnReply
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCreateInstanceRequestMarkIncomingMessagesReadedOnReply) SetTo(v CreateInstanceRequestMarkIncomingMessagesReadedOnReply) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCreateInstanceRequestMarkIncomingMessagesReadedOnReply) Get() (v CreateInstanceRequestMarkIncomingMessagesReadedOnReply, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCreateInstanceRequestMarkIncomingMessagesReadedOnReply) Or(d CreateInstanceRequestMarkIncomingMessagesReadedOnReply) CreateInstanceRequestMarkIncomingMessagesReadedOnReply {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCreateInstanceRequestOutgoingAPIMessageWebhook returns new OptCreateInstanceRequestOutgoingAPIMessageWebhook with value set to v.
func NewOptCreateInstanceRequestOutgoingAPIMessageWebhook(v CreateInstanceRequestOutgoingAPIMessageWebhook) OptCreateInstanceRequestOutgoingAPIMessageWebhook {
	return OptCreateInstanceRequestOutgoingAPIMessageWebhook{
		Value: v,
		Set:   true,
	}
}

// OptCreateInstanceRequestOutgoingAPIMessageWebhook is optional CreateInstanceRequestOutgoingAPIMessageWebhook.
type OptCreateInstanceRequestOutgoingAPIMessageWebhook struct {
	Value CreateInstanceRequestOutgoingAPIMessageWebhook
	Set   bool
}

// IsSet returns true if OptCreateInstanceRequestOutgoingAPIMessageWebhook was set.
func (o OptCreateInstanceRequestOutgoingAPIMessageWebhook) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCreateInstanceRequestOutgoingAPIMessageWebhook) Reset() {
	var v CreateInstanceRequestOutgoingAPIMessageWebhook
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCreateInstanceRequestOutgoingAPIMessageWebhook) SetTo(v CreateInstanceRequestOutgoingAPIMessageWebhook) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCreateInstanceRequestOutgoingAPIMessageWebhook) Get() (v CreateInstanceRequestOutgoingAPIMessageWebhook, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCreateInstanceRequestOutgoingAPIMessageWebhook) Or(d CreateInstanceRequestOutgoingAPIMessageWebhook) CreateInstanceRequestOutgoingAPIMessageWebhook {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCreateInstanceRequestOutgoingMessageWebhook returns new OptCreateInstanceRequestOutgoingMessageWebhook with value set to v.
func NewOptCreateInstanceRequestOutgoingMessageWebhook(v CreateInstanceRequestOutgoingMessageWebhook) OptCreateInstanceRequestOutgoingMessageWebhook {
	return OptCreateInstanceRequestOutgoingMessageWebhook{
		Value: v,
		Set:   true,
	}
}

// OptCreateInstanceRequestOutgoingMessageWebhook is optional CreateInstanceRequestOutgoingMessageWebhook.
type OptCreateInstanceRequestOutgoingMessageWebhook struct {
	Value CreateInstanceRequestOutgoingMessageWebhook
	Set   bool
}

// IsSet returns true if OptCreateInstanceRequestOutgoingMessageWebhook was set.
func (o OptCreateInstanceRequestOutgoingMessageWebhook) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCreateInstanceRequestOutgoingMessageWebhook) Reset() {
	var v CreateInstanceRequestOutgoingMessageWebhook
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCreateInstanceRequestOutgoingMessageWebhook) SetTo(v CreateInstanceRequestOutgoingMessageWebhook) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCreateInstanceRequestOutgoingMessageWebhook) Get() (v CreateInstanceRequestOutgoingMessageWebhook, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCreateInstanceRequestOutgoingMessageWebhook) Or(d CreateInstanceRequestOutgoingMessageWebhook) CreateInstanceRequestOutgoingMessageWebhook {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCreateInstanceRequestOutgoingWebhook returns new OptCreateInstanceRequestOutgoingWebhook with value set to v.
func NewOptCreateInstanceRequestOutgoingWebhook(v CreateInstanceRequestOutgoingWebhook) OptCreateInstanceRequestOutgoingWebhook {
	return OptCreateInstanceRequestOutgoingWebhook{
		Value: v,
		Set:   true,
	}
}

// OptCreateInstanceRequestOutgoingWebhook is optional CreateInstanceRequestOutgoingWebhook.
type OptCreateInstanceRequestOutgoingWebhook struct {
	Value CreateInstanceRequestOutgoingWebhook
	Set   bool
}

// IsSet returns true if OptCreateInstanceRequestOutgoingWebhook was set.
func (o OptCreateInstanceRequestOutgoingWebhook) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCreateInstanceRequestOutgoingWebhook) Reset() {
	var v CreateInstanceRequestOutgoingWebhook
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCreateInstanceRequestOutgoingWebhook) SetTo(v CreateInstanceRequestOutgoingWebhook) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCreateInstanceRequestOutgoingWebhook) Get() (v CreateInstanceRequestOutgoingWebhook, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCreateInstanceRequestOutgoingWebhook) Or(d CreateInstanceRequestOutgoingWebhook) CreateInstanceRequestOutgoingWebhook {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCreateInstanceRequestStateWebhook returns new OptCreateInstanceRequestStateWebhook with value set to v.
func NewOptCreateInstanceRequestStateWebhook(v CreateInstanceRequestStateWebhook) OptCreateInstanceRequestStateWebhook {
	return OptCreateInstanceRequestStateWebhook{
		Value: v,
		Set:   true,
	}
}

// OptCreateInstanceRequestStateWebhook is optional CreateInstanceRequestStateWebhook.
type OptCreateInstanceRequestStateWebhook struct {
	Value CreateInstanceRequestStateWebhook
	Set   bool
}

// IsSet returns true if OptCreateInstanceRequestStateWebhook was set.
func (o OptCreateInstanceRequestStateWebhook) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCreateInstanceRequestStateWebhook) Reset() {
	var v CreateInstanceRequestStateWebhook
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCreateInstanceRequestStateWebhook) SetTo(v CreateInstanceRequestStateWebhook) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCreateInstanceRequestStateWebhook) Get() (v CreateInstanceRequestStateWebhook, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCreateInstanceRequestStateWebhook) Or(d CreateInstanceRequestStateWebhook) CreateInstanceRequestStateWebhook {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptFloat64 returns new OptFloat64 with value set to v.
func NewOptFloat64(v float64) OptFloat64 {
	return OptFloat64{
		Value: v,
		Set:   true,
	}
}

// OptFloat64 is optional float64.
type OptFloat64 struct {
	Value float64
	Set   bool
}

// IsSet returns true if OptFloat64 was set.
func (o OptFloat64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptFloat64) Reset() {
	var v float64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptFloat64) SetTo(v float64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptFloat64) Get() (v float64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptFloat64) Or(d float64) float64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptURI returns new OptURI with value set to v.
func NewOptURI(v url.URL) OptURI {
	return OptURI{
		Value: v,
		Set:   true,
	}
}

// OptURI is optional url.URL.
type OptURI struct {
	Value url.URL
	Set   bool
}

// IsSet returns true if OptURI was set.
func (o OptURI) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptURI) Reset() {
	var v url.URL
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptURI) SetTo(v url.URL) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptURI) Get() (v url.URL, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptURI) Or(d url.URL) url.URL {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Инстанс партнерского аккаунта.
// Ref: #/components/schemas/PartnerInstance
type PartnerInstance struct {
	// Идентификатор инстанса аккаунта.
	// Значение uint64, 10 разрядов.
	IdInstance int64 `json:"idInstance"`
	// Название инстанса.
	Name string `json:"name"`
	// Тип инстанса:
	// v3 — мессенджер MAX
	// whatsapp — мессенджер WhatsApp.
	TypeInstance string `json:"typeInstance"`
	// Не используется.
	TypeAccount OptString `json:"typeAccount"`
	// Не используется.
	PartnerUserUiid OptString `json:"partnerUserUiid"`
	// Время создания инстанса.
	TimeCreated time.Time `json:"timeCreated"`
	// Время удаления инстанса.
	TimeDeleted OptDateTime `json:"timeDeleted"`
	// API-токен инстанса.
	ApiTokenInstance string `json:"apiTokenInstance"`
	// Состояние инстанса:
	// true — удален
	// false — активен.
	Deleted bool `json:"deleted"`
	// Подключенный тариф.
	Tariff string `json:"tariff"`
	// Признак бесплатного инстанса.
	IsFree bool `json:"isFree"`
	// Признак партнерского тарифа.
	IsPartner bool `json:"isPartner"`
	// Дата окончания действия инстанса.
	ExpirationDate time.Time `json:"expirationDate"`
	// Признак истечения срока действия.
	IsExpired bool `json:"isExpired"`
}

// GetIdInstance returns the value of IdInstance.
func (s *PartnerInstance) GetIdInstance() int64 {
	return s.IdInstance
}

// GetName returns the value of Name.
func (s *PartnerInstance) GetName() string {
	return s.Name
}

// GetTypeInstance returns the value of TypeInstance.
func (s *PartnerInstance) GetTypeInstance() string {
	return s.TypeInstance
}

// GetTypeAccount returns the value of TypeAccount.
func (s *PartnerInstance) GetTypeAccount() OptString {
	return s.TypeAccount
}

// GetPartnerUserUiid returns the value of PartnerUserUiid.
func (s *PartnerInstance) GetPartnerUserUiid() OptString {
	return s.PartnerUserUiid
}

// GetTimeCreated returns the value of TimeCreated.
func (s *PartnerInstance) GetTimeCreated() time.Time {
	return s.TimeCreated
}

// GetTimeDeleted returns the value of TimeDeleted.
func (s *PartnerInstance) GetTimeDeleted() OptDateTime {
	return s.TimeDeleted
}

// GetApiTokenInstance returns the value of ApiTokenInstance.
func (s *PartnerInstance) GetApiTokenInstance() string {
	return s.ApiTokenInstance
}

// GetDeleted returns the value of Deleted.
func (s *PartnerInstance) GetDeleted() bool {
	return s.Deleted
}

// GetTariff returns the value of Tariff.
func (s *PartnerInstance) GetTariff() string {
	return s.Tariff
}

// GetIsFree returns the value of IsFree.
func (s *PartnerInstance) GetIsFree() bool {
	return s.IsFree
}

// GetIsPartner returns the value of IsPartner.
func (s *PartnerInstance) GetIsPartner() bool {
	return s.IsPartner
}

// GetExpirationDate returns the value of ExpirationDate.
func (s *PartnerInstance) GetExpirationDate() time.Time {
	return s.ExpirationDate
}

// GetIsExpired returns the value of IsExpired.
func (s *PartnerInstance) GetIsExpired() bool {
	return s.IsExpired
}

// SetIdInstance sets the value of IdInstance.
func (s *PartnerInstance) SetIdInstance(val int64) {
	s.IdInstance = val
}

// SetName sets the value of Name.
func (s *PartnerInstance) SetName(val string) {
	s.Name = val
}

// SetTypeInstance sets the value of TypeInstance.
func (s *PartnerInstance) SetTypeInstance(val string) {
	s.TypeInstance = val
}

// SetTypeAccount sets the value of TypeAccount.
func (s *PartnerInstance) SetTypeAccount(val OptString) {
	s.TypeAccount = val
}

// SetPartnerUserUiid sets the value of PartnerUserUiid.
func (s *PartnerInstance) SetPartnerUserUiid(val OptString) {
	s.PartnerUserUiid = val
}

// SetTimeCreated sets the value of TimeCreated.
func (s *PartnerInstance) SetTimeCreated(val time.Time) {
	s.TimeCreated = val
}

// SetTimeDeleted sets the value of TimeDeleted.
func (s *PartnerInstance) SetTimeDeleted(val OptDateTime) {
	s.TimeDeleted = val
}

// SetApiTokenInstance sets the value of ApiTokenInstance.
func (s *PartnerInstance) SetApiTokenInstance(val string) {
	s.ApiTokenInstance = val
}

// SetDeleted sets the value of Deleted.
func (s *PartnerInstance) SetDeleted(val bool) {
	s.Deleted = val
}

// SetTariff sets the value of Tariff.
func (s *PartnerInstance) SetTariff(val string) {
	s.Tariff = val
}

// SetIsFree sets the value of IsFree.
func (s *PartnerInstance) SetIsFree(val bool) {
	s.IsFree = val
}

// SetIsPartner sets the value of IsPartner.
func (s *PartnerInstance) SetIsPartner(val bool) {
	s.IsPartner = val
}

// SetExpirationDate sets the value of ExpirationDate.
func (s *PartnerInstance) SetExpirationDate(val time.Time) {
	s.ExpirationDate = val
}

// SetIsExpired sets the value of IsExpired.
func (s *PartnerInstance) SetIsExpired(val bool) {
	s.IsExpired = val
}
