// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// CreateInstanceParams is parameters of createInstance operation.
type CreateInstanceParams struct {
	PartnerToken string
}

func unpackCreateInstanceParams(packed middleware.Parameters) (params CreateInstanceParams) {
	{
		key := middleware.ParameterKey{
			Name: "partnerToken",
			In:   "path",
		}
		params.PartnerToken = packed[key].(string)
	}
	return params
}

func decodeCreateInstanceParams(args [1]string, argsEscaped bool, r *http.Request) (params CreateInstanceParams, _ error) {
	// Decode path: partnerToken.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "partnerToken",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.PartnerToken = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "partnerToken",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// DeleteInstanceAccountParams is parameters of deleteInstanceAccount operation.
type DeleteInstanceAccountParams struct {
	// Партнерский API-токен.
	PartnerToken string
}

func unpackDeleteInstanceAccountParams(packed middleware.Parameters) (params DeleteInstanceAccountParams) {
	{
		key := middleware.ParameterKey{
			Name: "partnerToken",
			In:   "path",
		}
		params.PartnerToken = packed[key].(string)
	}
	return params
}

func decodeDeleteInstanceAccountParams(args [1]string, argsEscaped bool, r *http.Request) (params DeleteInstanceAccountParams, _ error) {
	// Decode path: partnerToken.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "partnerToken",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.PartnerToken = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "partnerToken",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetInstancesParams is parameters of getInstances operation.
type GetInstancesParams struct {
	// Партнерский API-токен.
	PartnerToken string
}

func unpackGetInstancesParams(packed middleware.Parameters) (params GetInstancesParams) {
	{
		key := middleware.ParameterKey{
			Name: "partnerToken",
			In:   "path",
		}
		params.PartnerToken = packed[key].(string)
	}
	return params
}

func decodeGetInstancesParams(args [1]string, argsEscaped bool, r *http.Request) (params GetInstancesParams, _ error) {
	// Decode path: partnerToken.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "partnerToken",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.PartnerToken = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "partnerToken",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
