// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateInstanceOperation        OperationName = "CreateInstance"
	DeleteInstanceAccountOperation OperationName = "DeleteInstanceAccount"
	GetInstancesOperation          OperationName = "GetInstances"
)
