// Code generated by ogen, DO NOT EDIT.

package api

import (
	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/validate"
)

func (s *CreateInstanceRequest) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.DelaySendMessagesMilliseconds.Get(); ok {
			if err := func() error {
				if err := (validate.Int{
					MinSet:        true,
					Min:           0,
					MaxSet:        false,
					Max:           0,
					MinExclusive:  false,
					MaxExclusive:  false,
					MultipleOfSet: false,
					MultipleOf:    0,
					Pattern:       nil,
				}).Validate(int64(value)); err != nil {
					return errors.Wrap(err, "int")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "delaySendMessagesMilliseconds",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.MarkIncomingMessagesReaded.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "markIncomingMessagesReaded",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.MarkIncomingMessagesReadedOnReply.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "markIncomingMessagesReadedOnReply",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.OutgoingAPIMessageWebhook.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "outgoingAPIMessageWebhook",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.OutgoingWebhook.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "outgoingWebhook",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.OutgoingMessageWebhook.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "outgoingMessageWebhook",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.IncomingWebhook.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "incomingWebhook",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.StateWebhook.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "stateWebhook",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s CreateInstanceRequestIncomingWebhook) Validate() error {
	switch s {
	case "yes":
		return nil
	case "no":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s CreateInstanceRequestMarkIncomingMessagesReaded) Validate() error {
	switch s {
	case "yes":
		return nil
	case "no":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s CreateInstanceRequestMarkIncomingMessagesReadedOnReply) Validate() error {
	switch s {
	case "yes":
		return nil
	case "no":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s CreateInstanceRequestOutgoingAPIMessageWebhook) Validate() error {
	switch s {
	case "yes":
		return nil
	case "no":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s CreateInstanceRequestOutgoingMessageWebhook) Validate() error {
	switch s {
	case "yes":
		return nil
	case "no":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s CreateInstanceRequestOutgoingWebhook) Validate() error {
	switch s {
	case "yes":
		return nil
	case "no":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s CreateInstanceRequestStateWebhook) Validate() error {
	switch s {
	case "yes":
		return nil
	case "no":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s CreateInstanceResponse) Validate() error {
	switch s.Type {
	case CreateInstanceSuccessResponseCreateInstanceResponse:
		if err := s.CreateInstanceSuccessResponse.Validate(); err != nil {
			return err
		}
		return nil
	case ErrorResponseCreateInstanceResponse:
		return nil // no validation needed
	default:
		return errors.Errorf("invalid type %q", s.Type)
	}
}

func (s *CreateInstanceSuccessResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.IdInstance.Get(); ok {
			if err := func() error {
				if err := (validate.Float{}).Validate(float64(value)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "idInstance",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s GetInstancesResponse) Validate() error {
	switch s.Type {
	case PartnerInstanceArrayGetInstancesResponse:
		if s.PartnerInstanceArray == nil {
			return errors.New("nil is invalid value")
		}
		return nil
	case ErrorResponseGetInstancesResponse:
		return nil // no validation needed
	default:
		return errors.Errorf("invalid type %q", s.Type)
	}
}
