// Package gen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package gen

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for CreateInstanceRequestIncomingWebhook.
const (
	CreateInstanceRequestIncomingWebhookNo  CreateInstanceRequestIncomingWebhook = "no"
	CreateInstanceRequestIncomingWebhookYes CreateInstanceRequestIncomingWebhook = "yes"
)

// Defines values for CreateInstanceRequestMarkIncomingMessagesReaded.
const (
	CreateInstanceRequestMarkIncomingMessagesReadedNo  CreateInstanceRequestMarkIncomingMessagesReaded = "no"
	CreateInstanceRequestMarkIncomingMessagesReadedYes CreateInstanceRequestMarkIncomingMessagesReaded = "yes"
)

// Defines values for CreateInstanceRequestMarkIncomingMessagesReadedOnReply.
const (
	CreateInstanceRequestMarkIncomingMessagesReadedOnReplyNo  CreateInstanceRequestMarkIncomingMessagesReadedOnReply = "no"
	CreateInstanceRequestMarkIncomingMessagesReadedOnReplyYes CreateInstanceRequestMarkIncomingMessagesReadedOnReply = "yes"
)

// Defines values for CreateInstanceRequestOutgoingAPIMessageWebhook.
const (
	CreateInstanceRequestOutgoingAPIMessageWebhookNo  CreateInstanceRequestOutgoingAPIMessageWebhook = "no"
	CreateInstanceRequestOutgoingAPIMessageWebhookYes CreateInstanceRequestOutgoingAPIMessageWebhook = "yes"
)

// Defines values for CreateInstanceRequestOutgoingMessageWebhook.
const (
	CreateInstanceRequestOutgoingMessageWebhookNo  CreateInstanceRequestOutgoingMessageWebhook = "no"
	CreateInstanceRequestOutgoingMessageWebhookYes CreateInstanceRequestOutgoingMessageWebhook = "yes"
)

// Defines values for CreateInstanceRequestOutgoingWebhook.
const (
	CreateInstanceRequestOutgoingWebhookNo  CreateInstanceRequestOutgoingWebhook = "no"
	CreateInstanceRequestOutgoingWebhookYes CreateInstanceRequestOutgoingWebhook = "yes"
)

// Defines values for CreateInstanceRequestStateWebhook.
const (
	No  CreateInstanceRequestStateWebhook = "no"
	Yes CreateInstanceRequestStateWebhook = "yes"
)

// CreateInstanceRequest defines model for CreateInstanceRequest.
type CreateInstanceRequest struct {
	DelaySendMessagesMilliseconds     *int                                                    `json:"delaySendMessagesMilliseconds,omitempty"`
	IncomingWebhook                   *CreateInstanceRequestIncomingWebhook                   `json:"incomingWebhook,omitempty"`
	MarkIncomingMessagesReaded        *CreateInstanceRequestMarkIncomingMessagesReaded        `json:"markIncomingMessagesReaded,omitempty"`
	MarkIncomingMessagesReadedOnReply *CreateInstanceRequestMarkIncomingMessagesReadedOnReply `json:"markIncomingMessagesReadedOnReply,omitempty"`

	// Name Название инстанса
	Name                      *string                                         `json:"name,omitempty"`
	OutgoingAPIMessageWebhook *CreateInstanceRequestOutgoingAPIMessageWebhook `json:"outgoingAPIMessageWebhook,omitempty"`
	OutgoingMessageWebhook    *CreateInstanceRequestOutgoingMessageWebhook    `json:"outgoingMessageWebhook,omitempty"`
	OutgoingWebhook           *CreateInstanceRequestOutgoingWebhook           `json:"outgoingWebhook,omitempty"`
	StateWebhook              *CreateInstanceRequestStateWebhook              `json:"stateWebhook,omitempty"`

	// WebhookUrl URL webhook
	WebhookUrl *string `json:"webhookUrl,omitempty"`

	// WebhookUrlToken Токен для валидации webhook
	WebhookUrlToken *string `json:"webhookUrlToken,omitempty"`
}

// CreateInstanceRequestIncomingWebhook defines model for CreateInstanceRequest.IncomingWebhook.
type CreateInstanceRequestIncomingWebhook string

// CreateInstanceRequestMarkIncomingMessagesReaded defines model for CreateInstanceRequest.MarkIncomingMessagesReaded.
type CreateInstanceRequestMarkIncomingMessagesReaded string

// CreateInstanceRequestMarkIncomingMessagesReadedOnReply defines model for CreateInstanceRequest.MarkIncomingMessagesReadedOnReply.
type CreateInstanceRequestMarkIncomingMessagesReadedOnReply string

// CreateInstanceRequestOutgoingAPIMessageWebhook defines model for CreateInstanceRequest.OutgoingAPIMessageWebhook.
type CreateInstanceRequestOutgoingAPIMessageWebhook string

// CreateInstanceRequestOutgoingMessageWebhook defines model for CreateInstanceRequest.OutgoingMessageWebhook.
type CreateInstanceRequestOutgoingMessageWebhook string

// CreateInstanceRequestOutgoingWebhook defines model for CreateInstanceRequest.OutgoingWebhook.
type CreateInstanceRequestOutgoingWebhook string

// CreateInstanceRequestStateWebhook defines model for CreateInstanceRequest.StateWebhook.
type CreateInstanceRequestStateWebhook string

// CreateInstanceSuccessResponse defines model for CreateInstanceSuccessResponse.
type CreateInstanceSuccessResponse struct {
	// ApiTokenInstance API токен инстанса
	ApiTokenInstance *string `json:"apiTokenInstance,omitempty"`

	// ApiUrl Базовый URL API
	ApiUrl *string `json:"apiUrl,omitempty"`

	// IdInstance Идентификатор инстанса
	IdInstance *float32 `json:"idInstance,omitempty"`

	// MediaUrl URL для работы с медиа
	MediaUrl *string `json:"mediaUrl,omitempty"`

	// TypeInstance Тип инстанса (например, v3)
	TypeInstance *string `json:"typeInstance,omitempty"`
}

// DeleteInstanceRequest Запрос на удаление инстанса партнерского аккаунта
type DeleteInstanceRequest struct {
	// IdInstance Идентификатор инстанса аккаунта.
	// Значение типа uint64, 10 разрядов.
	IdInstance int64 `json:"idInstance"`
}

// DeleteInstanceSuccessResponse Результат удаления инстанса партнерского аккаунта
type DeleteInstanceSuccessResponse struct {
	// DeleteInstanceAccount Флаг удаления инстанса аккаунта.
	// true — инстанс успешно удален.
	DeleteInstanceAccount bool `json:"deleteInstanceAccount"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Code Код ошибки
	Code int `json:"code"`

	// Description Описание ошибки
	Description string `json:"description"`
}

// PartnerInstance Инстанс партнерского аккаунта
type PartnerInstance struct {
	// ApiTokenInstance API-токен инстанса
	ApiTokenInstance string `json:"apiTokenInstance"`

	// Deleted Состояние инстанса:
	// true — удален
	// false — активен
	Deleted bool `json:"deleted"`

	// ExpirationDate Дата окончания действия инстанса
	ExpirationDate time.Time `json:"expirationDate"`

	// IdInstance Идентификатор инстанса аккаунта.
	// Значение uint64, 10 разрядов.
	IdInstance int64 `json:"idInstance"`

	// IsExpired Признак истечения срока действия
	IsExpired bool `json:"isExpired"`

	// IsFree Признак бесплатного инстанса
	IsFree bool `json:"isFree"`

	// IsPartner Признак партнерского тарифа
	IsPartner bool `json:"isPartner"`

	// Name Название инстанса
	Name string `json:"name"`

	// PartnerUserUiid Не используется
	PartnerUserUiid *string `json:"partnerUserUiid,omitempty"`

	// Tariff Подключенный тариф
	Tariff string `json:"tariff"`

	// TimeCreated Время создания инстанса
	TimeCreated time.Time `json:"timeCreated"`

	// TimeDeleted Время удаления инстанса
	TimeDeleted *time.Time `json:"timeDeleted,omitempty"`

	// TypeAccount Не используется
	TypeAccount *string `json:"typeAccount,omitempty"`

	// TypeInstance Тип инстанса:
	// v3 — мессенджер MAX
	// whatsapp — мессенджер WhatsApp
	TypeInstance string `json:"typeInstance"`
}

// DeleteInstanceAccountJSONRequestBody defines body for DeleteInstanceAccount for application/json ContentType.
type DeleteInstanceAccountJSONRequestBody = DeleteInstanceRequest

// CreateInstanceJSONRequestBody defines body for CreateInstance for application/json ContentType.
type CreateInstanceJSONRequestBody = CreateInstanceRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// DeleteInstanceAccountWithBody request with any body
	DeleteInstanceAccountWithBody(ctx context.Context, partnerToken string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	DeleteInstanceAccount(ctx context.Context, partnerToken string, body DeleteInstanceAccountJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetInstances request
	GetInstances(ctx context.Context, partnerToken string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateInstanceWithBody request with any body
	CreateInstanceWithBody(ctx context.Context, partnerToken string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateInstance(ctx context.Context, partnerToken string, body CreateInstanceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) DeleteInstanceAccountWithBody(ctx context.Context, partnerToken string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteInstanceAccountRequestWithBody(c.Server, partnerToken, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteInstanceAccount(ctx context.Context, partnerToken string, body DeleteInstanceAccountJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteInstanceAccountRequest(c.Server, partnerToken, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetInstances(ctx context.Context, partnerToken string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetInstancesRequest(c.Server, partnerToken)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateInstanceWithBody(ctx context.Context, partnerToken string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateInstanceRequestWithBody(c.Server, partnerToken, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateInstance(ctx context.Context, partnerToken string, body CreateInstanceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateInstanceRequest(c.Server, partnerToken, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewDeleteInstanceAccountRequest calls the generic DeleteInstanceAccount builder with application/json body
func NewDeleteInstanceAccountRequest(server string, partnerToken string, body DeleteInstanceAccountJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewDeleteInstanceAccountRequestWithBody(server, partnerToken, "application/json", bodyReader)
}

// NewDeleteInstanceAccountRequestWithBody generates requests for DeleteInstanceAccount with any type of body
func NewDeleteInstanceAccountRequestWithBody(server string, partnerToken string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "partnerToken", runtime.ParamLocationPath, partnerToken)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/partner/deleteInstanceAccount/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetInstancesRequest generates requests for GetInstances
func NewGetInstancesRequest(server string, partnerToken string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "partnerToken", runtime.ParamLocationPath, partnerToken)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/partner/getInstances/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateInstanceRequest calls the generic CreateInstance builder with application/json body
func NewCreateInstanceRequest(server string, partnerToken string, body CreateInstanceJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateInstanceRequestWithBody(server, partnerToken, "application/json", bodyReader)
}

// NewCreateInstanceRequestWithBody generates requests for CreateInstance with any type of body
func NewCreateInstanceRequestWithBody(server string, partnerToken string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "partnerToken", runtime.ParamLocationPath, partnerToken)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/partners/createInstance/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// DeleteInstanceAccountWithBodyWithResponse request with any body
	DeleteInstanceAccountWithBodyWithResponse(ctx context.Context, partnerToken string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DeleteInstanceAccountResponse, error)

	DeleteInstanceAccountWithResponse(ctx context.Context, partnerToken string, body DeleteInstanceAccountJSONRequestBody, reqEditors ...RequestEditorFn) (*DeleteInstanceAccountResponse, error)

	// GetInstancesWithResponse request
	GetInstancesWithResponse(ctx context.Context, partnerToken string, reqEditors ...RequestEditorFn) (*GetInstancesResponse, error)

	// CreateInstanceWithBodyWithResponse request with any body
	CreateInstanceWithBodyWithResponse(ctx context.Context, partnerToken string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateInstanceResponse, error)

	CreateInstanceWithResponse(ctx context.Context, partnerToken string, body CreateInstanceJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateInstanceResponse, error)
}

type DeleteInstanceAccountResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		union json.RawMessage
	}
}

// Status returns HTTPResponse.Status
func (r DeleteInstanceAccountResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteInstanceAccountResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetInstancesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		union json.RawMessage
	}
}
type GetInstances2000 = []PartnerInstance

// Status returns HTTPResponse.Status
func (r GetInstancesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetInstancesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateInstanceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		union json.RawMessage
	}
}

// Status returns HTTPResponse.Status
func (r CreateInstanceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateInstanceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// DeleteInstanceAccountWithBodyWithResponse request with arbitrary body returning *DeleteInstanceAccountResponse
func (c *ClientWithResponses) DeleteInstanceAccountWithBodyWithResponse(ctx context.Context, partnerToken string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DeleteInstanceAccountResponse, error) {
	rsp, err := c.DeleteInstanceAccountWithBody(ctx, partnerToken, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteInstanceAccountResponse(rsp)
}

func (c *ClientWithResponses) DeleteInstanceAccountWithResponse(ctx context.Context, partnerToken string, body DeleteInstanceAccountJSONRequestBody, reqEditors ...RequestEditorFn) (*DeleteInstanceAccountResponse, error) {
	rsp, err := c.DeleteInstanceAccount(ctx, partnerToken, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteInstanceAccountResponse(rsp)
}

// GetInstancesWithResponse request returning *GetInstancesResponse
func (c *ClientWithResponses) GetInstancesWithResponse(ctx context.Context, partnerToken string, reqEditors ...RequestEditorFn) (*GetInstancesResponse, error) {
	rsp, err := c.GetInstances(ctx, partnerToken, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetInstancesResponse(rsp)
}

// CreateInstanceWithBodyWithResponse request with arbitrary body returning *CreateInstanceResponse
func (c *ClientWithResponses) CreateInstanceWithBodyWithResponse(ctx context.Context, partnerToken string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateInstanceResponse, error) {
	rsp, err := c.CreateInstanceWithBody(ctx, partnerToken, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateInstanceResponse(rsp)
}

func (c *ClientWithResponses) CreateInstanceWithResponse(ctx context.Context, partnerToken string, body CreateInstanceJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateInstanceResponse, error) {
	rsp, err := c.CreateInstance(ctx, partnerToken, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateInstanceResponse(rsp)
}

// ParseDeleteInstanceAccountResponse parses an HTTP response from a DeleteInstanceAccountWithResponse call
func ParseDeleteInstanceAccountResponse(rsp *http.Response) (*DeleteInstanceAccountResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteInstanceAccountResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			union json.RawMessage
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetInstancesResponse parses an HTTP response from a GetInstancesWithResponse call
func ParseGetInstancesResponse(rsp *http.Response) (*GetInstancesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetInstancesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			union json.RawMessage
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseCreateInstanceResponse parses an HTTP response from a CreateInstanceWithResponse call
func ParseCreateInstanceResponse(rsp *http.Response) (*CreateInstanceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateInstanceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			union json.RawMessage
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xZ7W4bx9W+lcW87w8boMSluPriP7V2UgG1IygyUsASiuFySG1Mzm52l0pUgwBFtU2K",
	"BDUaBEhRtEkd9wJoWaxo0aRu4cwt9EqKM7tc7sfwQ5Zcx9APmpyPM+c55znPmXlKTLvh2Jxx3yOlp8Qz",
	"D1mDyo+/dBn12Tb3fMpNtss+azLPxx8c13aY61tMDquwOj3+mPHKA+Z5tMa8B1a9bnnMtHlFDmhY3Go0",
	"G6Sk54h/7DBSIhb3WY25pJUjFjfthsVrn7DyoW0/wQmM4+jH5Jh5JEe4TQ6iiZ7vWryG8xrUfbIdzh3v",
	"vMtohVVuYYmP+C5z6scLr8RpgwW+8EzXcnzL5qRE4B/QhQs4gy4MoQ89DfowFCeig1+IE+gSxVJ206/Z",
	"Fq9t7WyHNl3XM+MVbjj9uvM8n/rX3uzzYPwjt55136PdX2vh7yRHqrbboD4pkaZrkZkr7dlPGFeg8ROM",
	"4BJ6MNTgHAbimSaRGUAfzqEr/gh96Mf2S23Qir6xy58y08ctkwnycdM0meftMs+xuceyiUIdS5o2npA1",
	"cWtnWxOdiZkLhAt1LKXz4C8y9kZwJr6G1xr6cmtnewE/WpXp9sFf4RwtEx3oi99DHy6hi/aK9gxbebNR",
	"DlK9wSoWnQp1CIpoQxdewkh0xNeaONHgDfTgHPpyyXnG4xczzP8J+nCVMVW7A0PowpVoQx93E+2cdlS8",
	"u1gM3GN1piTJ1NbfhzuM8EhD6GriFMMOBuhPJTlocAVd0RYdGKJN4gQuYQSvYKRBFy6l608lFOiYZKTd",
	"EoaZjZb3OXyP1osvI7NxHbRUa1rcXzNyWkEPMLwQbfEMzjEEl/c5yRH2BW04dUZKxYIe/oshKmeTbIVo",
	"5YjLPmtaLhL74/jRDubCoUjJlDP+CT24EKcwEN/gAUUnhQuyxO3hUklYt2WadpOrguVfMIAuvFrElixC",
	"vttk2n/a36UGa+JUnMAV9MRXMIRRYu0UPrhC5NuybdcZ5Rkg1GdRYXLfdW13Oi2adkWFzN9gBOcajMRX",
	"0IeXcAl9opIPiVmZRX6AK+ijo8Y5plwult/xE0rDkjuojrdDXZ8zd2bGxXF4+/BZqIAszS4gEcikUF0x",
	"NlbZhl411o2VzWJ5s7haXV+vrG+YawZbX6tSo1wxWdkorFNjc3ODGirGDcKgojj1c+Q6ySzPpjBcKRas",
	"8XDc51Va98Ig7sKlpJiz4Jf4EeSobKDiCMdyKRpyj/oqRL6TnNfVpKdGMBRfBiGCKYbs+FqaeabMuYQT",
	"V/SVlSV9bUnf3CtslIqbJcOIl6kK9dmSbzXYO6y0C7H0OyLnHLG8++hsZQT8KCvqhayulxomouhAb2wV",
	"1voTrIhoe8btC+FseR+4jM3f+SX0JPcNpBOH43ybAeyMLcN8n7/rtDyXhaYtce3Op92bNBeTOB1HmjaB",
	"VxWSTnC2Rx5zH1lWRblrTyIJVzDCqimrZ090xEkSM6KUZ9S1qlWV55Ds4RIG4s9heAylbJ24KrH2ztbu",
	"3sP7u79dKSp3sRoskOaqA3wr2tCDNzL6YAQXknaG18j04vUzHb+/N5UoYxbNq/cJi3RdLyzJvz1dL8m/",
	"xS06dmboj5uB/DYavLTPj4oB4aMCPxEn0gfn8G9MHu3B1m/2+eeH1Peo40wf9gmO2HKcJKORo+LcWh/j",
	"4jDhUgdJhlUuW4snpTCK84ig4rSRqU5xDs3qi5a8IqnaCk/+HSGRKmluJGsf7t6//3AJ+8tx75tgJ6wD",
	"8oi+dNhkdGh12DseMdcLNi8s68u6vC1wGKeORUqkuKwvo6Md6h9KuZIP2SSvlIr5p+HP0o0tqQttZes0",
	"OafsoLAbHErui0pc1DvO18vDbMHspZ2BFXSfw7fo14E4leIgph1HcKndecRp0z+0Xet3rJLTHtq+VrWb",
	"vHJXkz4+k3ic4VriTzhbdLRf7e3taCu6vs9RjHegBwMYwZuEJtXuoOjMaTEP3A3qM+pAGTPbFVJKtTnj",
	"RJb8TRvMZ65HSo8VLJsuSH14rSU1I4YjDkYUx6lQInGoSDxzgpoVXBoidOksOwgGM8//hV05DuQ+91nA",
	"OtRx6pYpT5X/1AsEfJS1yS52UrZa8e3+32VVUiL/l59cYubDG8y8ujNvJTMf7ZdfBN2JjNsVXV/cUDmD",
	"2/4HiL68QG02GtQ9Vuj+IQYRRu7rQNthQtF6k02aIEM3Uh0NiSJLUpYXNLQz95nR58V3nNKLSoe0cqQZ",
	"i+/Udj9E8SpT6SzQpVL5hNdoqpMV0ieLZ1AAywRXm7OPqjKEF0c43ey3crNnJ9vS1oE0IZUxLyaulHoE",
	"RlKfYjpDHwbQj2evFN5heYvGBU3GmLd6SFPjShojAczxAN/Iyy9C2PqiI75JEZksMTXM8XH36ZEDnB9R",
	"bo35Y794CqatsZsRbSgMTmNaHs6wGIs/pDl3BGe3wrrIjupoCyj3DYykCuho0vFtGIpT6brb5N0PY279",
	"2dLtjahMzTDPw3uUkezj0vhO0v2x6pLi7W4aoouFsBVL9/RTWm910Uj0qeGC4+Yx+m/U2AVeDrFQd06Z",
	"RolMZF+6P4m3I1PaiESDMEXYJyQ7SetTqXJbBz8j5rZ81vDmFen05dnkip26Lj1+DyQ+xTE35PYcMTKp",
	"6LMv/LxTpxafPLyqkjp7ogSOF5OXBeimq8iPEU8HdUS6YmYmzy4sXt5MPHrNUPFJ5ky+lWW5872KzsUE",
	"pfo9/J0ISoZh/T9J3mma8kVcREIv1WKqr5uizRU1wCyUdWPdWDVWCobBdEYrqyubrGxsrBVMulpd3Sia",
	"RWONlXV9dc2orhl0nUweN8mh7zteKZ9HDl6mjrVccxnjS/jJtBv5o2J+BvVPnh0XW0fBq2+jTme/Dr8f",
	"dTpLXEmdFCAqOthEhJIOXiHqqKBy4WPfbcjb5/PDScVEuAhzj66ruEiONBMBkMEeXfzfAAAA//9jIx/A",
	"DCMAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
